# Generated by NeuroStack
# Artifact: agent/sample_prachi_agent


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_Account_detail = _ilu.spec_from_file_location(
    'Account_detail',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'Account_detail.py',
)
_mod_tools_Account_detail = _ilu.module_from_spec(_spec_tools_Account_detail)
_spec_tools_Account_detail.loader.exec_module(_mod_tools_Account_detail)
get_account_holder_names = _mod_tools_Account_detail.get_account_holder_names





# ============================================================================
# AGENT DEFINITION
# ============================================================================

sample_prachi_agent = Agent(
    name="sample_prachi_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        get_account_holder_names,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = sample_prachi_agent
