# Generated by NeuroStack
# Artifact: agent/final_test_with_all_artifacts


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_puppeter = _ilu.spec_from_file_location(
    'puppeter',
    _pl.Path(__file__).parent.parent.parent / 'mcp_servers' / 'external' / 'puppeter.py',
)
_mod_puppeter = _ilu.module_from_spec(_spec_puppeter)
_spec_puppeter.loader.exec_module(_mod_puppeter)
puppeter = _mod_puppeter.create_mcp_server
_spec_get_account_balances = _ilu.spec_from_file_location(
    'get_account_balances',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'get_account_balances.py',
)
_mod_get_account_balances = _ilu.module_from_spec(_spec_get_account_balances)
_spec_get_account_balances.loader.exec_module(_mod_get_account_balances)
get_account_balances = _mod_get_account_balances.get_account_balances
_spec_get_account_ids = _ilu.spec_from_file_location(
    'get_account_ids',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'get_account_ids.py',
)
_mod_get_account_ids = _ilu.module_from_spec(_spec_get_account_ids)
_spec_get_account_ids.loader.exec_module(_mod_get_account_ids)
get_account_ids = _mod_get_account_ids.get_account_ids
import pathlib
from google.adk.skills import load_skill_from_dir
from google.adk.tools.skill_toolset import SkillToolset



_skill_toolset = SkillToolset(
    skills=[
    load_skill_from_dir(pathlib.Path(__file__).parent.parent.parent / "skills" / "test-skill"),
    load_skill_from_dir(pathlib.Path(__file__).parent.parent.parent / "skills" / "newsapi-search"),
    ],
)


# ============================================================================
# AGENT DEFINITION
# ============================================================================

final_test_with_all_artifacts = Agent(
    name="final_test_with_all_artifacts",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[
        _skill_toolset,
        puppeter(),
        get_account_balances,
        get_account_ids,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = final_test_with_all_artifacts
