# Generated by NeuroStack
# Artifact: agent/final_test_with_all_artifacts

"""
System prompt for final_test_with_all_artifacts.
"""

AGENT_DESCRIPTION = """
sample desc
"""

SYSTEM_PROMPT = """
sample instr
"""
