# Generated by NeuroStack
# Artifact: agent/test_agent_tools_annotation_removal


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_get_current_time = _ilu.spec_from_file_location(
    'get_current_time',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'get_current_time.py',
)
_mod_get_current_time = _ilu.module_from_spec(_spec_get_current_time)
_spec_get_current_time.loader.exec_module(_mod_get_current_time)
get_current_time = _mod_get_current_time.get_current_time





# ============================================================================
# AGENT DEFINITION
# ============================================================================

test_agent_tools_annotation_removal = Agent(
    name="test_agent_tools_annotation_removal",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        get_current_time,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = test_agent_tools_annotation_removal
