# Generated by NeuroStack
# Artifact: agent/test_agent_tools_annotation_removal

"""
System prompt for test_agent_tools_annotation_removal.
"""

AGENT_DESCRIPTION = """
desc
"""

SYSTEM_PROMPT = """
instr
"""
