# Generated by NeuroStack
# Artifact: agent/test_agent_with_all_artifact

"""
System prompt for test_agent_with_all_artifact.
"""

AGENT_DESCRIPTION = """
Test agent with skills, tools and mcp
"""

SYSTEM_PROMPT = """
sample instr
"""
