# Generated by NeuroStack
# Vendored from platform origin: agent/story_discovery_agent_v2 (upstream_version=platform)

"""Story Discovery Agent - Fetches Jira story metadata."""

from .agent import root_agent
