# Generated by NeuroStack
# Vendored from platform origin: agent/story_discovery_agent_v2 (upstream_version=platform)

from __future__ import annotations
import sys
from pathlib import Path
max_output_tokens = 8192
# Ensure workspace root is in sys.path to resolve root-level 'core' imports
_project_root = str(Path(__file__).resolve().parents[3])
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

import logging
import warnings

from core.logging.config import add_file_handler_to_logger

logger = logging.getLogger(__name__)
add_file_handler_to_logger(logger)

warnings.filterwarnings("ignore", category=UserWarning, module="google.adk.tools.mcp_tool")
warnings.filterwarnings("ignore", category=UserWarning, module="google.adk.a2a")

from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())

from google.adk import Agent
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)
_spec_rel_tools = _ilu.spec_from_file_location(
    'tools',
    _pl.Path(__file__).parent / 'tools.py',
)
_mod_rel_tools = _ilu.module_from_spec(_spec_rel_tools)
_spec_rel_tools.loader.exec_module(_mod_rel_tools)
_spec_tools_global_tools = _ilu.spec_from_file_location(
    'global_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'global_tools.py',
)
_mod_tools_global_tools = _ilu.module_from_spec(_spec_tools_global_tools)
_spec_tools_global_tools.loader.exec_module(_mod_tools_global_tools)

SYSTEM_PROMPT = _mod_rel_prompt.SYSTEM_PROMPT

from modular_agents.agents.sdlc_agents.mcp_utils import create_jira_mcp_server
search_jira_stories_tool = _mod_rel_tools.search_jira_stories_tool
validate_story_results_tool = _mod_rel_tools.validate_story_results_tool
fetch_relevant_context_tool = _mod_tools_global_tools.fetch_relevant_context_tool
UNIVERSAL_CONTEXT_INSTRUCTION = _mod_tools_global_tools.UNIVERSAL_CONTEXT_INSTRUCTION

# Get model configuration from environment
jira_mcp_server = None
try:
    jira_mcp_server = create_jira_mcp_server()
    logger.info("[StoryScannerAgent] [OK] Jira MCP server created successfully")
    logger.info("[StoryScannerAgent] [INFO] MCP tools will be discovered dynamically by ADK at runtime")
except RuntimeError as e:
    logger.error(f"[StoryScannerAgent] [ERROR] Failed to create Jira MCP server: {e}")
except Exception as e:
    logger.error(f"[StoryScannerAgent] [ERROR] Unexpected error creating MCP server: {e}")
    logger.debug(f"[StoryScannerAgent] Error type: {type(e).__name__}", exc_info=True)
    logger.info("[StoryScannerAgent] Troubleshooting: Check uvx installation, env vars, and network connectivity")

tools_list = [validate_story_results_tool, search_jira_stories_tool, fetch_relevant_context_tool]
if jira_mcp_server is not None:
    tools_list.append(jira_mcp_server)
    logger.info("[StoryScannerAgent] [OK] Added MCPToolset to tools list - ADK will discover tools dynamically")
    logger.info("[StoryScannerAgent] [OK] Added validate_story_results tool for status filter enforcement")
else:
    logger.warning("[StoryScannerAgent] [WARNING] Jira MCP server not available!")
    logger.warning("[StoryScannerAgent] [WARNING] The agent will NOT be able to fetch Jira stories without the MCP server.")
    logger.warning("[StoryScannerAgent] [WARNING] Please fix the MCP server connection issue before using this agent.")

story_discovery_agent = Agent(
    name="story_discovery_agent_v2",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description="Story Discovery Agent using MCP toolsets to fetch story details from Jira.",
    instruction=UNIVERSAL_CONTEXT_INSTRUCTION + "\n\n" + SYSTEM_PROMPT,
    tools=tools_list,
    output_key="story_discovery",
    generate_content_config=types.GenerateContentConfig(
        response_mime_type="application/json",
        temperature=0.0,
        max_output_tokens=max_output_tokens,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = story_discovery_agent