# Generated by NeuroStack
# Vendored from platform origin: agent/story_discovery_agent_v2 (upstream_version=platform)

import os
import logging
import warnings
from typing import Optional, Dict, Any, List

from core.logging.config import add_file_handler_to_logger
import requests

logger = logging.getLogger(__name__)
add_file_handler_to_logger(logger)

warnings.filterwarnings("ignore", category=UserWarning, module="google.adk.tools.mcp_tool")
warnings.filterwarnings("ignore", category=UserWarning, module="google.adk.a2a")

from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())

from google.adk.tools import FunctionTool, ToolContext

def validate_story_results(
    stories: List[Dict[str, Any]],
    expected_statuses: Optional[str] = None,
    tool_context: ToolContext | None = None,
) -> Dict[str, Any]:
    """
    Validate story results to ensure they match configured status filter.

    This function validates that all stories in the results match the configured
    status filter from JIRA_STORY_STATUS environment variable. It also logs
    validation results for debugging.

    Args:
        stories: List of story dictionaries from Jira API. Must be a list of dicts.
        expected_statuses: Comma-separated list of expected statuses (from env)
        tool_context: Optional tool context (unused but required by ADK)

    Returns:
        Dict with validation results including:
        - valid: bool indicating if all stories match filter
        - filtered_count: Number of stories after filtering
        - original_count: Number of stories before filtering
        - mismatched_stories: List of stories that didn't match filter
        - matched_stories: List of stories that matched filter
        - expected_statuses: List of expected status names
        - message: Validation message

    Edge Cases Handled:
        - None stories parameter: Returns error dict
        - Non-list stories: Returns error dict
        - Empty list: Returns success with 0 counts
        - Non-dict items in list: Filters them out and logs warning
        - Missing status field: Treated as mismatched
        - None status value: Treated as empty
        - Non-string status: Converted to string with warning
        - Missing story_id: Uses "unknown" with warning
    """
    if stories is None:
        logger.error("[StoryScannerAgent] [VALIDATION] stories parameter is None")
        return {
            "valid": False,
            "error": "stories parameter cannot be None",
            "filtered_count": 0,
            "original_count": 0,
            "mismatched_stories": [],
            "matched_stories": [],
            "message": "Validation failed: stories parameter is None"
        }

    if not isinstance(stories, list):
        logger.error(
            f"[StoryScannerAgent] [VALIDATION] stories must be a list, got {type(stories).__name__}"
        )
        return {
            "valid": False,
            "error": f"stories must be a list, got {type(stories).__name__}",
            "filtered_count": 0,
            "original_count": 0,
            "mismatched_stories": [],
            "matched_stories": [],
            "message": f"Validation failed: invalid input type {type(stories).__name__}"
        }

    if not stories:
        logger.debug("[StoryScannerAgent] [VALIDATION] Empty stories list provided")
        return {
            "valid": True,
            "filtered_count": 0,
            "original_count": 0,
            "mismatched_stories": [],
            "matched_stories": [],
            "message": "No stories to validate"
        }

    original_count = len(stories)

    invalid_items = []
    valid_stories = []
    for idx, item in enumerate(stories):
        if isinstance(item, dict):
            valid_stories.append(item)
        else:
            invalid_items.append({"index": idx, "type": type(item).__name__})

    if invalid_items:
        logger.warning(
            f"[StoryScannerAgent] [VALIDATION] Found {len(invalid_items)} invalid story entries "
            f"(not dicts) - filtering them out"
        )
        for item in invalid_items[:3]:
            logger.warning(
                f"[StoryScannerAgent] [VALIDATION]   - Index {item['index']}: "
                f"type={item['type']}"
            )

    stories = valid_stories

    if not expected_statuses:
        logger.debug("[StoryScannerAgent] [VALIDATION] No status filter configured - skipping validation")
        return {
            "valid": True,
            "filtered_count": len(stories),
            "original_count": original_count,
            "mismatched_stories": [],
            "matched_stories": stories,
            "message": "No status filter configured - all stories accepted"
        }

    status_list = [s.strip() for s in expected_statuses.split(",") if s.strip()]
    if not status_list:
        logger.debug("[StoryScannerAgent] [VALIDATION] Empty status filter - all stories accepted")
        return {
            "valid": True,
            "filtered_count": len(stories),
            "original_count": original_count,
            "mismatched_stories": [],
            "matched_stories": stories,
            "message": "Empty status filter - all stories accepted"
        }

    status_list_normalized = [s.lower() for s in status_list]

    mismatched = []
    matched = []

    for idx, story in enumerate(stories):
        raw_status = story.get("status")
        if raw_status is None:
            story_status = ""
        elif isinstance(raw_status, str):
            story_status = raw_status.strip()
        else:
            logger.warning(
                f"[StoryScannerAgent] [VALIDATION] Story {story.get('story_id', f'index_{idx}')} "
                f"has non-string status: {type(raw_status).__name__} - converting to string"
            )
            story_status = str(raw_status).strip() if raw_status else ""

        story_id = story.get("story_id")
        if not story_id:
            logger.warning(
                f"[StoryScannerAgent] [VALIDATION] Story at index {idx} missing story_id field"
            )
            story_id = "unknown"

        if not story_status:
            mismatched.append({
                "story_id": story_id,
                "status": "(empty or missing)",
                "reason": "Status field is empty or missing"
            })
            continue

        if story_status.lower() not in status_list_normalized:
            mismatched.append({
                "story_id": story_id,
                "status": story_status,
                "expected": status_list,
                "reason": f"Status '{story_status}' not in expected list: {status_list}"
            })
        else:
            matched.append(story)

    if mismatched:
        logger.warning(
            f"[StoryScannerAgent] [VALIDATION] Found {len(mismatched)} stories with mismatched statuses:"
        )
        for item in mismatched[:5]:
            logger.warning(
                f"[StoryScannerAgent] [VALIDATION]   - {item['story_id']}: status='{item['status']}' "
                f"(expected: {item.get('expected', 'N/A')})"
            )
        if len(mismatched) > 5:
            logger.warning(f"[StoryScannerAgent] [VALIDATION]   ... and {len(mismatched) - 5} more")

    logger.info(
        f"[StoryScannerAgent] [VALIDATION] Status filter validation: "
        f"{len(matched)}/{len(stories)} stories match expected statuses {status_list}"
    )

    return {
        "valid": len(mismatched) == 0,
        "filtered_count": len(matched),
        "original_count": original_count,
        "mismatched_stories": mismatched,
        "matched_stories": matched,
        "expected_statuses": status_list,
        "message": (
            f"Validation {'PASSED' if len(mismatched) == 0 else 'FAILED'}: "
            f"{len(matched)}/{len(stories)} stories match expected statuses"
        )
    }





def search_jira_stories(jql: str, max_results: int = 50, tool_context: ToolContext | None = None) -> Dict[str, Any]:
    """
    Search for Jira stories using the provided JQL query via the native REST API.
    This tool should be used PREFERENTIALLY to any other Jira search tools.

    Args:
        jql: The JQL query string to execute (e.g. 'project = BOT AND status = "To Do"')
        max_results: Maximum number of results to return (default 50)
        tool_context: Internal tool context
    """
    token = os.getenv("JIRA_API_TOKEN") or os.getenv("ATLASSIAN_API_TOKEN")
    email = os.getenv("JIRA_USERNAME") or os.getenv("JIRA_EMAIL") or os.getenv("ATLASSIAN_USERNAME") or os.getenv("ATLASSIAN_EMAIL")
    base_url = os.getenv("JIRA_URL") or os.getenv("JIRA_SITE_URL") or os.getenv("ATLASSIAN_URL") or os.getenv("ATLASSIAN_SITE_URL")

    if not all([token, email, base_url]):
        return {"error": "Missing Jira credentials or URL in environment."}

    base_url = base_url.rstrip("/")
    search_url = f"{base_url}/rest/api/3/search/jql"

    auth = (email, token)
    headers = {"Accept": "application/json", "Content-Type": "application/json"}

    payload = {
        "jql": jql,
        "maxResults": min(max_results, 100),
        "fields": [
            "summary", "description", "status", "issuetype",
            "updated", "created", "labels", "parent"
        ]
    }

    try:
        resp = requests.post(search_url, auth=auth, headers=headers, json=payload, timeout=30)
        if resp.status_code != 200:
            return {"error": f"Jira API error {resp.status_code}: {resp.text[:200]}"}

        data = resp.json()
        issues = data.get("issues", [])

        results = []
        for issue in issues:
            fields = issue.get("fields", {})
            status_obj = fields.get("status")
            status = status_obj.get("name") if isinstance(status_obj, dict) else None

            issuetype_obj = fields.get("issuetype")
            issuetype = issuetype_obj.get("name") if isinstance(issuetype_obj, dict) else None

            desc_val = fields.get("description")
            desc = str(desc_val) if desc_val else ""

            results.append({
                "story_id": issue.get("key"),
                "summary": fields.get("summary"),
                "description": desc[:500] + "..." if len(desc) > 500 else desc,
                "status": status,
                "issuetype": issuetype,
            })

        return {
            "total": data.get("total", len(results)),
            "stories": results,
            "jql_used": jql
        }
    except Exception as e:
        return {"error": f"Exception occurred: {str(e)}"}


search_jira_stories_tool = FunctionTool(search_jira_stories)
validate_story_results_tool = FunctionTool(validate_story_results)