# Generated by NeuroStack
# Artifact: workflow/story_to_code_with_review_workflow

"""
Graph-Based Workflow: story_to_code_with_review_workflow
Automated SDLC pipeline that fetches Jira stories, generates code, and includes human review with revision loop.

Auto-generated by the Graph Workflow Studio.
ADK Docs: https://adk.dev/graphs/routes/
          https://adk.dev/graphs/human-input/
"""
from __future__ import annotations
from dotenv import load_dotenv, find_dotenv
from google.adk import Agent, Workflow, Event, Context
from google.adk import Context
from google.adk.events import RequestInput
from google.adk.workflow import node
from google.genai import types as genai_types
import importlib.util as _ilu
import pathlib as _pl
_spec_agents_code_generation_agent_v2 = _ilu.spec_from_file_location(
    'code_generation_agent_v2',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'code_generation_agent_v2' / 'agent.py',
)
_mod_agents_code_generation_agent_v2 = _ilu.module_from_spec(_spec_agents_code_generation_agent_v2)
_spec_agents_code_generation_agent_v2.loader.exec_module(_mod_agents_code_generation_agent_v2)
_spec_agents_story_discovery_agent_v2 = _ilu.spec_from_file_location(
    'story_discovery_agent_v2',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'story_discovery_agent_v2' / 'agent.py',
)
_mod_agents_story_discovery_agent_v2 = _ilu.module_from_spec(_spec_agents_story_discovery_agent_v2)
_spec_agents_story_discovery_agent_v2.loader.exec_module(_mod_agents_story_discovery_agent_v2)

code_generation = _mod_agents_code_generation_agent_v2.root_agent
story_discovery = _mod_agents_story_discovery_agent_v2.root_agent
from pydantic import BaseModel
from pydantic import BaseModel, Field, model_validator
from typing import Any
import os, re

load_dotenv(find_dotenv())


# ──────────────────────────────────────────────
# Pydantic Schemas
# ──────────────────────────────────────────────
# (No custom schemas)

# ──────────────────────────────────────────────
# Agent Definitions
# ──────────────────────────────────────────────
# (No agent nodes defined)

# ──────────────────────────────────────────────
# Join Nodes — Fan-in for parallel branches
# ──────────────────────────────────────────────
# (No join nodes)

# ──────────────────────────────────────────────
# Function Nodes — Plain Python (no LLM)
# ──────────────────────────────────────────────
# (No function nodes)

# ──────────────────────────────────────────────
# HITL Nodes — yield RequestInput(...) to pause for human input
# ──────────────────────────────────────────────
_SKIP_PREFIXES = ("_adk", "__", "_", "temp:", "workflow_status")


class UserReviewFeedback(BaseModel):
    approved: bool = Field(description="True to approve the output, False to request revisions.")
    feedback: str = Field(
        default="",
        description="Required when declining — describe what should be changed.",
    )

    @model_validator(mode="after")
    def feedback_required_on_decline(self) -> "UserReviewFeedback":
        if not self.approved and not self.feedback.strip():
            raise ValueError("feedback is required when declining.")
        return self


def _extract_text_from_node_input(node_input) -> str:
    if node_input is None:
        return ""
    if isinstance(node_input, genai_types.Content):
        return "\n".join(
            part.text
            for part in (node_input.parts or [])
            if hasattr(part, "text") and part.text
        ).strip()
    if isinstance(node_input, str):
        return node_input.strip()
    if hasattr(node_input, "model_dump"):
        return str(node_input.model_dump())
    return str(node_input).strip()


def _is_internal_key(key: str) -> bool:
    return any(key.startswith(p) for p in _SKIP_PREFIXES)


def _build_review_body(ctx: Context) -> str:
    sections = []
    for key, value in ctx.state.to_dict().items():
        if _is_internal_key(key) or not value:
            continue
        lbl = key.replace("_", " ").title()
        text = str(value).strip()
        if text.startswith(("{", "[")) or "\n" in text:
            sections.append(f"### {lbl}\n{text}")
        else:
            sections.append(f"### {lbl}\n{text}")
    return (
        "\n\n".join(sections)
        if sections
        else "_No agent outputs found in session state._"
    )


def _make_text_event(text: str, state: dict | None = None) -> Event:
    return Event(
        output=text,
        content=genai_types.Content(
            role="model",
            parts=[genai_types.Part(text=text)],
        ),
        **({"state": state} if state else {}),
    )


def _parse_review_response(raw) -> UserReviewFeedback:
    import json as _json
    import logging as _logging
    if isinstance(raw, UserReviewFeedback):
        return raw
    if isinstance(raw, dict):
        try:
            return UserReviewFeedback.model_validate(raw)
        except Exception:
            pass
    if isinstance(raw, str):
        try:
            parsed = _json.loads(raw)
            if isinstance(parsed, dict):
                return UserReviewFeedback.model_validate(parsed)
        except Exception:
            pass
    if isinstance(raw, genai_types.Content):
        for part in (raw.parts or []):
            if hasattr(part, "function_response") and part.function_response:
                resp = part.function_response.response or {}
                if isinstance(resp, dict):
                    try:
                        return UserReviewFeedback.model_validate(resp)
                    except Exception:
                        pass
            if hasattr(part, "text") and part.text:
                try:
                    parsed = _json.loads(part.text)
                    if isinstance(parsed, dict):
                        return UserReviewFeedback.model_validate(parsed)
                except Exception:
                    pass
    _logging.getLogger(__name__).warning(
        "[code_review_gate] Could not parse resume_input (%s: %r). "
        "Defaulting to approved=True so the workflow can complete.",
        type(raw).__name__, raw,
    )
    return UserReviewFeedback(approved=True, feedback="")

@node(rerun_on_resume=True)
def code_review_gate(node_input, ctx: Context = None):
    """Human-in-the-Loop gate: Does the generated code meet requirements? Approve to proceed, or describe changes needed."""
    iteration = ctx.state.get("iterations_code_review_gate", 0) if ctx else 0
    interrupt_id = f"code_review_gate:iter{iteration}"
    resume_input = ctx.resume_inputs.get(interrupt_id) if ctx else None

    if not resume_input:
        last_output_text = _extract_text_from_node_input(node_input)
        if last_output_text:
            yield Event(state={"_hitl:last_output_code_review_gate": last_output_text})
        body = _build_review_body(ctx) if ctx else ""
        if "_No agent outputs found" in body:
            body = ""
        else:
            body = f"\n\n---\n### Session State\n{body}"

        review_content = f"### Output for Review\n{last_output_text}" if last_output_text else "_(No direct output received)_"
        msg = f"**[Review Cycle {iteration + 1} of 5]**\n\n{review_content}{body}\n\n---\nDoes the generated code meet requirements? Approve to proceed, or describe changes needed."
        yield RequestInput(message=msg, response_schema=UserReviewFeedback, interrupt_id=interrupt_id)
        return

    review_response = _parse_review_response(resume_input)
    if review_response.approved:
        last_output = ctx.state.get("_hitl:last_output_code_review_gate") or "_No output recorded._"
        # Route to next node via "approved" edge if wired; else workflow ends here.
        yield Event(
            output=last_output,
            content=genai_types.Content(
                role="model",
                parts=[genai_types.Part(text=last_output)],
            ),
            state={"workflow_status": "APPROVED"},
            route="approved",
        )
        return

    iterations = ctx.state.get("iterations_code_review_gate", 0) + 1
    if iterations > 5:
        last_output: str = ctx.state.get("_hitl:last_output_code_review_gate") or "_No output recorded._"
        # Route to next node via "approved" edge; forced approval due to max cycles.
        yield Event(
            output=last_output,
            content=genai_types.Content(
                role="model",
                parts=[genai_types.Part(text=last_output)],
            ),
            state={"workflow_status": "MAX_REVISIONS_REACHED"},
            route="approved",
        )
        return

    last_output_text = ctx.state.get(f"_hitl:last_output_code_review_gate") or "_No output recorded._"
    yield Event(
        content=genai_types.Content(
            role="user",
            parts=[genai_types.Part(
                text=(
                    "The user rejected your previous output. "
                    f"Please revise it based on this feedback:\n\n{review_response.feedback}\n\n"
                    "---\n### Your Previous Output\n\n"
                    f"{last_output_text}"
                )
            )],
        ),
        state={
            "iterations_code_review_gate": iterations,
            "feedback_code_review_gate": review_response.feedback,
        },
        route="revise",
    )

# ──────────────────────────────────────────────
# Router Nodes — return Event(route=KEY) for conditional branching
# ──────────────────────────────────────────────
# (No router nodes)

# ──────────────────────────────────────────────
# Workflow Graph
# ──────────────────────────────────────────────
root_agent = Workflow(
    name="story_to_code_with_review_workflow",
    edges=[
        ("START", story_discovery),
        (story_discovery, code_generation),
        (code_generation, code_review_gate),
        (code_review_gate,
            {
            "revise": code_generation
            },
        ),
    ]
)
