# Generated by NeuroStack
# Artifact: agent/agent_with_r_k_skill


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_calculator_server = _ilu.spec_from_file_location(
    'calculator_server',
    _pl.Path(__file__).parent.parent.parent / 'mcp_servers' / 'internal' / 'calculator_server.py',
)
_mod_calculator_server = _ilu.module_from_spec(_spec_calculator_server)
_spec_calculator_server.loader.exec_module(_mod_calculator_server)
calculator_server = _mod_calculator_server.create_mcp_server
import pathlib
from google.adk.skills import load_skill_from_dir
from google.adk.tools.skill_toolset import SkillToolset



_skill_toolset = SkillToolset(
    skills=[
    load_skill_from_dir(pathlib.Path(__file__).parent.parent.parent / "skills" / "sample-r-k-skill"),
    ],
)


# ============================================================================
# AGENT DEFINITION
# ============================================================================

agent_with_r_k_skill = Agent(
    name="agent_with_r_k_skill",
    model='openai/gpt-5',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[
        _skill_toolset,
        calculator_server(),
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = agent_with_r_k_skill
