# Generated by NeuroStack
# Artifact: agent/agent_with_r_k_skill

"""
System prompt for agent_with_r_k_skill.
"""

AGENT_DESCRIPTION = """
t/r 3 test with skill
"""

SYSTEM_PROMPT = """
sample instr
"""
