# Generated by NeuroStack
# Vendored from platform origin: agent/github_push_agent_v2 (upstream_version=platform)

from __future__ import annotations

import sys
from pathlib import Path

from modular_agents.agents.github_push_agent_v2.github_server import run_github_flow_tool

# Ensure workspace root is in sys.path to resolve root-level imports
_project_root = str(Path(__file__).resolve().parents[3])
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

import logging
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

from google.adk.agents import Agent
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)
_spec_tools_global_tools = _ilu.spec_from_file_location(
    'global_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'global_tools.py',
)
_mod_tools_global_tools = _ilu.module_from_spec(_spec_tools_global_tools)
_spec_tools_global_tools.loader.exec_module(_mod_tools_global_tools)

fetch_relevant_context_tool = _mod_tools_global_tools.fetch_relevant_context_tool
UNIVERSAL_CONTEXT_INSTRUCTION = _mod_tools_global_tools.UNIVERSAL_CONTEXT_INSTRUCTION

from modular_agents.agents.sdlc_agents.mcp_utils import sanitize_tool_descriptions_callback
from modular_agents.core.llm import get_llm_backend_name, get_llm_model_name

from core.logging.config import add_file_handler_to_logger

AGENT_INSTRUCTION = _mod_rel_prompt.AGENT_INSTRUCTION
AGENT_DESCRIPTION = _mod_rel_prompt.AGENT_DESCRIPTION

logger = logging.getLogger(__name__)
add_file_handler_to_logger(logger)

# ── LLM config ────────────────────────────────────────────────────────────────

max_output_tokens = 8192

logger.info(
    "GitHubPushAgent LLM configuration: model=%s, backend=%s, max_tokens=%s",
    get_llm_model_name(),
    get_llm_backend_name(),
    max_output_tokens,
)

# ── Tools ──────────────────────────────────────────────────────────────────────

tools_list: list = [
    fetch_relevant_context_tool,
    run_github_flow_tool(),
]

# ── Callbacks ──────────────────────────────────────────────────────────────────

from modular_agents.core.agent_instrumentation import make_instrumented_callbacks
from modular_agents.agents.sdlc_agents.context_projection import truncate_context_in_request

_system_name = get_llm_backend_name()
_callbacks = make_instrumented_callbacks(
    "github_push_agent",
    system_name=_system_name,
)


def chained_before_model_callback(callback_context, llm_request):
    try:
        truncate_context_in_request(llm_request, agent_name="github_push_agent")
    except Exception as exc:
        logger.warning("GitHubPushAgent: context truncation failed: %s", exc)
    sanitize_tool_descriptions_callback(callback_context, llm_request)
    _callbacks["before_model"](callback_context, llm_request)


def chained_before_tool_callback(tool, args, tool_context):
    return _callbacks["before_tool"](tool, args, tool_context)


# ── Agent ──────────────────────────────────────────────────────────────────────

github_push_agent = Agent(
    name="github_push_agent_v2",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=UNIVERSAL_CONTEXT_INSTRUCTION + "\n\n" + AGENT_INSTRUCTION,
    tools=tools_list,
    output_key="github_push_result",
    generate_content_config=types.GenerateContentConfig(
        response_mime_type="application/json",
        temperature=0.1,
        max_output_tokens=max_output_tokens,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ],
    ),
)

logger.info("GitHubPushAgent created successfully")

root_agent = github_push_agent



logger.info("GitHubPushAgent runner initialized")
