# Generated by NeuroStack
# Artifact: workflow/sample_wf

"""
Workflow: sample_wf
Description: desc
Instructions: instr
"""
from __future__ import annotations
from google.adk import Agent
from google.adk.tools import load_memory
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_agents_azure_devops_agent = _ilu.spec_from_file_location(
    'azure_devops_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'azure_devops_agent' / 'agent.py',
)
_mod_agents_azure_devops_agent = _ilu.module_from_spec(_spec_agents_azure_devops_agent)
_spec_agents_azure_devops_agent.loader.exec_module(_mod_agents_azure_devops_agent)
_spec_agents_documentation_agent = _ilu.spec_from_file_location(
    'documentation_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'documentation_agent' / 'agent.py',
)
_mod_agents_documentation_agent = _ilu.module_from_spec(_spec_agents_documentation_agent)
_spec_agents_documentation_agent.loader.exec_module(_mod_agents_documentation_agent)

documentation_agent = _mod_agents_documentation_agent.root_agent
azure_devops_agent = _mod_agents_azure_devops_agent.root_agent





root_agent = Agent(
    model='gemini-2.5-pro',
    name="sample_wf",
    description="""desc""",
    instruction="""instr""",
    global_instruction="""instr""",
    sub_agents=[documentation_agent, azure_devops_agent],
    generate_content_config=types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
    tools=[load_memory],
)
