# Generated by NeuroStack
# Artifact: agent/final_test_2_with_uncommited_mcp_skill_tool


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_notion_server = _ilu.spec_from_file_location(
    'notion_server',
    _pl.Path(__file__).parent.parent.parent / 'mcp_servers' / 'external' / 'notion_server.py',
)
_mod_notion_server = _ilu.module_from_spec(_spec_notion_server)
_spec_notion_server.loader.exec_module(_mod_notion_server)
notion_server = _mod_notion_server.create_mcp_server
_spec_get_current_time = _ilu.spec_from_file_location(
    'get_current_time',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'get_current_time.py',
)
_mod_get_current_time = _ilu.module_from_spec(_spec_get_current_time)
_spec_get_current_time.loader.exec_module(_mod_get_current_time)
get_current_time = _mod_get_current_time.get_current_time
import pathlib
from google.adk.skills import load_skill_from_dir
from google.adk.tools.skill_toolset import SkillToolset



_skill_toolset = SkillToolset(
    skills=[
    load_skill_from_dir(pathlib.Path(__file__).parent.parent.parent / "skills" / "final-test-skill-2"),
    ],
)


# ============================================================================
# AGENT DEFINITION
# ============================================================================

final_test_2_with_uncommited_mcp_skill_tool = Agent(
    name="final_test_2_with_uncommited_mcp_skill_tool",
    model='gemini/gemini-2.5-flash-lite',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[
        _skill_toolset,
        notion_server(),
        get_current_time,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.1,
        max_output_tokens=4096,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = final_test_2_with_uncommited_mcp_skill_tool
