# Generated by NeuroStack
# Artifact: agent/final_test_2_with_uncommited_mcp_skill_tool

"""
System prompt for final_test_2_with_uncommited_mcp_skill_tool.
"""

AGENT_DESCRIPTION = """
final test 2
"""

SYSTEM_PROMPT = """
final test 2 str
"""
