# Generated by NeuroStack
# Artifact: agent/new_agent


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

# No MCP servers configured





# ============================================================================
# AGENT DEFINITION
# ============================================================================

new_agent = Agent(
    name="new_agent",
    model=model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0' llm_client=<google.adk.models.lite_llm.LiteLLMClient object at 0x0000019C013C6AD0>,
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[


    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = new_agent
