# Generated by NeuroStack
# Artifact: workflow/sample_wf_1

"""
Graph-Based Workflow: sample_wf_1
Graph-based ADK workflow 'sample_wf_1'

Auto-generated by the Graph Workflow Studio.
ADK Docs: https://adk.dev/graphs/routes/
          https://adk.dev/graphs/human-input/
"""
from __future__ import annotations
from dotenv import load_dotenv, find_dotenv
from google.adk import Agent, Workflow, Event, Context
import importlib.util as _ilu
import pathlib as _pl
_spec_agents_github_push_agent_v2 = _ilu.spec_from_file_location(
    'github_push_agent_v2',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'github_push_agent_v2' / 'agent.py',
)
_mod_agents_github_push_agent_v2 = _ilu.module_from_spec(_spec_agents_github_push_agent_v2)
_spec_agents_github_push_agent_v2.loader.exec_module(_mod_agents_github_push_agent_v2)
_spec_agents_story_discovery_agent_v2 = _ilu.spec_from_file_location(
    'story_discovery_agent_v2',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'story_discovery_agent_v2' / 'agent.py',
)
_mod_agents_story_discovery_agent_v2 = _ilu.module_from_spec(_spec_agents_story_discovery_agent_v2)
_spec_agents_story_discovery_agent_v2.loader.exec_module(_mod_agents_story_discovery_agent_v2)

github_push_agent_v2 = _mod_agents_github_push_agent_v2.root_agent
story_discovery_agent_v2 = _mod_agents_story_discovery_agent_v2.root_agent
from pydantic import BaseModel
from typing import Any
import os, re

load_dotenv(find_dotenv())


# ──────────────────────────────────────────────
# Pydantic Schemas
# ──────────────────────────────────────────────
# (No custom schemas)

# ──────────────────────────────────────────────
# Agent Definitions
# ──────────────────────────────────────────────
# (No agent nodes defined)

# ──────────────────────────────────────────────
# Join Nodes — Fan-in for parallel branches
# ──────────────────────────────────────────────
# (No join nodes)

# ──────────────────────────────────────────────
# Function Nodes — Plain Python (no LLM)
# ──────────────────────────────────────────────
# (No function nodes)

# ──────────────────────────────────────────────
# HITL Nodes — yield RequestInput(...) to pause for human input
# ──────────────────────────────────────────────
# (No HITL nodes)

# ──────────────────────────────────────────────
# Router Nodes — return Event(route=KEY) for conditional branching
# ──────────────────────────────────────────────
# (No router nodes)

# ──────────────────────────────────────────────
# Workflow Graph
# ──────────────────────────────────────────────
root_agent = Workflow(
    name="sample_wf_1",
    edges=[
        ("START", story_discovery_agent_v2),
        (story_discovery_agent_v2, github_push_agent_v2),
    ]
)
