# Generated by NeuroStack
# Artifact: agent/test_agent_for_mcp


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_sample_mcp_server = _ilu.spec_from_file_location(
    'sample_mcp_server',
    _pl.Path(__file__).parent.parent.parent / 'mcp_servers' / 'internal' / 'sample_mcp_server.py',
)
_mod_sample_mcp_server = _ilu.module_from_spec(_spec_sample_mcp_server)
_spec_sample_mcp_server.loader.exec_module(_mod_sample_mcp_server)
sample_mcp_server = _mod_sample_mcp_server.create_mcp_server





# ============================================================================
# AGENT DEFINITION
# ============================================================================

test_agent_for_mcp = Agent(
    name="test_agent_for_mcp",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        sample_mcp_server(),
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = test_agent_for_mcp
