# Generated by NeuroStack
# Vendored from platform origin: agent/code_generation_agent_v2 (upstream_version=platform)

from __future__ import annotations

import sys
from pathlib import Path

# Ensure workspace root is in sys.path to resolve root-level 'core' imports
_project_root = str(Path(__file__).resolve().parents[3])
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

import pathlib
import logging
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

from google.adk.agents import Agent
from google.genai import types
from google.adk.tools import FunctionTool
from google.adk.skills import load_skill_from_dir
from google.adk.tools import skill_toolset

import importlib.util as _ilu
import pathlib as _pl
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)
_spec_rel_tools = _ilu.spec_from_file_location(
    'tools',
    _pl.Path(__file__).parent / 'tools.py',
)
_mod_rel_tools = _ilu.module_from_spec(_spec_rel_tools)
_spec_rel_tools.loader.exec_module(_mod_rel_tools)
_spec_tools_global_tools = _ilu.spec_from_file_location(
    'global_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'global_tools.py',
)
_mod_tools_global_tools = _ilu.module_from_spec(_spec_tools_global_tools)
_spec_tools_global_tools.loader.exec_module(_mod_tools_global_tools)

fetch_relevant_context_tool = _mod_tools_global_tools.fetch_relevant_context_tool
UNIVERSAL_CONTEXT_INSTRUCTION = _mod_tools_global_tools.UNIVERSAL_CONTEXT_INSTRUCTION

AGENT_INSTRUCTION = _mod_rel_prompt.AGENT_INSTRUCTION
AGENT_DESCRIPTION = _mod_rel_prompt.AGENT_DESCRIPTION
fetch_github_tree = _mod_rel_tools.fetch_github_tree
fetch_url_content = _mod_rel_tools.fetch_url_content

from modular_agents.agents.sdlc_agents.mcp_utils import sanitize_tool_descriptions_callback
from modular_agents.core.llm import get_llm_backend_name, get_llm_model_name

from core.logging.config import add_file_handler_to_logger

logger = logging.getLogger(__name__)
add_file_handler_to_logger(logger)

# ── External Context Tools ─────────────────────────────────────────────────────

fetch_github_tree_tool = FunctionTool(fetch_github_tree)
fetch_url_content_tool = FunctionTool(fetch_url_content)

# ── LLM config ────────────────────────────────────────────────────────────────

max_output_tokens = 16384

logger.info(
    "LLM configuration: model=%s, backend=%s, max_tokens=%s",
    get_llm_model_name(),
    get_llm_backend_name(),
    max_output_tokens,
)

# ── Skills ─────────────────────────────────────────────────────────────────────

_skills_dir = pathlib.Path(__file__).parent / "skills"


def _load_skill(name: str):
    skill_path = _skills_dir / name
    if not skill_path.exists():
        logger.warning("Skill directory not found, skipping: %s", skill_path)
        return None
    try:
        skill = load_skill_from_dir(skill_path)
        logger.info("Loaded skill: %s", name)
        return skill
    except Exception as exc:
        logger.warning("Failed to load skill '%s': %s", name, exc)
        return None


_all_skills = [
    _load_skill("backend-java-springboot"),   # default
    _load_skill("backend-dotnet-aspnet"),
    _load_skill("backend-php-laravel"),
    _load_skill("backend-python-flask"),
    _load_skill("backend-node-express"),
    _load_skill("frontend-vanilla"),
]

_loaded_skills = [s for s in _all_skills if s is not None]
logger.info("Skills loaded: %d / %d", len(_loaded_skills), len(_all_skills))

code_gen_skillset = skill_toolset.SkillToolset(skills=_loaded_skills)

# ── Tools ──────────────────────────────────────────────────────────────────────
# CodeGenerationAgent intentionally does NOT contain GitHub/GitLab push tools.
# Repository push is handled by github_push_agent.

tools_list = [
    code_gen_skillset,
    fetch_github_tree_tool,
    fetch_url_content_tool,
    fetch_relevant_context_tool,
]

# ── Callbacks ──────────────────────────────────────────────────────────────────

from modular_agents.core.agent_instrumentation import make_instrumented_callbacks
from modular_agents.agents.sdlc_agents.context_projection import truncate_context_in_request

_system_name = get_llm_backend_name()
_callbacks = make_instrumented_callbacks(
    "code_generation_agent",
    system_name=_system_name,
)


def chained_before_model_callback(callback_context, llm_request):
    try:
        truncate_context_in_request(llm_request, agent_name="code_generation_agent")
    except Exception as exc:
        logger.warning("CodeGenerationAgent: context truncation failed: %s", exc)
    sanitize_tool_descriptions_callback(callback_context, llm_request)
    _callbacks["before_model"](callback_context, llm_request)


def chained_before_tool_callback(tool, args, tool_context):
    return _callbacks["before_tool"](tool, args, tool_context)


# ── Agent ──────────────────────────────────────────────────────────────────────

code_generation_agent = Agent(
    name="code_generation_agent_v2",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=UNIVERSAL_CONTEXT_INSTRUCTION + "\n\n" + AGENT_INSTRUCTION,
    tools=tools_list,
    output_key="generated_code",
    generate_content_config=types.GenerateContentConfig(
        response_mime_type="application/json",
        temperature=0.2,
        max_output_tokens=max_output_tokens,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ],
    ),
)

logger.info("CodeGenerationAgent created successfully")

root_agent = code_generation_agent



logger.info("CodeGenerationAgent runner initialized")
