# Generated by NeuroStack
# Vendored from platform origin: agent/code_generation_agent_v2 (upstream_version=platform)


from typing import Dict, Any
import re
import os
import logging
import requests
from google.adk.tools import ToolContext
from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)


def fetch_github_tree(
    github_url: str,
    tool_context: ToolContext | None = None,
) -> dict[str, Any]:
    """
    Fetch the folder/directory tree of a public GitHub repository.
    Returns directory paths and root-level files ONLY — no file content is read.

    Use this when resolved_config.references.github_repo is NOT null.
    The returned directory_structure[] becomes resolved_config.custom_structure[].

    Args:
        github_url: Full GitHub repo URL (e.g. https://github.com/laravel/laravel)
        tool_context: Internal tool context (unused)
    """
    try:
        match = re.match(r"https?://github\.com/([^/\s]+)/([^/\s?#]+)", github_url.strip())
        if not match:
            return {
                "error": f"Invalid GitHub URL: {github_url}",
                "directory_structure": [],
                "root_files": [],
            }

        owner = match.group(1)
        # 🔴 Bug 3 fix: rstrip(".git") strips chars, not the suffix
        raw_repo = match.group(2)
        repo = raw_repo[:-4] if raw_repo.endswith(".git") else raw_repo
        api_base = f"https://api.github.com/repos/{owner}/{repo}"

        # 🔴 Bug 2 fix: correct Accept header + required X-GitHub-Api-Version
        headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "Neurostack-CodeGen/1.0",
        }
        token = os.getenv("GITHUB_TOKEN") or os.getenv("GITHUB_API_TOKEN")
        if token:
            headers["Authorization"] = f"Bearer {token}"

        # Step 1 — get default branch
        repo_resp = requests.get(api_base, headers=headers, timeout=15)
        # ⚠️ Issue 4 fix: separate 403 (rate-limit / forbidden) from other errors
        if repo_resp.status_code == 403:
            return {
                "error": "GitHub rate limit hit or access forbidden. Set GITHUB_TOKEN env var to increase limits.",
                "directory_structure": [],
                "root_files": [],
            }
        if repo_resp.status_code == 404:
            return {
                "error": f"Repository not found: {owner}/{repo}",
                "directory_structure": [],
                "root_files": [],
            }
        if repo_resp.status_code != 200:
            return {
                "error": f"GitHub API error {repo_resp.status_code}: {repo_resp.text[:200]}",
                "directory_structure": [],
                "root_files": [],
            }

        default_branch = repo_resp.json().get("default_branch", "main")

        # Step 2 — fetch full recursive tree
        tree_url = f"{api_base}/git/trees/{default_branch}?recursive=1"
        tree_resp = requests.get(tree_url, headers=headers, timeout=20)
        if tree_resp.status_code == 403:
            return {
                "error": "GitHub rate limit hit fetching tree. Set GITHUB_TOKEN env var.",
                "directory_structure": [],
                "root_files": [],
            }
        if tree_resp.status_code != 200:
            return {
                "error": f"Tree fetch failed: HTTP {tree_resp.status_code}",
                "directory_structure": [],
                "root_files": [],
            }

        tree_data = tree_resp.json()
        # 🔴 Bug 1 fix: surface truncated flag — GitHub caps at 100k entries / 7 MB
        api_truncated = tree_data.get("truncated", False)
        tree_items = tree_data.get("tree", [])

        # Directories only (no file content fetched)
        directories = [
            item["path"] for item in tree_items
            if item.get("type") == "tree"
        ]

        # Root-level file names for context (no content)
        root_files = [
            item["path"] for item in tree_items
            if item.get("type") == "blob" and "/" not in item["path"]
        ]

        if api_truncated:
            logger.warning(
                "fetch_github_tree: %s/%s tree was truncated by GitHub API — results are partial",
                owner, repo,
            )
        logger.info(
            "fetch_github_tree: %s/%s — %d dirs, %d root files (truncated=%s)",
            owner, repo, len(directories), len(root_files), api_truncated,
        )

        return {
            "owner": owner,
            "repo": repo,
            "default_branch": default_branch,
            "directory_structure": directories,
            "root_files": root_files,
            "total_directories": len(directories),
            "truncated": api_truncated,
            "warning": (
                "GitHub API truncated the tree — results are incomplete. "
                "Repo may exceed 100k entries or 7 MB."
            ) if api_truncated else None,
        }

    except requests.exceptions.Timeout:
        return {"error": "Request timed out fetching GitHub tree", "directory_structure": [], "root_files": []}
    except Exception as exc:
        logger.warning("fetch_github_tree error: %s", exc)
        return {"error": f"Unexpected error: {str(exc)}", "directory_structure": [], "root_files": []}


def fetch_url_content(
    url: str,
    tool_context: ToolContext | None = None,
) -> Dict[str, Any]:
    """
    Fetch a public URL and return its clean text content.

    Use this when resolved_config.references.docs[] is NOT empty.
    Extracts tech guidance (framework versions, config patterns, recommended
    libraries) from documentation pages to inform code generation.

    Args:
        url: Public URL to fetch (e.g. https://laravel.com/docs/12.x/eloquent)
        tool_context: Internal tool context (unused)
    """
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (compatible; Neurostack-CodeGen/1.0)",
            "Accept": "text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
        }

        resp = requests.get(url, headers=headers, timeout=15, allow_redirects=True)
        if resp.status_code != 200:
            return {"error": f"HTTP {resp.status_code}", "url": url, "content": None}

        content_type = resp.headers.get("Content-Type", "")

        if "text/html" in content_type:
            # ⚠️ Issue 1 fix: set encoding before parsing to avoid garbled text
            resp.encoding = resp.apparent_encoding or "utf-8"
            # 💡 Style fix: use find_all (explicit recommended API)
            soup = BeautifulSoup(resp.text, "html.parser")
            for tag in soup.find_all(["script", "style", "nav", "footer", "header", "aside", "form"]):
                tag.decompose()
            text = soup.get_text(separator="\n", strip=True)
            lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
            text = "\n".join(lines)
        else:
            resp.encoding = resp.apparent_encoding or "utf-8"
            text = resp.text.strip()

        # Truncate to ~8 000 chars (~2 000 tokens) to avoid prompt overflow
        truncated = len(text) > 8000
        text = text[:8000]

        logger.info("fetch_url_content: %s — %d chars (truncated=%s)", url, len(text), truncated)

        return {
            "url": url,
            "content": text,
            "content_length": len(text),
            "truncated": truncated,
        }

    except requests.exceptions.Timeout:
        return {"error": "Request timed out", "url": url, "content": None}
    except Exception as exc:
        logger.warning("fetch_url_content error: %s", exc)
        return {"error": f"Unexpected error: {str(exc)}", "url": url, "content": None}