# Generated by NeuroStack
# Vendored from platform origin: agent/azure_devops_agent (upstream_version=platform)

"""
Azure DevOps Pipeline Agent Package

A specialized agent for Azure DevOps pipeline automation using browser automation
to trigger pipeline runs and monitor their status.
"""

from .agent import azure_devops_agent, root_agent, runner

__all__ = [
    "azure_devops_agent",
    "root_agent",
    "runner"
]

