# Generated by NeuroStack
# Vendored from platform origin: agent/azure_devops_agent (upstream_version=platform)

from __future__ import annotations

from google.adk import Agent
from google.genai import types
from google.adk.tools import load_memory

import importlib.util as _ilu
import pathlib as _pl
_spec_rel_azure_devops = _ilu.spec_from_file_location(
    'azure_devops',
    _pl.Path(__file__).parent / 'azure_devops.py',
)
_mod_rel_azure_devops = _ilu.module_from_spec(_spec_rel_azure_devops)
_spec_rel_azure_devops.loader.exec_module(_mod_rel_azure_devops)
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)

SYSTEM_PROMPT = _mod_rel_prompt.SYSTEM_PROMPT

azure_devops = _mod_rel_azure_devops.create_mcp_server
azure_devops_agent = Agent(
    name="azure_devops_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description="Specialized agent for Azure DevOps pipeline automation - can trigger pipeline runs and check their status using browser automation.",
    instruction=SYSTEM_PROMPT,
    tools=[
        azure_devops(),
        load_memory,
    ],
    generate_content_config=types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = azure_devops_agent
