# Generated by NeuroStack
# Vendored from platform origin: agent/azure_devops_agent (upstream_version=platform)

"""
Server wrapper for Azure DevOps MCP using CustomMCPToolset.
Auto-generated for Azure DevOps agent.
"""

import sys
import os
from pathlib import Path
from google.adk.tools.mcp_tool.mcp_toolset import StdioConnectionParams, MCPToolset
from mcp import StdioServerParameters

try:
    from dotenv import load_dotenv  # optional
    load_dotenv()
except Exception:
    pass

try:
    AGENT_TIMEOUT = int(os.getenv("AGENT_TIMEOUT", "60"))
except Exception:
    AGENT_TIMEOUT = 60

def create_mcp_server() -> MCPToolset:
    """Create and return the MCPToolset for the 'azure_devops' MCP."""
    toolset_script_path = str((Path(__file__).parent / "azure_devops_toolset.py").resolve())
    return MCPToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(
                command=sys.executable,
                args=[toolset_script_path],
            ),
            timeout=AGENT_TIMEOUT,
        )
    )

