# Generated by NeuroStack
# Artifact: agent/test_agent_with_tool_module


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_datetime_tools = _ilu.spec_from_file_location(
    'datetime_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'datetime_tools.py',
)
_mod_tools_datetime_tools = _ilu.module_from_spec(_spec_tools_datetime_tools)
_spec_tools_datetime_tools.loader.exec_module(_mod_tools_datetime_tools)
get_current_time = _mod_tools_datetime_tools.get_current_time





# ============================================================================
# AGENT DEFINITION
# ============================================================================

test_agent_with_tool_module = Agent(
    name="test_agent_with_tool_module",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        get_current_time,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = test_agent_with_tool_module
