# Generated by NeuroStack
# Artifact: agent/weather_agent_to_assist_me


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_weather_fetcher = _ilu.spec_from_file_location(
    'weather_fetcher',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'weather_fetcher.py',
)
_mod_tools_weather_fetcher = _ilu.module_from_spec(_spec_tools_weather_fetcher)
_spec_tools_weather_fetcher.loader.exec_module(_mod_tools_weather_fetcher)
get_weather = _mod_tools_weather_fetcher.get_weather





# ============================================================================
# AGENT DEFINITION
# ============================================================================

weather_agent_to_assist_me = Agent(
    name="weather_agent_to_assist_me",
    model='gemini-2.5-pro',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        get_weather,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = weather_agent_to_assist_me
