# Generated by NeuroStack
# Vendored from platform origin: mcp/notion_server (upstream_version=platform)

"""
Server wrapper for GitHub MCP using MCPToolset.
Auto-generated by API at runtime.
"""

import json
import os
from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset, StdioServerParameters, StdioConnectionParams

try:
    from dotenv import load_dotenv  # optional
    load_dotenv()
except Exception:
    pass

try:
    AGENT_TIMEOUT = int(os.getenv("AGENT_TIMEOUT", "180"))
except Exception:
    AGENT_TIMEOUT = 180


def create_mcp_server() -> MCPToolset:
    """Create and return the MCPToolset for the Firecrawl MCP server."""
    notion_api_key = os.getenv("NOTION_TOKEN")
    if not notion_api_key:
        raise ValueError("NOTION_TOKEN environment variable is not set")

    # Prepare headers for the MCP
    NOTION_MCP_HEADERS = json.dumps({
        "Authorization": f"Bearer {notion_api_key}",
        "Notion-Version": "2022-06-28",
    })

    return MCPToolset(
             connection_params=StdioConnectionParams(
                    server_params=StdioServerParameters(
                        command="npx",
                        args=["@notionhq/notion-mcp-server"],
                        env={"OPENAPI_MCP_HEADERS": NOTION_MCP_HEADERS}
                    ),
                    timeout=AGENT_TIMEOUT,  # Adjust timeout as needed
                )   
            )