# Generated by NeuroStack
# Vendored from platform origin: mcp/puppeter (upstream_version=platform)

"""
Puppeter MCP Server
===================
Open MCP server: Puppeter

Auto-generated on: 2026-07-17 01:34:53

This is an open MCP server (no environment variables or credentials required).
"""

import os
from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset, StdioConnectionParams
from mcp import StdioServerParameters

try:
    AGENT_TIMEOUT = int(os.getenv("AGENT_TIMEOUT", "180"))
except Exception:
    AGENT_TIMEOUT = 180


def create_mcp_server() -> MCPToolset:
    """Create and return the MCPToolset for the 'Puppeter' MCP server."""
    return MCPToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(
                command='npx',
                args=['-y', '@modelcontextprotocol/server-puppeteer'],
            ),
            timeout=AGENT_TIMEOUT,
        ),
    )
