# Generated by NeuroStack
# Artifact: workflow/samle_grpah_wf

"""
Graph-Based Workflow: samle_grpah_wf
Graph-based ADK workflow 'samle_grpah_wf'

Auto-generated by the Graph Workflow Studio.
ADK Docs: https://adk.dev/graphs/routes/
          https://adk.dev/graphs/human-input/
"""
from __future__ import annotations
from dotenv import load_dotenv, find_dotenv
from google.adk import Agent, Workflow, Event, Context
import importlib.util as _ilu
import pathlib as _pl
_spec_agents_containment_agent = _ilu.spec_from_file_location(
    'containment_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'containment_agent' / 'agent.py',
)
_mod_agents_containment_agent = _ilu.module_from_spec(_spec_agents_containment_agent)
_spec_agents_containment_agent.loader.exec_module(_mod_agents_containment_agent)
_spec_agents_decision_triage_agent = _ilu.spec_from_file_location(
    'decision_triage_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'decision_triage_agent' / 'agent.py',
)
_mod_agents_decision_triage_agent = _ilu.module_from_spec(_spec_agents_decision_triage_agent)
_spec_agents_decision_triage_agent.loader.exec_module(_mod_agents_decision_triage_agent)

containment_agent = _mod_agents_containment_agent.root_agent
decision_triage_agent = _mod_agents_decision_triage_agent.root_agent
from pydantic import BaseModel
from typing import Any
import os, re

load_dotenv(find_dotenv())


# ──────────────────────────────────────────────
# Pydantic Schemas
# ──────────────────────────────────────────────
# (No custom schemas)

# ──────────────────────────────────────────────
# Agent Definitions
# ──────────────────────────────────────────────
# (No agent nodes defined)

# ──────────────────────────────────────────────
# Join Nodes — Fan-in for parallel branches
# ──────────────────────────────────────────────
# (No join nodes)

# ──────────────────────────────────────────────
# Function Nodes — Plain Python (no LLM)
# ──────────────────────────────────────────────
# (No function nodes)

# ──────────────────────────────────────────────
# HITL Nodes — yield RequestInput(...) to pause for human input
# ──────────────────────────────────────────────
# (No HITL nodes)

# ──────────────────────────────────────────────
# Router Nodes — return Event(route=KEY) for conditional branching
# ──────────────────────────────────────────────
# (No router nodes)

# ──────────────────────────────────────────────
# Workflow Graph
# ──────────────────────────────────────────────
root_agent = Workflow(
    name="samle_grpah_wf",
    edges=[
        ("START", decision_triage_agent),
        (decision_triage_agent, containment_agent),
    ]
)
