# Generated by NeuroStack
# Artifact: agent/newagenttest


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_get_account_balances = _ilu.spec_from_file_location(
    'get_account_balances',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'get_account_balances.py',
)
_mod_get_account_balances = _ilu.module_from_spec(_spec_get_account_balances)
_spec_get_account_balances.loader.exec_module(_mod_get_account_balances)
get_account_balances = _mod_get_account_balances.get_account_balances





# ============================================================================
# AGENT DEFINITION
# ============================================================================

newagenttest = Agent(
    name="newagenttest",
    model='gemini/gemini-2.5-flash-lite',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        get_account_balances,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = newagenttest
