# Generated by NeuroStack
# Artifact: agent/test_agent


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_sample_mcp_server = _ilu.spec_from_file_location(
    'sample_mcp_server',
    _pl.Path(__file__).parent.parent.parent / 'mcp_servers' / 'internal' / 'sample_mcp_server.py',
)
_mod_sample_mcp_server = _ilu.module_from_spec(_spec_sample_mcp_server)
_spec_sample_mcp_server.loader.exec_module(_mod_sample_mcp_server)
sample_mcp_server = _mod_sample_mcp_server.create_mcp_server
_spec_tools_Account_detail = _ilu.spec_from_file_location(
    'Account_detail',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'Account_detail.py',
)
_mod_tools_Account_detail = _ilu.module_from_spec(_spec_tools_Account_detail)
_spec_tools_Account_detail.loader.exec_module(_mod_tools_Account_detail)
get_account_holder_names = _mod_tools_Account_detail.get_account_holder_names
_spec_tools_datetime_tools = _ilu.spec_from_file_location(
    'datetime_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'datetime_tools.py',
)
_mod_tools_datetime_tools = _ilu.module_from_spec(_spec_tools_datetime_tools)
_spec_tools_datetime_tools.loader.exec_module(_mod_tools_datetime_tools)
get_current_time = _mod_tools_datetime_tools.get_current_time
_spec_tools_pp_calculator_tools = _ilu.spec_from_file_location(
    'pp_calculator_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'pp_calculator_tools.py',
)
_mod_tools_pp_calculator_tools = _ilu.module_from_spec(_spec_tools_pp_calculator_tools)
_spec_tools_pp_calculator_tools.loader.exec_module(_mod_tools_pp_calculator_tools)
add = _mod_tools_pp_calculator_tools.add





# ============================================================================
# AGENT DEFINITION
# ============================================================================

test_agent = Agent(
    name="test_agent",
    model='gemini/gemini-2.5-flash',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        sample_mcp_server(),
        get_account_holder_names,
        get_current_time,
        add,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = test_agent
