# Generated by NeuroStack
# Artifact: agent/sample_agent_to_test_guradrails


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_Account_detail = _ilu.spec_from_file_location(
    'Account_detail',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'Account_detail.py',
)
_mod_tools_Account_detail = _ilu.module_from_spec(_spec_tools_Account_detail)
_spec_tools_Account_detail.loader.exec_module(_mod_tools_Account_detail)
get_account_balances = _mod_tools_Account_detail.get_account_balances
get_account_ids = _mod_tools_Account_detail.get_account_ids
_spec_tools_pp_calculator_tools = _ilu.spec_from_file_location(
    'pp_calculator_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'pp_calculator_tools.py',
)
_mod_tools_pp_calculator_tools = _ilu.module_from_spec(_spec_tools_pp_calculator_tools)
_spec_tools_pp_calculator_tools.loader.exec_module(_mod_tools_pp_calculator_tools)
add = _mod_tools_pp_calculator_tools.add





# ============================================================================
# AGENT DEFINITION
# ============================================================================

sample_agent_to_test_guradrails = Agent(
    name="sample_agent_to_test_guradrails",
    model='gemini/gemini-2.5-flash-lite',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        get_account_balances,
        get_account_ids,
        add,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = sample_agent_to_test_guradrails
