# Generated by NeuroStack
# Artifact: agent/sample_agent_to_test_guradrails

"""
System prompt for sample_agent_to_test_guradrails.
"""

AGENT_DESCRIPTION = """
test guardrails
"""

SYSTEM_PROMPT = """
test instr
"""
