# Generated by NeuroStack
# Vendored from platform origin: mcp/documentation (upstream_version=platform)

"""
FastMCP Server for documentation exposing selected tools.
Auto-generated by API at runtime.
"""

import sys
from pathlib import Path
from mcp.server.fastmcp import FastMCP
from typing import Dict, Any, List


mcp = FastMCP("documentation")


import importlib.util as _ilu
import pathlib as _pl
_spec_tools_documentation_tools = _ilu.spec_from_file_location(
    'documentation_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'documentation_tools.py',
)
_mod_tools_documentation_tools = _ilu.module_from_spec(_spec_tools_documentation_tools)
_spec_tools_documentation_tools.loader.exec_module(_mod_tools_documentation_tools)

@mcp.tool()
async def generate_api_documentation(project_path: str, language: str = "auto", output_format: str = "markdown") -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `generate_api_documentation`.
    Calls the underlying function defined in `modular_agents.tools.documentation_tools`.
    """
    tool_generate_api_documentation = _mod_tools_documentation_tools.generate_api_documentation
    return tool_generate_api_documentation(project_path, language, output_format)


@mcp.tool()
async def generate_docstrings(file_path: str, language: str = "auto", style: str = "google") -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `generate_docstrings`.
    Calls the underlying function defined in `modular_agents.tools.documentation_tools`.
    """
    tool_generate_docstrings = _mod_tools_documentation_tools.generate_docstrings
    return tool_generate_docstrings(file_path, language, style)


@mcp.tool()
async def generate_readme(project_path: str, template: str = "standard", include_badges: bool = True) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `generate_readme`.
    Calls the underlying function defined in `modular_agents.tools.documentation_tools`.
    """
    tool_generate_readme = _mod_tools_documentation_tools.generate_readme
    return tool_generate_readme(project_path, template, include_badges)


@mcp.tool()
async def validate_documentation(project_path: str, language: str = "auto", check_coverage: bool = True) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `validate_documentation`.
    Calls the underlying function defined in `modular_agents.tools.documentation_tools`.
    """
    tool_validate_documentation = _mod_tools_documentation_tools.validate_documentation
    return tool_validate_documentation(project_path, language, check_coverage)


@mcp.tool()
async def update_documentation(project_path: str, target_files: List[str] = [], auto_sync: bool = True) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `update_documentation`.
    Calls the underlying function defined in `modular_agents.tools.documentation_tools`.
    """
    tool_update_documentation = _mod_tools_documentation_tools.update_documentation
    return tool_update_documentation(project_path, target_files, auto_sync)


if __name__ == "__main__":
    mcp.run(transport="stdio")
