# Generated by NeuroStack
# Vendored from platform origin: mcp/documentation (upstream_version=platform)

"""
Server wrapper for documentation MCP using CustomMCPToolset.
Auto-generated by API at runtime.
"""

import sys
import os
from pathlib import Path
from google.adk.tools.mcp_tool.mcp_toolset import StdioConnectionParams, MCPToolset
from mcp import StdioServerParameters

try:
    from dotenv import load_dotenv  # optional
    load_dotenv()
except Exception:
    pass

try:
    AGENT_TIMEOUT = int(os.getenv("AGENT_TIMEOUT", "240"))  # Timeout for documentation operations
except Exception:
    AGENT_TIMEOUT = 240

def create_mcp_server() -> MCPToolset:
    """Create and return the MCPToolset for the 'documentation' MCP."""
    toolset_script_path = str((Path(__file__).parent / "documentation_toolset.py").resolve())
    return MCPToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(
                command=sys.executable,
                args=[toolset_script_path],
            ),
            timeout=AGENT_TIMEOUT,
        )
    )
