# Generated by NeuroStack
# Artifact: mcp/multi_function_tools_mcp.py

"""
FastMCP Server for multi_function_tools_mcp exposing selected tools.
Auto-generated by API at runtime.
"""

from mcp.server.fastmcp import FastMCP
from typing import Any, Dict, List, Optional

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_Account_detail = _ilu.spec_from_file_location(
    'Account_detail',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'Account_detail.py',
)
_mod_tools_Account_detail = _ilu.module_from_spec(_spec_tools_Account_detail)
_spec_tools_Account_detail.loader.exec_module(_mod_tools_Account_detail)
_spec_tools_datetime_tools = _ilu.spec_from_file_location(
    'datetime_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'datetime_tools.py',
)
_mod_tools_datetime_tools = _ilu.module_from_spec(_spec_tools_datetime_tools)
_spec_tools_datetime_tools.loader.exec_module(_mod_tools_datetime_tools)
_spec_tools_pp_calculator_tools = _ilu.spec_from_file_location(
    'pp_calculator_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'pp_calculator_tools.py',
)
_mod_tools_pp_calculator_tools = _ilu.module_from_spec(_spec_tools_pp_calculator_tools)
_spec_tools_pp_calculator_tools.loader.exec_module(_mod_tools_pp_calculator_tools)

tool_add = _mod_tools_pp_calculator_tools.add
tool_get_account_balances = _mod_tools_Account_detail.get_account_balances
tool_get_current_date = _mod_tools_datetime_tools.get_current_date

mcp = FastMCP("multi_function_tools_mcp")


@mcp.tool()
async def add(num1: float, num2: float) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `add`.
    Calls the `add` tool from the `pp_calculator_tools` tool module.
    """
    return tool_add(num1=num1, num2=num2)


@mcp.tool()
async def get_account_balances(account_holder_name: str | None = None) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `get_account_balances`.
    Calls the `get_account_balances` tool from the `Account_detail` tool module.
    """
    return tool_get_account_balances(account_holder_name=account_holder_name)


@mcp.tool()
async def get_current_date() -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `get_current_date`.
    Calls the `get_current_date` tool from the `datetime_tools` tool module.
    """
    return tool_get_current_date()


if __name__ == "__main__":
    mcp.run(transport="stdio")
