# Generated by NeuroStack
# Artifact: mcp/new_server.py

"""
FastMCP Server for new_server exposing selected tools.
Auto-generated by API at runtime.
"""

from mcp.server.fastmcp import FastMCP
from typing import Any, Dict, List, Optional

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_deployed_ps_25 = _ilu.spec_from_file_location(
    'deployed_ps_25',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'deployed_ps_25.py',
)
_mod_tools_deployed_ps_25 = _ilu.module_from_spec(_spec_tools_deployed_ps_25)
_spec_tools_deployed_ps_25.loader.exec_module(_mod_tools_deployed_ps_25)
_spec_tools_global_tools = _ilu.spec_from_file_location(
    'global_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'global_tools.py',
)
_mod_tools_global_tools = _ilu.module_from_spec(_spec_tools_global_tools)
_spec_tools_global_tools.loader.exec_module(_mod_tools_global_tools)
_spec_tools_log_normalization_tools = _ilu.spec_from_file_location(
    'log_normalization_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'log_normalization_tools.py',
)
_mod_tools_log_normalization_tools = _ilu.module_from_spec(_spec_tools_log_normalization_tools)
_spec_tools_log_normalization_tools.loader.exec_module(_mod_tools_log_normalization_tools)
_spec_tools_threat_hunting_baseline_tools = _ilu.spec_from_file_location(
    'threat_hunting_baseline_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'threat_hunting_baseline_tools.py',
)
_mod_tools_threat_hunting_baseline_tools = _ilu.module_from_spec(_spec_tools_threat_hunting_baseline_tools)
_spec_tools_threat_hunting_baseline_tools.loader.exec_module(_mod_tools_threat_hunting_baseline_tools)
_spec_tools_weather_tools = _ilu.spec_from_file_location(
    'weather_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'weather_tools.py',
)
_mod_tools_weather_tools = _ilu.module_from_spec(_spec_tools_weather_tools)
_spec_tools_weather_tools.loader.exec_module(_mod_tools_weather_tools)

tool_get_current_weather = _mod_tools_weather_tools.get_current_weather
tool_normalize_timestamp = _mod_tools_log_normalization_tools.normalize_timestamp
tool_fetch_relevant_context = _mod_tools_global_tools.fetch_relevant_context
tool_compute_baseline_features = _mod_tools_threat_hunting_baseline_tools.compute_baseline_features
tool_get_forecast = _mod_tools_deployed_ps_25.get_forecast

mcp = FastMCP("new_server")


@mcp.tool()
async def get_current_weather(city: str, country_code: Optional = None, units: str = 'metric') -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `get_current_weather`.
    Calls the `get_current_weather` tool from the `weather_tools` tool module.
    """
    return tool_get_current_weather(city=city, country_code=country_code, units=units)


@mcp.tool()
async def normalize_timestamp(ts_value: Union, default_tz: str = 'UTC') -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `normalize_timestamp`.
    Calls the `normalize_timestamp` tool from the `log_normalization_tools` tool module.
    """
    return tool_normalize_timestamp(ts_value=ts_value, default_tz=default_tz)


@mcp.tool()
async def fetch_relevant_context(goal: str, tool_context: google.adk.agents.context.Context | None = None) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `fetch_relevant_context`.
    Calls the `fetch_relevant_context` tool from the `global_tools` tool module.
    """
    return tool_fetch_relevant_context(goal=goal, tool_context=tool_context)


@mcp.tool()
async def compute_baseline_features(entity_username: str, history_start_ts: str, history_end_ts: str, dataset_root: str = 'data/threat_hunting_demo') -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `compute_baseline_features`.
    Calls the `compute_baseline_features` tool from the `threat_hunting_baseline_tools` tool module.
    """
    return tool_compute_baseline_features(entity_username=entity_username, history_start_ts=history_start_ts, history_end_ts=history_end_ts, dataset_root=dataset_root)


@mcp.tool()
async def get_forecast(location: str, days: int = 3, timeout_seconds: float = 20.0) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `get_forecast`.
    Calls the `get_forecast` tool from the `deployed_ps_25` tool module.
    """
    return tool_get_forecast(location=location, days=days, timeout_seconds=timeout_seconds)


if __name__ == "__main__":
    mcp.run(transport="stdio")
