# Generated by NeuroStack
# Artifact: mcp/new_sample_mcp_server.py

"""
FastMCP Server for new_sample_mcp_server exposing selected tools.
Auto-generated by API at runtime.
"""

import sys
from pathlib import Path
from mcp.server.fastmcp import FastMCP
from typing import Any, Dict, List, Optional

repo_root = None
for parent in Path(__file__).resolve().parents:
    if (parent / "modular_agents").is_dir():
        repo_root = parent
        break
if repo_root and str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

# Load environment variables from project .env so tool credentials are available
try:
    from dotenv import load_dotenv as _load_dotenv
    for _env_candidate in (repo_root / "env.dev", repo_root / ".env") if repo_root else []:
        if _env_candidate.exists():
            _load_dotenv(dotenv_path=_env_candidate, override=False)
except Exception:
    pass

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_classify_ticket_tools = _ilu.spec_from_file_location(
    'classify_ticket_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'classify_ticket_tools.py',
)
_mod_tools_classify_ticket_tools = _ilu.module_from_spec(_spec_tools_classify_ticket_tools)
_spec_tools_classify_ticket_tools.loader.exec_module(_mod_tools_classify_ticket_tools)
_spec_tools_compression_tools = _ilu.spec_from_file_location(
    'compression_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'compression_tools.py',
)
_mod_tools_compression_tools = _ilu.module_from_spec(_spec_tools_compression_tools)
_spec_tools_compression_tools.loader.exec_module(_mod_tools_compression_tools)
_spec_tools_local_filesystem_tools = _ilu.spec_from_file_location(
    'local_filesystem_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'local_filesystem_tools.py',
)
_mod_tools_local_filesystem_tools = _ilu.module_from_spec(_spec_tools_local_filesystem_tools)
_spec_tools_local_filesystem_tools.loader.exec_module(_mod_tools_local_filesystem_tools)
_spec_tools_log_normalization_tools = _ilu.spec_from_file_location(
    'log_normalization_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'log_normalization_tools.py',
)
_mod_tools_log_normalization_tools = _ilu.module_from_spec(_spec_tools_log_normalization_tools)
_spec_tools_log_normalization_tools.loader.exec_module(_mod_tools_log_normalization_tools)
_spec_tools_threat_hunting_data_tools = _ilu.spec_from_file_location(
    'threat_hunting_data_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'threat_hunting_data_tools.py',
)
_mod_tools_threat_hunting_data_tools = _ilu.module_from_spec(_spec_tools_threat_hunting_data_tools)
_spec_tools_threat_hunting_data_tools.loader.exec_module(_mod_tools_threat_hunting_data_tools)
_spec_tools_vulnerability_remediation_tools = _ilu.spec_from_file_location(
    'vulnerability_remediation_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'vulnerability_remediation_tools.py',
)
_mod_tools_vulnerability_remediation_tools = _ilu.module_from_spec(_spec_tools_vulnerability_remediation_tools)
_spec_tools_vulnerability_remediation_tools.loader.exec_module(_mod_tools_vulnerability_remediation_tools)

tool_fix_code_vulnerabilities = _mod_tools_vulnerability_remediation_tools.fix_code_vulnerabilities
tool_generate_security_patches = _mod_tools_vulnerability_remediation_tools.generate_security_patches
tool_zip_file = _mod_tools_compression_tools.zip_file
tool_generate_threat_hunting_demo_dataset = _mod_tools_threat_hunting_data_tools.generate_threat_hunting_demo_dataset
tool_classify_ticket = _mod_tools_classify_ticket_tools.classify_ticket
tool_handle_schema_drift = _mod_tools_log_normalization_tools.handle_schema_drift
tool_normalize_timestamp = _mod_tools_log_normalization_tools.normalize_timestamp
tool_read_text_file = _mod_tools_local_filesystem_tools.read_text_file

mcp = FastMCP("new_sample_mcp_server")


@mcp.tool()
async def fix_code_vulnerabilities(file_path: str, vulnerabilities: List, backup: bool = True) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `fix_code_vulnerabilities`.
    Calls the underlying function defined in `modular_agents.tools.vulnerability_remediation_tools`.
    """
    return tool_fix_code_vulnerabilities(file_path=file_path, vulnerabilities=vulnerabilities, backup=backup)


@mcp.tool()
async def generate_security_patches(project_path: str, fixes_data: List, create_branch: bool = True) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `generate_security_patches`.
    Calls the underlying function defined in `modular_agents.tools.vulnerability_remediation_tools`.
    """
    return tool_generate_security_patches(project_path=project_path, fixes_data=fixes_data, create_branch=create_branch)


@mcp.tool()
async def zip_file(source_path: str, destination_path: str) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `zip_file`.
    Calls the underlying function defined in `modular_agents.tools.compression_tools`.
    """
    return tool_zip_file(source_path=source_path, destination_path=destination_path)


@mcp.tool()
async def generate_threat_hunting_demo_dataset(dataset_root: str = 'data/threat_hunting_demo', seed: int = 1337, end_ts: Optional[str] = None, days_history: int = 13) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `generate_threat_hunting_demo_dataset`.
    Calls the underlying function defined in `modular_agents.tools.threat_hunting_data_tools`.
    """
    return tool_generate_threat_hunting_demo_dataset(dataset_root=dataset_root, seed=seed, end_ts=end_ts, days_history=days_history)


@mcp.tool()
async def classify_ticket(text: str) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `classify_ticket`.
    Calls the underlying function defined in `modular_agents.tools.classify_ticket_tools`.
    """
    return tool_classify_ticket(text=text)


@mcp.tool()
async def handle_schema_drift(event: Dict, drift_policy: Optional = None) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `handle_schema_drift`.
    Calls the underlying function defined in `modular_agents.tools.log_normalization_tools`.
    """
    return tool_handle_schema_drift(event=event, drift_policy=drift_policy)


@mcp.tool()
async def normalize_timestamp(ts_value: Union, default_tz: str = 'UTC') -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `normalize_timestamp`.
    Calls the underlying function defined in `modular_agents.tools.log_normalization_tools`.
    """
    return tool_normalize_timestamp(ts_value=ts_value, default_tz=default_tz)


@mcp.tool()
async def read_text_file(relative_path: str) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `read_text_file`.
    Calls the underlying function defined in `modular_agents.tools.local_filesystem_tools`.
    """
    return tool_read_text_file(relative_path=relative_path)


if __name__ == "__main__":
    mcp.run(transport="stdio")
