# Generated by NeuroStack
# Vendored from platform origin: mcp/sample_mcp_server (upstream_version=platform)

"""
FastMCP Server for sample_mcp_server exposing selected tools.
Auto-generated by API at runtime.
"""


def _load_platform_tool(module_stem, name):
    import importlib.util
    import pathlib
    import sys

    key = f"_vendored_tool_{module_stem}"
    module = sys.modules.get(key)
    if module is None:
        spec = importlib.util.spec_from_file_location(
            key, pathlib.Path(__file__).resolve().parents[2] / "tools" / f"{module_stem}.py"
        )
        module = importlib.util.module_from_spec(spec)
        sys.modules[key] = module
        try:
            spec.loader.exec_module(module)
        except Exception:
            sys.modules.pop(key, None)
            raise
    return getattr(module, name)


import sys
from pathlib import Path
from mcp.server.fastmcp import FastMCP
from typing import Any, Dict, List, Optional

repo_root = None
for parent in Path(__file__).resolve().parents:
    if (parent / "modular_agents").is_dir():
        repo_root = parent
        break
if repo_root and str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

# Load environment variables from project .env so tool credentials are available
try:
    from dotenv import load_dotenv as _load_dotenv
    for _env_candidate in (repo_root / "env.dev", repo_root / ".env") if repo_root else []:
        if _env_candidate.exists():
            _load_dotenv(dotenv_path=_env_candidate, override=False)
except Exception:
    pass

tool_block_ip = _load_platform_tool('containment_tools', 'block_ip')
tool_load_threat_hunting_dataset = _load_platform_tool('threat_hunting_data_tools', 'load_threat_hunting_dataset')
tool_get_crypto_price = _load_platform_tool('cryptocurrency_tools', 'get_crypto_price')
tool_get_current_date = _load_platform_tool('datetime_tools', 'get_current_date')
tool_fetch_data_from_table = _load_platform_tool('database_tools', 'fetch_data_from_table')
tool_update_jira_ticket = _load_platform_tool('jira_tools', 'update_jira_ticket')
tool_add_integers = _load_platform_tool('ppp_calculator_tools', 'add_integers')

mcp = FastMCP("sample_mcp_server")


@mcp.tool()
async def block_ip(ip_address: str) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `block_ip`.
    Calls the underlying function defined in `modular_agents.tools.containment_tools`.
    """
    return tool_block_ip(ip_address=ip_address)


@mcp.tool()
async def load_threat_hunting_dataset(dataset_root: str = 'data/threat_hunting_demo') -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `load_threat_hunting_dataset`.
    Calls the underlying function defined in `modular_agents.tools.threat_hunting_data_tools`.
    """
    return tool_load_threat_hunting_dataset(dataset_root=dataset_root)


@mcp.tool()
async def get_crypto_price(symbol: str) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `get_crypto_price`.
    Calls the underlying function defined in `modular_agents.tools.cryptocurrency_tools`.
    """
    return tool_get_crypto_price(symbol=symbol)


@mcp.tool()
async def get_current_date() -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `get_current_date`.
    Calls the underlying function defined in `modular_agents.tools.datetime_tools`.
    """
    return tool_get_current_date()


@mcp.tool()
async def fetch_data_from_table(db_path: str, table_name: str) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `fetch_data_from_table`.
    Calls the underlying function defined in `modular_agents.tools.database_tools`.
    """
    return tool_fetch_data_from_table(db_path=db_path, table_name=table_name)


@mcp.tool()
async def update_jira_ticket(ticket_id: str, status: str, resolution_note: str, draft_response: str = '', tool_context: google.adk.agents.context.Context | None = None) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `update_jira_ticket`.
    Calls the underlying function defined in `modular_agents.tools.jira_tools`.
    """
    return tool_update_jira_ticket(ticket_id=ticket_id, status=status, resolution_note=resolution_note, draft_response=draft_response, tool_context=tool_context)


@mcp.tool()
async def add_integers(num1: int, num2: int) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `add_integers`.
    Calls the underlying function defined in `modular_agents.tools.ppp_calculator_tools`.
    """
    return tool_add_integers(num1=num1, num2=num2)


if __name__ == "__main__":
    mcp.run(transport="stdio")
