# Generated by NeuroStack
# Vendored from platform origin: agent/code_review_agent_v2 (upstream_version=platform)

"""Code Review Agent - Analyzes code against compliance templates."""
from .agent import root_agent