# Generated by NeuroStack
# Vendored from platform origin: agent/code_review_agent_v2 (upstream_version=platform)

"""
Code Review Agent — Enterprise-grade MR/PR review for any SDLC pipeline.

Works in two modes:
  1. Standalone  — given a GitHub PR URL or GitLab MR IID directly.
  2. Pipeline    — reads upstream context (generated_code / mr snapshot)
                   from session state via fetch_relevant_context.

Outputs a strict JSON payload of inline review comments that:
  - The CodeGenerationAgent can consume on the next iteration to fix issues.
  - Can be optionally posted back as inline comments on the MR/PR.
"""

from __future__ import annotations

import logging
import os
import pathlib
import sys

_project_root = str(pathlib.Path(__file__).resolve().parents[3])
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())

from google.adk.agents import Agent
from google.adk.tools import FunctionTool, load_memory
from google.adk.skills import load_skill_from_dir
from google.adk.tools import skill_toolset
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)
_spec_rel_tools = _ilu.spec_from_file_location(
    'tools',
    _pl.Path(__file__).parent / 'tools.py',
)
_mod_rel_tools = _ilu.module_from_spec(_spec_rel_tools)
_spec_rel_tools.loader.exec_module(_mod_rel_tools)
_spec_tools_global_tools = _ilu.spec_from_file_location(
    'global_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'global_tools.py',
)
_mod_tools_global_tools = _ilu.module_from_spec(_spec_tools_global_tools)
_spec_tools_global_tools.loader.exec_module(_mod_tools_global_tools)

fetch_relevant_context_tool = _mod_tools_global_tools.fetch_relevant_context_tool
UNIVERSAL_CONTEXT_INSTRUCTION = _mod_tools_global_tools.UNIVERSAL_CONTEXT_INSTRUCTION
from core.logging.config import add_file_handler_to_logger
from modular_agents.core.llm import get_llm_backend_name, get_llm_model_name

AGENT_INSTRUCTION = _mod_rel_prompt.AGENT_INSTRUCTION
AGENT_DESCRIPTION = _mod_rel_prompt.AGENT_DESCRIPTION
fetch_pr_diff = _mod_rel_tools.fetch_pr_diff
post_github_review_comments = _mod_rel_tools.post_github_review_comments
from modular_agents.agents.sdlc_agents.mcp_utils import sanitize_tool_descriptions_callback

logger = logging.getLogger(__name__)
add_file_handler_to_logger(logger)
logger.info("Initializing CodeReviewAgent")

# ── LLM config ─────────────────────────────────────────────────────────────
max_output_tokens = 8192

logger.info(
    "LLM config: model=%s backend=%s max_tokens=%s",
    get_llm_model_name(),
    get_llm_backend_name(),
    max_output_tokens,
)

# ── Skills ──────────────────────────────────────────────────────────────────
_skills_dir = pathlib.Path(__file__).parent / "skills"

def _load_skill(name: str):
    p = _skills_dir / name
    if not p.exists():
        logger.warning("Skill not found, skipping: %s", p)
        return None
    try:
        s = load_skill_from_dir(p)
        logger.info("Loaded skill: %s", name)
        return s
    except Exception as exc:
        logger.warning("Failed to load skill '%s': %s", name, exc)
        return None

_all_skills = [
    _load_skill("review-java-springboot"),
    _load_skill("review-dotnet-aspnet"),
    _load_skill("review-python-flask"),
    _load_skill("review-node-express"),
    _load_skill("review-php-laravel"),
    _load_skill("review-frontend-vanilla"),
]
_loaded_skills = [s for s in _all_skills if s is not None]
logger.info("Review skills loaded: %d / %d", len(_loaded_skills), len(_all_skills))

review_skillset = skill_toolset.SkillToolset(skills=_loaded_skills)

# ── Tools ───────────────────────────────────────────────────────────────────
fetch_pr_diff_tool = FunctionTool(fetch_pr_diff)
post_github_comments_tool = FunctionTool(post_github_review_comments)

tools_list = [
    load_memory,
    review_skillset,
    fetch_relevant_context_tool,
    fetch_pr_diff_tool,
    post_github_comments_tool,
]

# ── Callbacks ───────────────────────────────────────────────────────────────
from modular_agents.core.agent_instrumentation import make_instrumented_callbacks
from modular_agents.agents.sdlc_agents.context_projection import truncate_context_in_request

_system_name = get_llm_backend_name()
_callbacks = make_instrumented_callbacks("code_review_agent", system_name=_system_name)

def chained_before_model_callback(callback_context, llm_request):
    try:
        truncate_context_in_request(llm_request, agent_name="code_review_agent")
    except Exception as exc:
        logger.warning("Context truncation failed: %s", exc)
    sanitize_tool_descriptions_callback(callback_context, llm_request)
    _callbacks["before_model"](callback_context, llm_request)

def chained_before_tool_callback(tool, args, tool_context):
    return _callbacks["before_tool"](tool, args, tool_context)

# ── Agent ───────────────────────────────────────────────────────────────────
code_review_agent = Agent(
    name="code_review_agent_v2",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=UNIVERSAL_CONTEXT_INSTRUCTION + "\n\n" + AGENT_INSTRUCTION,
    tools=tools_list,
    output_key="code_review_output",
    generate_content_config=types.GenerateContentConfig(
        response_mime_type="application/json",
        temperature=0.1,          # Low temp → deterministic, consistent review
        max_output_tokens=max_output_tokens,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ],
    ),
)

logger.info("CodeReviewAgent created successfully")
root_agent = code_review_agent


logger.info("CodeReviewAgent runner initialized")
