# Generated by NeuroStack
# Vendored from platform origin: agent/code_review_agent_v2 (upstream_version=platform)

"""
Tools for CodeReviewAgent.

Four tools:
  fetch_pr_diff          — GitHub: fetch changed files + patches from a PR
  post_github_review_comments — post inline review comments on a GitHub PR

Fetcher returns a normalised structure. Poster handles github API quirks and is
best-effort (failures are non-fatal).
"""

from __future__ import annotations

import base64
import logging
import os
import re
import time
from typing import Any, Dict, List, Optional, Tuple

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

from google.adk.tools import ToolContext

try:
    from dotenv import load_dotenv, find_dotenv
    load_dotenv(find_dotenv())
except Exception:
    pass

logger = logging.getLogger(__name__)

# ── Shared retry session ────────────────────────────────────────────────────
_session = requests.Session()
_session.mount(
    "https://",
    HTTPAdapter(
        max_retries=Retry(
            total=4,
            backoff_factor=1,
            status_forcelist=[429, 500, 502, 503, 504],
            allowed_methods=["HEAD", "GET", "POST", "PUT", "DELETE", "PATCH"],
        )
    ),
)

# ── Max diff bytes per file — keeps context window lean ────────────────────
_MAX_DIFF_BYTES = 24_000   # ~6k tokens per file; agent sees diffs, not full files

# ─────────────────────────────────────────────────────────────────────────────
# Token resolvers
# ─────────────────────────────────────────────────────────────────────────────

def _github_token() -> Optional[str]:
    return (
        os.getenv("GITHUB_TOKEN")
        or os.getenv("GITHUB_PERSONAL_ACCESS_TOKEN")
        or os.getenv("GH_TOKEN")
    )

def _github_headers() -> Dict[str, str]:
    h = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "Neurostack-CodeReview/1.0",
    }
    tok = _github_token()
    if tok:
        h["Authorization"] = f"Bearer {tok}"
    return h


def _github_get(url: str, headers: Dict[str, str], **kwargs) -> requests.Response:
    """GET with GitHub 403 rate-limit detection and automatic backoff."""
    resp = _session.get(url, headers=headers, **kwargs)
    if resp.status_code == 403:
        remaining = resp.headers.get("X-RateLimit-Remaining", "1")
        reset_at = int(resp.headers.get("X-RateLimit-Reset", int(time.time()) + 60))
        if remaining == "0":
            sleep_for = max(reset_at - int(time.time()) + 2, 5)
            logger.warning("GitHub rate limit hit, sleeping %ds before retry", sleep_for)
            time.sleep(sleep_for)
            return _session.get(url, headers=headers, **kwargs)
    return resp


# ─────────────────────────────────────────────────────────────────────────────
# Diff helpers
# ─────────────────────────────────────────────────────────────────────────────

def _truncate_diff(diff: str, max_bytes: int = _MAX_DIFF_BYTES) -> Tuple[str, bool]:
    """Truncate a diff to max_bytes. Returns (diff_text, was_truncated)."""
    encoded = diff.encode("utf-8", errors="replace")
    if len(encoded) <= max_bytes:
        return diff, False
    truncated = encoded[:max_bytes].decode("utf-8", errors="replace")
    return truncated + "\n... [diff truncated — remaining content not shown]", True


def _parse_line_number_from_diff(diff: str) -> int:
    """
    Extract the starting line number of the first added hunk in a diff string.
    Falls back to 1 if parsing fails.

    Note: target_hunk_line parameter removed (Bug 7 fix) — it was declared but
    never used; the function always returned the first hunk's start line.
    """
    for line in diff.splitlines():
        m = re.match(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@", line)
        if m:
            return int(m.group(1))
    return 1



def _diff_position(
    patch: str,
    target_line: int,
) -> Optional[int]:
    """
    Convert an absolute new-file line number to GitHub's legacy
    diff-relative position.

    The first diff-content line after the first @@ hunk header has
    position 1. Position counting continues across later hunks.

    Args:
        patch:
            Unified diff patch for one file.

        target_line:
            Absolute line number on the new/right side of the file.

    Returns:
        The 1-based diff position, or None when the new-file line is
        not represented in the patch.
    """
    if not patch or target_line <= 0:
        return None

    position = 0
    current_new_line: Optional[int] = None
    inside_hunk = False

    for line in patch.splitlines():
        if line.startswith("@@"):
            match = re.match(
                r"^@@ -\d+(?:,\d+)? "
                r"\+(\d+)(?:,\d+)? @@",
                line,
            )

            if not match:
                continue

            current_new_line = int(match.group(1))
            inside_hunk = True

            # Do not count the first hunk header. GitHub position 1 is
            # the first content line immediately below that header.
            #
            # Subsequent hunk headers are part of the diff-offset
            # sequence, so count them after position tracking started.
            if position > 0:
                position += 1

            continue

        if not inside_hunk or current_new_line is None:
            continue

        # Every row represented in the patch advances the legacy
        # diff-relative position.
        position += 1

        if line.startswith("\\"):
            # Metadata such as:
            # "\ No newline at end of file"
            #
            # It occupies a diff row but not a new-file line.
            continue

        if line.startswith("-"):
            # Deleted lines exist only on the old/left side.
            # They advance diff position, but not the new-file line.
            continue

        if line.startswith("+"):
            # Added line on the new/right side.
            if current_new_line == target_line:
                return position

            current_new_line += 1
            continue

        # Context line exists on both old and new sides.
        if current_new_line == target_line:
            return position

        current_new_line += 1

    return None

# ─────────────────────────────────────────────────────────────────────────────
# TOOL 1 — GitHub PR diff fetcher
# ─────────────────────────────────────────────────────────────────────────────

def fetch_pr_diff(
    owner: str,
    repo: str,
    pr_number: int,
    tool_context: "ToolContext | None" = None,
) -> Dict[str, Any]:
    """
    Fetch the file-level diffs for a GitHub Pull Request.

    Uses the GitHub Pulls API (files endpoint) which returns per-file patches.
    Handles pagination for PRs with >30 changed files.

    Args:
        owner:     Repository owner (user or org)
        repo:      Repository name
        pr_number: Pull request number

    Returns:
        {
          "platform": "github",
          "owner": str,
          "repo": str,
          "pr_number": int,
          "title": str,
          "head_branch": str,
          "base_branch": str,
          "web_url": str,
          "total_files": int,
          "head_sha": str,    // needed for posting review comments
          "changes": [
            {
              "file_path": str,
              "old_file_path": str,
              "status": "added|modified|deleted|renamed",
              "diff": str,
              "diff_truncated": bool,
              "first_added_line": int,
              "additions": int,
              "deletions": int
            }
          ],
          "error": null | str
        }
    """
    base = "https://api.github.com"
    headers = _github_headers()

    # ── PR metadata ────────────────────────────────────────────────────────
    try:
        meta_resp = _session.get(
            f"{base}/repos/{owner}/{repo}/pulls/{pr_number}",
            headers=headers, timeout=15,
        )
        if meta_resp.status_code == 404:
            return {"error": f"PR #{pr_number} not found in {owner}/{repo}", "changes": []}
        if meta_resp.status_code != 200:
            return {"error": f"GitHub API {meta_resp.status_code}", "changes": []}
        meta = meta_resp.json()
    except Exception as exc:
        return {"error": f"PR metadata fetch failed: {exc}", "changes": []}

    head_sha = meta.get("head", {}).get("sha", "")

    # ── Files + patches (paginated) ────────────────────────────────────────
    all_files: List[Dict] = []
    page = 1
    while True:
        try:
            files_resp = _github_get(
                f"{base}/repos/{owner}/{repo}/pulls/{pr_number}/files",
                headers=headers,
                params={"per_page": 100, "page": page},
                timeout=30,
            )
            if files_resp.status_code != 200:
                break
            batch = files_resp.json()
            if not batch:
                break
            all_files.extend(batch)
            if len(batch) < 100:
                break
            page += 1
        except Exception:
            break

    # ── Normalise ──────────────────────────────────────────────────────────
    normalised = []
    for f in all_files:
        raw_patch = f.get("patch", "")
        diff_text, truncated = _truncate_diff(raw_patch)

        # GitHub uses "status" field: added, modified, deleted, renamed, copied, changed, unchanged
        gh_status = f.get("status", "modified")
        status = gh_status if gh_status in ("added", "deleted", "renamed") else "modified"

        normalised.append({
            "file_path": f.get("filename", ""),
            "old_file_path": f.get("previous_filename") or f.get("filename", ""),
            "status": status,
            "diff": diff_text,
            "diff_truncated": truncated,
            "first_added_line": _parse_line_number_from_diff(raw_patch),
            "additions": f.get("additions", 0),
            "deletions": f.get("deletions", 0),
        })

    logger.info(
        "fetch_pr_diff: %s/%s PR#%d files=%d",
        owner, repo, pr_number, len(normalised),
    )
    return {
        "platform": "github",
        "owner": owner,
        "repo": repo,
        "pr_number": pr_number,
        "title": meta.get("title", ""),
        "description": meta.get("body", ""),
        "head_branch": meta.get("head", {}).get("ref", ""),
        "base_branch": meta.get("base", {}).get("ref", ""),
        "web_url": meta.get("html_url", ""),
        "author": (meta.get("user") or {}).get("login", ""),
        "head_sha": head_sha,
        "total_files": len(normalised),
        "truncated_at_api_limit": len(all_files) >= 3000,  # GitHub hard-caps at 3000 files
        "changes": normalised,
        "error": None,
    }


# ─────────────────────────────────────────────────────────────────────────────
# TOOL 2 — GitHub inline review comment poster
# ─────────────────────────────────────────────────────────────────────────────

from typing import Any, Dict, List, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveInt,
    validate_call,
)


class FileData(BaseModel):
    """A changed file and its unified diff."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    file_path: str = Field(min_length=1)
    diff: str


class Comment(BaseModel):
    """A validated inline code-review comment."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    id: str = ""
    severity: Literal[
        "critical",
        "major",
        "minor",
        "suggestion",
    ] = "minor"
    category: str = ""
    title: str = "Code Review Comment"
    body: str = ""
    suggestion: str = ""
    file_path: str = Field(min_length=1)
    line_number: PositiveInt = 1
    rule_ref: str = ""


@validate_call(
    config=ConfigDict(arbitrary_types_allowed=True)
)
def post_github_review_comments(
    owner: str,
    repo: str,
    pr_number: PositiveInt,
    comments: list[Comment],
    commit_sha: str = "",
    files_data: list[FileData] | None = None,
    tool_context: ToolContext | None = None,
) -> Dict[str, Any]:
    """
    Post a GitHub Pull Request Review with inline comments.

    Uses the GitHub Reviews API:
    POST /repos/:owner/:repo/pulls/:number/reviews

    Args:
        owner:
            Repository owner.

        repo:
            Repository name.

        pr_number:
            Pull request number.

        comments:
            Validated list of code-review comments.

        commit_sha:
            HEAD commit SHA of the PR.

        files_data:
            Optional validated list of changed files and their diffs.

        tool_context:
            Optional surrounding tool context.

    Returns:
        {
            "review_id": int | None,
            "review_url": str | None,
            "posted": int,
            "errors": list[str],
        }
    """
    token = _github_token()
    if not token:
        return {
            "review_id": None,
            "review_url": None,
            "posted": 0,
            "errors": ["GITHUB_TOKEN not set"],
        }

    headers = _github_headers()
    base = "https://api.github.com"

    # If commit_sha was not passed, fetch it.
    if not commit_sha:
        try:
            response = _session.get(
                f"{base}/repos/{owner}/{repo}/pulls/{pr_number}",
                headers=headers,
                timeout=10,
            )
            if response.status_code == 200:
                commit_sha = (
                    response.json()
                    .get("head", {})
                    .get("sha", "")
                )
        except Exception:
            pass

    # Map each valid file path to its unified diff.
    patch_map: Dict[str, str] = {}

    if files_data:
        for file_data in files_data:
            # FileData validation guarantees a non-empty file_path.
            patch_map[file_data.file_path] = file_data.diff
    else:
        # Auto-fetch changed files from GitHub.
        try:
            page = 1

            while True:
                files_response = _github_get(
                    f"{base}/repos/{owner}/{repo}/pulls/"
                    f"{pr_number}/files",
                    headers=headers,
                    params={
                        "per_page": 100,
                        "page": page,
                    },
                    timeout=30,
                )

                if files_response.status_code != 200:
                    break

                batch = files_response.json()

                if not batch:
                    break

                for file_entry in batch:
                    # Do not insert an empty-string path into patch_map.
                    filename = file_entry.get("filename")

                    if not isinstance(filename, str):
                        continue

                    filename = filename.strip()

                    if not filename:
                        continue

                    patch = file_entry.get("patch", "")
                    patch_map[filename] = (
                        patch if isinstance(patch, str) else ""
                    )

                if len(batch) < 100:
                    break

                page += 1

        except Exception as fetch_error:
            logger.warning(
                "post_github_review_comments: could not fetch "
                "PR files for position mapping: %s",
                fetch_error,
            )

    gh_comments: list[dict[str, Any]] = []
    errors: List[str] = []

    for comment in comments:
        severity_emoji = {
            "critical": "🔴",
            "major": "🟠",
            "minor": "🟡",
            "suggestion": "💡",
        }.get(comment.severity, "ℹ️")

        
        note = (
            f"{severity_emoji} "
            f"**[{comment.severity.upper()}]** "
            f"`{comment.category}` — {comment.title}\n\n"
            f"{comment.body}"
        )

        if comment.suggestion:
            note += (
                "\n\n### Suggested fix\n\n"
                f"{comment.suggestion}"
            )

        if comment.id:
            note += f"\n\n*Review ID: {comment.id}*"

        patch = patch_map.get(comment.file_path, "")
        position = _diff_position(
            patch,
            comment.line_number,
        )

        if position is not None:
            gh_comments.append(
                {
                    "path": comment.file_path,
                    "position": position,
                    "body": note,
                }
            )
        else:
            errors.append(
                f"Could not locate line "
                f"{comment.line_number} in diff for "
                f"{comment.file_path}; comment will appear "
                "in review body."
            )

            gh_comments.append(
                {
                    "_fallback": True,
                    "path": comment.file_path,
                    "line": comment.line_number,
                    "body": note,
                }
            )

    inline_comments = [
        comment
        for comment in gh_comments
        if not comment.get("_fallback")
    ]

    fallback_comments = [
        comment
        for comment in gh_comments
        if comment.get("_fallback")
    ]

    if not inline_comments and not fallback_comments:
        return {
            "review_id": None,
            "review_url": None,
            "posted": 0,
            "errors": errors
            or ["No postable review comments"],
        }

    event = "COMMENT"

    total = len(comments)
    critical_count = sum(
        1
        for comment in comments
        if comment.severity == "critical"
    )
    major_count = sum(
        1
        for comment in comments
        if comment.severity == "major"
    )

    base_review_body = (
        f"🤖 **Automated Code Review** — "
        f"{total} comment(s) | "
        f"🔴 {critical_count} critical | "
        f"🟠 {major_count} major\n\n"
        "Review generated by CodeReviewAgent."
    )

    def append_fallback_comments(
        body: str,
        review_comments: list[dict[str, Any]],
        heading: str,
        note: str,
    ) -> str:
        """
        Append comments to the top-level review body.

        This is used both for comments that could not initially be
        mapped and for the complete HTTP 422 fallback.
        """
        if not review_comments:
            return body

        body += f"\n\n### 📝 {heading}\n{note}\n\n"

        for review_comment in review_comments:
            location = review_comment.get(
                "line",
                review_comment.get("position", "?"),
            )

            body += (
                f"**File:** `{review_comment['path']}` "
                f"(Line/Position {location})\n\n"
                f"{review_comment['body']}\n\n"
                "---\n"
            )

        return body

    # Include comments that could not be mapped in the initial request.
    # This prevents them from being lost if GitHub accepts the inline
    # comments successfully.
    review_body = append_fallback_comments(
        body=base_review_body,
        review_comments=fallback_comments,
        heading="Additional Review Comments",
        note=(
            "*These comments could not be attached inline and are "
            "listed in the review body.*"
        ),
    )

    payload: dict[str, Any] = {
        "body": review_body,
        "event": event,
        "comments": inline_comments,
    }

    if commit_sha:
        payload["commit_id"] = commit_sha

    try:
        response = _session.post(
            f"{base}/repos/{owner}/{repo}/pulls/"
            f"{pr_number}/reviews",
            headers=headers,
            json=payload,
            timeout=30,
        )

        if response.status_code in (200, 201):
            review = response.json()

            logger.info(
                "post_github_review_comments: %s/%s PR#%d "
                "review_id=%s posted=%d fallback=%d",
                owner,
                repo,
                pr_number,
                review.get("id"),
                len(inline_comments),
                len(fallback_comments),
            )

            return {
                "review_id": review.get("id"),
                "review_url": review.get("html_url", ""),
                "posted": (
                    len(inline_comments)
                    + len(fallback_comments)
                ),
                "errors": errors,
            }

        if response.status_code == 422 and inline_comments:
            # Build this from base_review_body instead of review_body.
            # Otherwise pre-existing fallback comments would appear twice.
            all_review_comments = (
                inline_comments + fallback_comments
            )

            fallback_body = append_fallback_comments(
                body=base_review_body,
                review_comments=all_review_comments,
                heading="Review Comments (Fallback)",
                note=(
                    "*Inline placement failed, so all comments "
                    "are listed below.*"
                ),
            )

            fallback_payload = {
                **payload,
                "body": fallback_body,
                "comments": [],
            }

            retry_response = _session.post(
                f"{base}/repos/{owner}/{repo}/pulls/"
                f"{pr_number}/reviews",
                headers=headers,
                json=fallback_payload,
                timeout=30,
            )

            if retry_response.status_code in (200, 201):
                review = retry_response.json()

                logger.warning(
                    "post_github_review_comments: inline "
                    "placement failed with 422; posted a "
                    "fallback general review for PR#%d",
                    pr_number,
                )

                errors.append(
                    "Inline position mapping failed (422); "
                    "posted as a general review."
                )

                return {
                    "review_id": review.get("id"),
                    "review_url": review.get(
                        "html_url",
                        "",
                    ),
                    "posted": len(all_review_comments),
                    "errors": errors,
                }

        errors.append(
            f"GitHub API {response.status_code}: "
            f"{response.text[:300]}"
        )

        return {
            "review_id": None,
            "review_url": None,
            "posted": 0,
            "errors": errors,
        }

    except Exception as exc:
        errors.append(str(exc))

        return {
            "review_id": None,
            "review_url": None,
            "posted": 0,
            "errors": errors,
        }

# def post_github_review_comments(
#     owner: str,
#     repo: str,
#     pr_number: int,
#     comments: list,
#     commit_sha: str = "",
#     files_data: Optional[list] = None,
#     tool_context: ToolContext | None = None,
# ) -> Dict[str, Any]:
#     """
#     Post a GitHub Pull Request Review with inline comments.

#     Uses the GitHub Reviews API (POST /repos/:owner/:repo/pulls/:number/reviews)
#     which creates a review event with all inline comments atomically.

#     Args:
#         owner:      Repository owner
#         repo:       Repository name
#         pr_number:  Pull request number
#         comments:   List of comment dicts from the agent's output
#         commit_sha: HEAD commit SHA of the PR (from fetch_pr_diff result)
#         files_data: Optional list of changed-file dicts from fetch_pr_diff's
#                     ``changes`` field. Each entry must have ``file_path`` and
#                     ``diff`` keys. When provided (or auto-fetched internally),
#                     inline comments are anchored via the diff-relative ``position``
#                     field that GitHub's batch review endpoint requires.
#                     (Bug 6 fix: batch endpoint needs "position", not "line".)

#     Returns:
#         {
#           "review_id": int | null,
#           "review_url": str | null,
#           "posted": int,
#           "errors": [str]
#         }
#     """
#     token = _github_token()
#     if not token:
#         return {"review_id": None, "review_url": None, "posted": 0, "errors": ["GITHUB_TOKEN not set"]}

#     headers = _github_headers()
#     base = "https://api.github.com"

#     # If commit_sha not passed, fetch it
#     if not commit_sha:
#         try:
#             r = _session.get(
#                 f"{base}/repos/{owner}/{repo}/pulls/{pr_number}",
#                 headers=headers, timeout=10,
#             )
#             if r.status_code == 200:
#                 commit_sha = r.json().get("head", {}).get("sha", "")
#         except Exception:
#             pass

#     # Bug 6 fix: the batch review endpoint uses "position" (diff-relative offset),
#     # NOT "line" (absolute new-file line). Fetch per-file patches if not supplied.
#     patch_map: Dict[str, str] = {}
#     if files_data:
#         for f in files_data:
#             fp = f.get("file_path") or f.get("filename", "")
#             if fp:
#                 patch_map[fp] = f.get("diff") or f.get("patch", "")
#     else:
#         # Auto-fetch from GitHub PR files endpoint
#         try:
#             _page = 1
#             while True:
#                 files_resp = _github_get(
#                     f"{base}/repos/{owner}/{repo}/pulls/{pr_number}/files",
#                     headers=headers,
#                     params={"per_page": 100, "page": _page},
#                     timeout=30,
#                 )
#                 if files_resp.status_code != 200:
#                     break
#                 _batch = files_resp.json()
#                 if not _batch:
#                     break
#                 for f in _batch:
#                     patch_map[f.get("filename", "")] = f.get("patch", "")
#                 if len(_batch) < 100:
#                     break
#                 _page += 1
#         except Exception as _fe:
#             logger.warning("post_github_review_comments: could not fetch PR files for position mapping: %s", _fe)

#     # Build GitHub review comments
#     gh_comments = []
#     errors: List[str] = []

#     for comment in comments:
#         severity = comment.get("severity", "minor")
#         title = comment.get("title", "Code Review Comment")
#         body = comment.get("body", "")
#         suggestion = comment.get("suggestion", "")
#         file_path = comment.get("file_path", "")
#         line_number = comment.get("line_number", 1)
#         category = comment.get("category", "")
#         comment_id = comment.get("id", "")

#         severity_emoji = {
#             "critical": "🔴",
#             "major": "🟠",
#             "minor": "🟡",
#             "suggestion": "💡",
#         }.get(severity, "ℹ️")

#         note = f"{severity_emoji} **[{severity.upper()}]** `{category}` — {title}\n\n{body}"
#         if suggestion:
#             note += f"\n\n**Suggested fix:**\n```\n{suggestion}\n```"
#         if comment_id:
#             note += f"\n\n*Review ID: {comment_id}*"

#         if file_path and line_number > 0:
#             # Bug 6 fix: compute diff-relative position for the batch review endpoint.
#             # "line" is ignored by POST /pulls/:number/reviews; "position" is required.
#             patch = patch_map.get(file_path, "")
#             pos = _diff_position(patch, line_number)
#             if pos is not None:
#                 gh_comments.append({
#                     "path": file_path,
#                     "position": pos,
#                     "body": note,
#                 })
#             else:
#                 # Line not found in diff (e.g. unchanged context) — append to body instead
#                 errors.append(
#                     f"Could not locate line {line_number} in diff for {file_path}; "
#                     "comment will appear in review body."
#                 )
#                 # Accumulate for fallback body inclusion below
#                 gh_comments.append({"_fallback": True, "path": file_path, "line": line_number, "body": note})
#         else:
#             errors.append(f"Skipped inline comment (missing file or line): {title[:60]}")

#     inline_comments = [c for c in gh_comments if not c.get("_fallback")]
#     fallback_comments = [c for c in gh_comments if c.get("_fallback")]

#     if not inline_comments and not fallback_comments:
#         return {
#             "review_id": None,
#             "review_url": None,
#             "posted": 0,
#             "errors": errors or ["No postable inline comments (missing line info)"],
#         }

#     # Always use COMMENT event (as requested by user)
#     event = "COMMENT"

#     # Aggregate body
#     total = len(comments)
#     crits = sum(1 for c in comments if c.get("severity") == "critical")
#     majors = sum(1 for c in comments if c.get("severity") == "major")
#     review_body = (
#         f"🤖 **Automated Code Review** — {total} comment(s) | "
#         f"🔴 {crits} critical | 🟠 {majors} major\n\n"
#         f"Review generated by CodeReviewAgent."
#     )

#     payload = {
#         "body": review_body,
#         "event": event,
#         "comments": inline_comments,
#     }
#     if commit_sha:
#         payload["commit_id"] = commit_sha

#     try:
#         resp = _session.post(
#             f"{base}/repos/{owner}/{repo}/pulls/{pr_number}/reviews",
#             headers=headers,
#             json=payload,
#             timeout=30,
#         )
        
#         if resp.status_code in (200, 201):
#             review = resp.json()
#             logger.info(
#                 "post_github_review_comments: %s/%s PR#%d review_id=%s posted=%d fallback=%d",
#                 owner, repo, pr_number, review.get("id"), len(inline_comments), len(fallback_comments),
#             )
#             return {
#                 "review_id": review.get("id"),
#                 "review_url": review.get("html_url", ""),
#                 "posted": len(inline_comments) + len(fallback_comments),
#                 "errors": errors,
#             }
#         elif resp.status_code == 422 and inline_comments:
#             # Fallback: GitHub rejects the entire review if even one position is invalid.
#             # Strip inline comments and move them all into the body.
#             fallback_body = review_body + "\n\n### 📝 Review Comments (Fallback)\n*Note: Inline placement failed, comments are listed below:*\n\n"
#             for c in inline_comments + fallback_comments:
#                 fallback_body += f"**File:** `{c['path']}` (Position/Line {c.get('position') or c.get('line', '?')})\n{c['body']}\n\n---\n"
            
#             payload["comments"] = []
#             payload["body"] = fallback_body
            
#             retry_resp = _session.post(
#                 f"{base}/repos/{owner}/{repo}/pulls/{pr_number}/reviews",
#                 headers=headers,
#                 json=payload,
#                 timeout=30,
#             )
#             if retry_resp.status_code in (200, 201):
#                 review = retry_resp.json()
#                 logger.warning("post_github_review_comments: inline failed (422), posted fallback general review for PR#%d", pr_number)
#                 errors.append("Inline position mapping failed (422); posted as a general review.")
#                 return {
#                     "review_id": review.get("id"),
#                     "review_url": review.get("html_url", ""),
#                     "posted": len(inline_comments) + len(fallback_comments),
#                     "errors": errors,
#                 }
            
#         errors.append(f"GitHub API {resp.status_code}: {resp.text[:300]}")
#         return {"review_id": None, "review_url": None, "posted": 0, "errors": errors}
#     except Exception as exc:
#         errors.append(str(exc))
#         return {"review_id": None, "review_url": None, "posted": 0, "errors": errors}