# Generated by NeuroStack
# Vendored from platform origin: tool/get_account_holder_names (upstream_version=platform)

from __future__ import annotations
from typing import Any, Dict, List
import os
from sqlalchemy import create_engine, text
from dotenv import load_dotenv , find_dotenv
load_dotenv(find_dotenv())

# ---------------------------------------------------------------------------
# DB CONNECTION
# ---------------------------------------------------------------------------

# FINANCE_DB_URL points at the Postgres database holding account_holders (e.g. neurostack_dev).
# Falls back to a local finance.db SQLite file only when the env var is unset (local dev without Postgres access).
current_dir = os.path.dirname(os.path.abspath(__file__))
default_db_path = os.path.join(current_dir, "..", "examples", "finance.db")
FINANCE_DB_URL = os.getenv("DATABASE_URL", f"sqlite:///{default_db_path}")

_engine = None

def get_engine():
    """Lazy-load the SQLAlchemy database engine."""
    global _engine
    if _engine is None:
        _engine = create_engine(FINANCE_DB_URL, pool_size=5, max_overflow=10)
    return _engine

def _execute(query: str, params: tuple = ()) -> list[dict]:
    # Seamlessly adapt '?' placeholder queries to SQLAlchemy named parameter mapping
    engine = get_engine()
    
    param_dict = {}
    param_count = 0
    while "?" in query:
        placeholder = f":p{param_count}"
        query = query.replace("?", placeholder, 1)
        if param_count < len(params):
            param_dict[f"p{param_count}"] = params[param_count]
        param_count += 1
        
    with engine.connect() as conn:
        result = conn.execute(text(query), param_dict)
        return [dict(row._mapping) for row in result]

def _get_role(tool_context: Any) -> str:
    """Helper to extract user role from tool context."""
    if not tool_context or not hasattr(tool_context, "state"):
        return "user"
    return tool_context.state.get("user_metadata", {}).get("role", "user")

# ---------------------------------------------------------------------------
# TOOLS
# ---------------------------------------------------------------------------

def get_account_holder_names(filter_name: str | None = None) -> Dict[str, Any]:
    """Returns a list of account holder names. Only names are returned."""
    query = "SELECT account_holder_name FROM account_holders"
    params = []
    if filter_name:
        query += " WHERE LOWER(account_holder_name) LIKE LOWER(?)"
        params.append(f"%{filter_name}%")
    
    rows = _execute(query, tuple(params))
    return {
        "status": "success",
        "data": [{"account_holder_name": r["account_holder_name"]} for r in rows]
    }

def get_customer_ids(account_holder_name: str | None = None) -> Dict[str, Any]:
    """Returns customer IDs associated with account holders."""
    query = "SELECT account_holder_name, customer_id FROM account_holders"
    params = []
    if account_holder_name:
        query += " WHERE LOWER(account_holder_name) LIKE LOWER(?)"
        params.append(f"%{account_holder_name}%")
        
    rows = _execute(query, tuple(params))
    return {
        "status": "success",
        "data": [dict(r) for r in rows]
    }

def get_account_ids(account_holder_name: str | None = None, tool_context: Any = None) -> Dict[str, Any]:
    """
    Returns account IDs. 
    Note: For 'user' and 'developer' roles, the IDs are masked with asterisks.
    For 'admin' role, full IDs are shown.
    """
    role = _get_role(tool_context)
    query = "SELECT account_holder_name, account_id FROM account_holders"
    params = []
    if account_holder_name:
        query += " WHERE LOWER(account_holder_name) LIKE LOWER(?)"
        params.append(f"%{account_holder_name}%")
        
    rows = _execute(query, tuple(params))
    
    data = []
    for r in rows:
        row_dict = dict(r)
        if role in ["user", "developer"]:
            # Masking logic
            raw_id = row_dict["account_id"]
            if "-" in raw_id:
                parts = raw_id.split("-")
                row_dict["account_id"] = f"{parts[0]}-***-***"
            else:
                row_dict["account_id"] = "***-***"
        data.append(row_dict)
        
    return {
        "status": "success",
        "data": data,
        "note": "Account IDs are masked for your role." if role != "admin" else "Clear text IDs shown for admin."
    }

def get_account_types(account_holder_name: str | None = None) -> Dict[str, Any]:
    """Returns account types (savings, current, fd, nro)."""
    query = "SELECT account_holder_name, account_type FROM account_holders"
    params = []
    if account_holder_name:
        query += " WHERE LOWER(account_holder_name) LIKE LOWER(?)"
        params.append(f"%{account_holder_name}%")
        
    rows = _execute(query, tuple(params))
    return {
        "status": "success",
        "data": [dict(r) for r in rows]
    }

def get_account_balances(account_holder_name: str | None = None) -> Dict[str, Any]:
    """Returns account balances. Access restricted by RBAC guardrail."""
    query = "SELECT account_holder_name, account_balance FROM account_holders"
    params = []
    if account_holder_name:
        query += " WHERE LOWER(account_holder_name) LIKE LOWER(?)"
        params.append(f"%{account_holder_name}%")
        
    rows = _execute(query, tuple(params))
    return {
        "status": "success",
        "data": [dict(r) for r in rows]
    }

def get_account_start_dates(account_holder_name: str | None = None) -> Dict[str, Any]:
    """Returns the dates when accounts were opened."""
    query = "SELECT account_holder_name, account_start_date FROM account_holders"
    params = []
    if account_holder_name:
        query += " WHERE LOWER(account_holder_name) LIKE LOWER(?)"
        params.append(f"%{account_holder_name}%")
        
    rows = _execute(query, tuple(params))
    return {
        "status": "success",
        "data": [dict(r) for r in rows]
    }

def get_last_interaction_dates(account_holder_name: str | None = None) -> Dict[str, Any]:
    """Returns the date of last interaction with the customer."""
    query = "SELECT account_holder_name, last_interaction_date FROM account_holders"
    params = []
    if account_holder_name:
        query += " WHERE LOWER(account_holder_name) LIKE LOWER(?)"
        params.append(f"%{account_holder_name}%")
        
    rows = _execute(query, tuple(params))
    return {
        "status": "success",
        "data": [dict(r) for r in rows]
    }

def get_last_transaction_amounts(account_holder_name: str | None = None) -> Dict[str, Any]:
    """Returns the amount of the last transaction. Access restricted by RBAC guardrail."""
    query = "SELECT account_holder_name, last_transaction_amount FROM account_holders"
    params = []
    if account_holder_name:
        query += " WHERE LOWER(account_holder_name) LIKE LOWER(?)"
        params.append(f"%{account_holder_name}%")
        
    rows = _execute(query, tuple(params))
    return {
        "status": "success",
        "data": [dict(r) for r in rows]
    }

# Registry for easy importing
TOOLS = [
    get_account_holder_names,
    get_customer_ids,
    get_account_ids,
    get_account_types,
    get_account_balances,
    get_account_start_dates,
    get_last_interaction_dates,
    get_last_transaction_amounts,
]