# Generated by NeuroStack
# Artifact: tool/add_cubes.py

"""Calculate the sum of cubes of three numbers.

This tool takes three numeric values and returns the sum of their cubes.
Use this when you need to compute a³ + b³ + c³ for any three numbers.
"""

from typing import Union


def add_cubes(num1: float, num2: float, num3: float) -> dict:
    """Calculate the sum of cubes of three numbers.
    
    Computes num1³ + num2³ + num3³ and returns the result.
    
    Args:
        num1: The first number (int or float)
        num2: The second number (int or float)
        num3: The third number (int or float)
    
    Returns:
        A dictionary with:
        - On success: {"status": "success", "result": <sum_of_cubes>}
        - On error: {"status": "error", "error_message": "<error_description>"}
    
    Examples:
        >>> add_cubes(2, 3, 4)
        {"status": "success", "result": 99}
        
        >>> add_cubes(1, 1, 1)
        {"status": "success", "result": 3}
    """
    try:
        # Validate inputs are numeric
        if not all(isinstance(n, (int, float)) for n in [num1, num2, num3]):
            return {
                "status": "error",
                "error_message": "All parameters must be numeric (int or float)"
            }
        
        # Calculate cubes
        cube1 = num1 ** 3
        cube2 = num2 ** 3
        cube3 = num3 ** 3
        
        # Sum the cubes
        result = cube1 + cube2 + cube3
        
        return {
            "status": "success",
            "result": result
        }
        
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Error calculating sum of cubes: {str(e)}"
        }
