# Generated by NeuroStack
# Vendored from platform origin: tool/compression_tools (upstream_version=platform)

"""
Generated Tools - compression_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-01-09 16:42:00
Total tools: 2
"""

import zipfile
import os
from typing import Dict, Any

def zip_file(source_path: str, destination_path: str) -> Dict[str, Any]:
    """
    Compresses a file or directory into a zip file.

    Args:
        source_path (str): Path to the file or directory to be zipped.
        destination_path (str): Path to the output zip file.

    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields.
                       Example: {"success": True, "message": "File zipped successfully", "data": {}}
    """
    try:
        with zipfile.ZipFile(destination_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            if os.path.isfile(source_path):
                zipf.write(source_path, os.path.basename(source_path))
            else:
                for root, _, files in os.walk(source_path):
                    for file in files:
                        file_path = os.path.join(root, file)
                        zipf.write(file_path, os.path.relpath(file_path, source_path))

        return {
            "success": True,
            "message": "File zipped successfully",
            "data": {}
        }
    except FileNotFoundError:
        return {
            "success": False,
            "message": f"Error: Source file or directory not found: {source_path}",
            "data": {}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }

def unzip_file(zip_file_path: str, destination_path: str) -> Dict[str, Any]:
    """
    Unzips a zip file to a specified destination directory.

    Args:
        zip_file_path (str): Path to the zip file to be unzipped.
        destination_path (str): Path to the directory where the contents of the zip file will be extracted.

    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields.
                       Example: {"success": True, "message": "File unzipped successfully", "data": {}}
    """
    try:
        with zipfile.ZipFile(zip_file_path, 'r') as zipf:
            zipf.extractall(destination_path)

        return {
            "success": True,
            "message": "File unzipped successfully",
            "data": {}
        }
    except FileNotFoundError:
        return {
            "success": False,
            "message": f"Error: Zip file not found: {zip_file_path}",
            "data": {}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }
