# Generated by NeuroStack
# Vendored from platform origin: tool/get_current_time (upstream_version=platform)

"""
Generated Tools - datetime_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2025-07-04 20:14:07
Total tools: 2
"""

from typing import Dict, Any, List, Optional
from datetime import datetime


def get_current_date() -> Dict[str, Any]:
    """
    Retrieves the current date.

    Args:
        None

    Returns:
        Dict[str, Any]: A dictionary containing the success status, message, and the current date in ISO format.
                         Example: {"success": True, "message": "Successfully retrieved current date.", "data": {"current_date": "2023-10-27"}}
    """
    try:
        current_date = datetime.now().isoformat()[:10]  # Get only the date part in ISO format (YYYY-MM-DD)

        return {
            "success": True,
            "message": "Successfully retrieved current date.",
            "data": {"current_date": current_date}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: Failed to retrieve current date. {str(e)}",
            "data": {}
        }


def get_current_time() -> Dict[str, Any]:
    """
    Retrieves the current time.

    Args:
        None

    Returns:
        Dict[str, Any]: A dictionary containing the success status, a message, and the current time in ISO format.
                        Example: {"success": True, "message": "Current time retrieved successfully.", "data": {"current_time": "2023-10-27T10:00:00"}}
                        In case of failure, "success" will be False and "message" will contain an error message.
    """
    try:
        current_time = datetime.now().isoformat()
        return {
            "success": True,
            "message": "Current time retrieved successfully.",
            "data": {"current_time": current_time}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error retrieving current time: {str(e)}"
        }