# Generated by NeuroStack
# Vendored from platform origin: tool/deployed_ps_25 (upstream_version=platform)

"""
Auto-generated deployed tool wrapper.

Tool name: deployed_ps_25
Generated on: 2026-03-27 00:46:02
"""

from typing import Dict, Any, Optional, List
import httpx

from ..core.logger import get_logger as _get_logger

BASE_URL = "http://ecs-neurostack-sdlc-604389771.us-east-1.elb.amazonaws.com"
AVAILABLE_OPERATIONS: List[Dict[str, Any]] = [
    {
        "method": "GET",
        "path": "/weather"
    },
    {
        "method": "GET",
        "path": "/forecast"
    },
    {
        "method": "GET",
        "path": "/conditions"
    }
]

LOGGER = _get_logger("tools")


def _resolve_operation(operation: str) -> Dict[str, Any]:
    """Resolve operation metadata by path."""
    for op in AVAILABLE_OPERATIONS:
        if op.get("path") == operation:
            return op
    if operation.startswith("/weather"):
        return {"method": "GET", "path": "/weather"}
    if operation.startswith("/forecast"):
        return {"method": "GET", "path": "/forecast"}
    if operation.startswith("/conditions"):
        return {"method": "GET", "path": "/conditions"}
    return {"method": "POST", "path": operation}


def _normalize_weather_operation(
    operation: str,
    query_params: Optional[Dict[str, Any]],
) -> (str, Optional[Dict[str, Any]]):
    """Convert tool aliases and legacy path-style calls to the deployed API shape."""
    resolved_query_params = dict(query_params or {})

    alias_map = {
        "get_weather": "/weather",
        "weather": "/weather",
        "get_forecast": "/forecast",
        "forecast": "/forecast",
        "get_current_conditions": "/conditions",
        "current_conditions": "/conditions",
        "conditions": "/conditions",
    }
    alias_key = operation.lstrip("/")
    if alias_key in alias_map:
        return alias_map[alias_key], (resolved_query_params or None)

    for prefix in ("/weather/", "/forecast/", "/conditions/"):
        if operation.startswith(prefix):
            location = operation[len(prefix):].strip("/")
            if location:
                resolved_query_params.setdefault("location", location)
            return prefix[:-1], (resolved_query_params or None)

    if operation in {"/weather/{location}", "/forecast/{location}", "/conditions/{location}"}:
        base_operation = operation.split("/{", 1)[0]
        return base_operation, (resolved_query_params or None)

    return operation, (resolved_query_params or None)


def _infer_operation_and_params(
    operation: Optional[str],
    query_params: Optional[Dict[str, Any]],
    extra_kwargs: Dict[str, Any],
) -> (Optional[str], Optional[Dict[str, Any]]):
    """Best-effort normalization for LLM-generated tool arguments."""
    resolved_operation = operation
    resolved_query_params = dict(query_params or {})

    # Accept alternate argument names an LLM may produce.
    if not resolved_operation:
        resolved_operation = extra_kwargs.pop("operation", None) or extra_kwargs.pop("path", None)

    location = extra_kwargs.get("location")
    if not resolved_operation and location:
        extra_kwargs.pop("location", None)
        request_type = str(extra_kwargs.pop("request_type", "weather")).lower()
        if "forecast" in request_type:
            resolved_operation = f"/forecast/{location}"
        else:
            resolved_operation = f"/weather/{location}"

    if resolved_operation and not str(resolved_operation).startswith("/"):
        resolved_operation = f"/{resolved_operation}"

    # Keep any unknown kwargs as query params instead of failing the invocation.
    for key, value in extra_kwargs.items():
        resolved_query_params.setdefault(key, value)

    return resolved_operation, (resolved_query_params or None)


def deployed_ps_25(
    operation: Optional[str] = None,
    payload: Optional[Dict[str, Any]] = None,
    query_params: Optional[Dict[str, Any]] = None,
    timeout_seconds: float = 20.0,
    **kwargs: Any,
) -> Dict[str, Any]:
    """Weather information assistant"""
    operation, query_params = _infer_operation_and_params(operation, query_params, kwargs)
    if operation:
        operation, query_params = _normalize_weather_operation(operation, query_params)

    if not operation:
        return {
            "success": False,
            "message": "No operation specified",
            "data": {"available_operations": AVAILABLE_OPERATIONS},
        }

    try:
        op_meta = _resolve_operation(operation)
        method = str(op_meta.get("method", "POST")).upper()
        url = f"{BASE_URL}{operation}"
        LOGGER.info(f"deployed_ps_25 request | method={method} url={url} query_params={query_params}")

        request_kwargs: Dict[str, Any] = {
            "method": method,
            "url": url,
            "timeout": timeout_seconds,
        }

        if query_params:
            request_kwargs["params"] = query_params

        if payload and method in {"POST", "PUT", "PATCH", "DELETE"}:
            request_kwargs["json"] = payload

        response = httpx.request(**request_kwargs)
        LOGGER.info(f"deployed_ps_25 response | status_code={response.status_code} url={url}")

        try:
            response_data: Any = response.json()
        except Exception:
            response_data = {"text": response.text}

        if 200 <= response.status_code < 300:
            return {
                "success": True,
                "message": f"Operation {operation} completed successfully",
                "data": response_data,
                "status_code": response.status_code,
            }

        return {
            "success": False,
            "message": f"HTTP {response.status_code}: {response.text}",
            "data": response_data,
            "status_code": response.status_code,
        }
    except Exception as e:
        LOGGER.error(f"deployed_ps_25 exception | url={BASE_URL}{operation} error={str(e)}")
        return {
            "success": False,
            "message": f"Failed to call deployed tool: {str(e)}",
            "data": {},
        }


def get_weather(location: str, timeout_seconds: float = 20.0) -> Dict[str, Any]:
    """Get current weather information for a location."""
    return deployed_ps_25(
        operation="/weather",
        query_params={"location": location},
        timeout_seconds=timeout_seconds,
    )


def get_forecast(location: str, days: int = 3, timeout_seconds: float = 20.0) -> Dict[str, Any]:
    """Get weather forecast for a location."""
    return deployed_ps_25(
        operation="/forecast",
        query_params={"location": location, "days": days},
        timeout_seconds=timeout_seconds,
    )


def get_current_conditions(location: str, timeout_seconds: float = 20.0) -> Dict[str, Any]:
    """Get detailed current weather conditions for a location."""
    return deployed_ps_25(
        operation="/conditions",
        query_params={"location": location},
        timeout_seconds=timeout_seconds,
    )
