# Generated by NeuroStack
# Vendored from platform origin: tool/global_tools (upstream_version=platform)

"""
Universal tiered hybrid retrieval for any ADK agent pipeline.

Works with any JSON output format including nested agent payloads.
"""

from google.adk.tools.tool_context import ToolContext
from google.adk.tools import FunctionTool
from typing import Any
import re
import json
import time
import logging

logger = logging.getLogger(__name__)

# ── Tuning knobs ──────────────────────────────────────────────────────────────
_BM25_CONFIDENCE      = 0.5
_SEMANTIC_THRESHOLD   = 0.20
_MAX_KEYS             = 5
_FINGERPRINT_TOKENS   = 60    # max meaningful tokens in fingerprint
_RECENCY_BOOST        = 0.08

# ── Lazy model load (avoids torch import at app startup on Windows) ───────────
_embedder = None
_embedder_load_error: str | None = None


def _get_embedder():
    """Load MiniLM on first use; return None if torch/sentence-transformers unavailable."""
    global _embedder, _embedder_load_error
    if _embedder is not None:
        return _embedder
    if _embedder_load_error is not None:
        return None
    try:
        logger.info("Loading MiniLM embedding model...")
        from sentence_transformers import SentenceTransformer

        _embedder = SentenceTransformer("all-MiniLM-L6-v2")
        logger.info("MiniLM ready.")
        return _embedder
    except Exception as exc:
        _embedder_load_error = str(exc)
        logger.warning(
            f"MiniLM unavailable ({exc}). "
            "Semantic tier disabled; BM25/recency only."
        )
        return None


# ── Keys that are pure scaffolding — never meaningful for retrieval ────────────
# These appear in EVERY agent output and would pollute BM25/semantic equally,
# making all keys look identical.
_SCAFFOLD_KEYS = {
    # Agent metadata
    "agent", "agent_name", "agent_version", "output_key",
    # Session/invocation IDs
    "session_id", "invocation_id",
    # Timestamps
    "timestamp", "created_date", "updated_date", "last_updated",
    "scan_timestamp", "project_tests_scan_timestamp",
    # Generic status wrappers
    "message", "type",
    # Empty containers
    "linked_issues", "labels", "extra_libraries", "custom_structure",
    "github_repo", "docs", "references", "_sources",
    # Source provenance (nested copy of same data)
    "session", "ticket", "session_id", "long_term_context", "memory_loaded", "state",
    "role" , "user_role" , "is_authenticated" , "user_metadata"
}

# ── Values that carry no semantic signal ──────────────────────────────────────
_BORING_VALUES = re.compile(
    r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'  # UUID
    r'|^\d{4}-\d{2}-\d{2}T[\d:.+Z-]+$'   # ISO timestamp
    r'|^e-[0-9a-f-]{30,}$'               # ADK invocation ID
    r'|^\d+(\.\d+)?$'                    # pure number
    r'|^(null|true|false)$',             # JSON literals
    re.IGNORECASE
)

# ── High-value keys — always include their values even if short ────────────────
# These keys contain the most discriminating content for retrieval.
_HIGH_VALUE_KEYS = {
    # Story/ticket content
    "summary", "description", "acceptance_criteria", "story_id",
    "project_key", "project_name",
    # Test content
    "test_summary", "test_description", "test_key", "test_type",
    # Deployment content
    "error", "error_type", "deployment_status", "app_name",
    "environment", "remediation_steps", "logs",
    # Tech requirements
    "framework", "language", "pattern", "primary", "auth_mechanism",
    "compliance", "platform",
    # Generic high-value
    "status", "data", "stories", "results", "output"
}


def _extract_tokens(obj: Any, depth: int = 0, max_depth: int = 8) -> list[str]:
    """
    Recursively extract meaningful tokens from any JSON structure.

    Priority order:
      1. High-value key values → always included
      2. Regular string values → included if not boring
      3. Key names → included if not scaffold and not boring
      4. Lists → recursed into
      5. Nested dicts → recursed into, scaffold keys skipped
    """
    if depth > max_depth:
        return []

    tokens = []

    if isinstance(obj, dict):
        for k, v in obj.items():
            k_str = str(k)
            is_scaffold = (
                k_str in _SCAFFOLD_KEYS or
                k_str.startswith(('_adk', '__', '_', 'temp:'))
            )
            is_high_value = k_str in _HIGH_VALUE_KEYS

            # Always recurse into high-value keys
            if is_high_value:
                # Add the key name itself as a token
                tokens.append(k_str.replace("_", " "))
                # Add value directly if it's a short string
                if isinstance(v, str) and v.strip() and not _BORING_VALUES.match(v.strip()):
                    tokens.append(v.strip()[:120])
                elif isinstance(v, list):
                    tokens.extend(_extract_tokens(v, depth + 1, max_depth))
                elif isinstance(v, dict):
                    tokens.extend(_extract_tokens(v, depth + 1, max_depth))
            elif not is_scaffold:
                # Regular key — add name as token if meaningful
                if len(k_str) > 2 and not k_str.startswith("_"):
                    tokens.append(k_str.replace("_", " "))
                tokens.extend(_extract_tokens(v, depth + 1, max_depth))
            # Scaffold keys: skip entirely

    elif isinstance(obj, list):
        for item in obj:
            tokens.extend(_extract_tokens(item, depth + 1, max_depth))

    elif isinstance(obj, str):
        v = obj.strip()
        if v and len(v) > 2 and not _BORING_VALUES.match(v):
            tokens.append(v[:120])

    elif isinstance(obj, (int, float, bool)):
        pass  # never useful for text retrieval

    return tokens


def _make_fingerprint(key: str, value: Any) -> str:
    """
    Build a retrieval fingerprint for a session state key-value pair.

    For JSON/dict values: extracts meaningful tokens using _extract_tokens.
    For plain strings:    uses head+tail slice.

    The fingerprint is what BM25 and the semantic embedder both operate on.
    It must contain domain-relevant terms, not JSON scaffolding.
    """
    key_label = key.replace("_", " ")

    # Try JSON parse if string
    parsed = None
    if isinstance(value, dict):
        parsed = value
    elif isinstance(value, str):
        try:
            parsed = json.loads(value)
        except (json.JSONDecodeError, ValueError):
            parsed = None

    if parsed is not None:
        raw_tokens = _extract_tokens(parsed)

        # Deduplicate preserving order
        seen, unique = set(), []
        for t in raw_tokens:
            t_lower = t.lower()
            if t_lower not in seen and len(t_lower) > 1:
                seen.add(t_lower)
                unique.append(t)
            if len(unique) >= _FINGERPRINT_TOKENS:
                break

        content = " | ".join(unique)
        fingerprint = f"{key_label}: {content}"
        return fingerprint

    # Plain string fallback
    value_str = str(value)
    chars = _FINGERPRINT_TOKENS * 8
    head = value_str[:chars]
    tail = value_str[-chars:] if len(value_str) > chars * 2 else ""
    sep  = " ... " if tail else ""
    return f"{key_label}: {head}{sep}{tail}"


# ── Similarity helpers ─────────────────────────────────────────────────────────

def _cosine_similarity(a, b) -> float:
    import numpy as np
    a, b = np.array(a), np.array(b)
    denom = np.linalg.norm(a) * np.linalg.norm(b)
    return float(np.dot(a, b) / denom) if denom > 0 else 0.0


def _tokenize(text: str) -> list[str]:
    return re.findall(r"\w+", text.lower())


def _apply_recency_boost(scores: dict, available_keys: list) -> dict:
    boosted = dict(scores)
    n = len(available_keys)
    for i, key in enumerate(available_keys):
        if key not in boosted:
            continue
        pos = n - 1 - i
        if pos == 0:
            boosted[key] = boosted[key] + _RECENCY_BOOST
        elif pos == 1:
            boosted[key] = boosted[key] + _RECENCY_BOOST * 0.5
    return boosted


# ── Main retrieval function ────────────────────────────────────────────────────
def fetch_relevant_context(goal: str, tool_context: ToolContext | None = None) -> dict:
    """
    Tiered hybrid retrieval. Works for any agent, any pipeline, any JSON format.

    Tier 1 — BM25 on fingerprints   (~0.1ms, no model)
    Tier 2 — MiniLM semantic         (~50ms, model in memory)
    Tier 3 — Recency fallback        (~0ms)
    """
    t0 = time.perf_counter()
    logger.debug(f"fetch_relevant_context | agent: {tool_context.agent_name}")
    logger.debug(f"Goal: '{goal}'")

    raw_state: dict = tool_context.session.state

    if not raw_state:
        return {
            "found": False, "matched_count": 0,
            "results": [], "available_keys": [],
            "instructions": "Session state empty. Proceed from user message.",
        }

    available_keys = [
        k for k in raw_state.keys()
        if k not in _SCAFFOLD_KEYS and not k.startswith(('_adk', '__', '_', 'temp:'))
    ]
    logger.debug(f"Available keys (filtered): {available_keys}")

    if not available_keys:
        return {
            "found": False, "matched_count": 0,
            "results": [], "available_keys": [],
            "instructions": "Session state contains only system keys. Proceed from user message.",
        }

    # Build fingerprints
    fingerprints = {}
    for k in available_keys:
        fp = _make_fingerprint(k, raw_state[k])
        fingerprints[k] = fp
        logger.debug(f"Fingerprint[{k}]: {fp[:200]}")

    # ── Tier 1: BM25 ──────────────────────────────────────────────────────────
    from rank_bm25 import BM25Okapi

    corpus_tokens = [_tokenize(fp) for fp in fingerprints.values()]
    query_tokens  = _tokenize(goal)
    bm25          = BM25Okapi(corpus_tokens)
    raw_bm25      = bm25.get_scores(query_tokens)

    bm25_min   = min(raw_bm25)
    bm25_max   = max(raw_bm25)
    bm25_range = bm25_max - bm25_min if bm25_max != bm25_min else 1.0
    bm25_norm  = {
        k: float((raw_bm25[i] - bm25_min) / bm25_range)
        for i, k in enumerate(available_keys)
    }
    top_bm25 = max(bm25_norm.values())
    logger.debug(f"BM25 normalised: { {k: round(v,3) for k,v in bm25_norm.items()} }")
    logger.debug(f"BM25 top: {round(top_bm25,3)} | threshold: {_BM25_CONFIDENCE}")

    if top_bm25 >= _BM25_CONFIDENCE:
        matched = dict(bm25_norm)
        matched = _apply_recency_boost(matched, available_keys)
        method  = "bm25"
        logger.debug("BM25 confident.")
    else:
        # ── Tier 2: Semantic ───────────────────────────────────────────────────
        logger.debug("BM25 below threshold. Running semantic tier...")
        embedder = _get_embedder()
        if embedder is None:
            matched = _apply_recency_boost(dict(bm25_norm), available_keys)
            method  = "bm25"
            logger.debug("Semantic skipped (embedder unavailable). Using BM25 + recency.")
        else:
            try:
                texts      = [goal] + list(fingerprints.values())
                embeddings = embedder.encode(
                    texts, convert_to_numpy=True, show_progress_bar=False
                )
                goal_emb   = embeddings[0]
                sem_scores = {
                    k: _cosine_similarity(goal_emb, embeddings[i + 1])
                    for i, k in enumerate(available_keys)
                }
                logger.debug(f"Semantic: { {k: round(v,3) for k,v in sem_scores.items()} }")

                bm25_max_val = max(bm25_norm.values()) if max(bm25_norm.values()) > 0 else 1
                fused = {
                    k: 0.4 * (bm25_norm[k] / bm25_max_val) + 0.6 * sem_scores[k]
                    for k in available_keys
                }
                fused   = _apply_recency_boost(fused, available_keys)
                logger.debug(f"Fused+recency: { {k: round(v,3) for k,v in fused.items()} }")

                matched = {
                    k: v for k, v in fused.items() if sem_scores[k] >= _SEMANTIC_THRESHOLD
                }
                method  = "semantic"

            except Exception as e:
                logger.error(f"Semantic failed: {e}")
                matched = {}
                method  = "recency_fallback"

    # ── Tier 3: Recency fallback ───────────────────────────────────────────────
    if not matched:
        matched = {available_keys[-1]: 0.0}
        method  = "recency_fallback"
        logger.debug(f"Recency fallback -> '{available_keys[-1]}'")

    sorted_matched = sorted(matched.items(), key=lambda x: x[1], reverse=True)[:_MAX_KEYS]
    skipped        = [k for k in available_keys if k not in dict(sorted_matched)]

    results = []
    for key, score in sorted_matched:
        value = tool_context.state.get(key)
        logger.debug(f"key='{key}' | score={round(score,3)} | method={method}")
        results.append({"key": key, "score": round(score,3), "value": value})

    elapsed = round((time.perf_counter() - t0) * 1000, 1)
    logger.debug(f"Done in {elapsed}ms | matched={len(results)} | skipped={skipped}")

    return {
        "found"            : True,
        "resolution_method": method,
        "matched_count"    : len(results),
        "results"          : results,
        "skipped_keys"     : skipped,
        "available_keys"   : available_keys,
    }




UNIVERSAL_CONTEXT_INSTRUCTION = """
=== MANDATORY CONTEXT RETRIEVAL ===

You are an independent agent invocation. Session state may contain outputs
from prior agents, system-injected data, or be empty. You must always check
before proceeding — you cannot know what exists without calling the tool.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP 1 — FIRST ACTION: call fetch_relevant_context(goal="...")
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Do this BEFORE writing your first response when YOU are invoked.
  CRITICAL: If YOU (this specific agent) have already called `fetch_relevant_context` 
  during your current execution in this chat history, DO NOT call it again! 
  However, if you are a newly invoked agent in a pipeline, you MUST call it once.

  ── WRITING AN EFFECTIVE GOAL ──────────────────────────────────────────

  Structure: "<expected_key_tokens> : <what you need it for>"

  Key tokens = the words you expect in the key name, underscores as spaces.

  WHY: The tool does keyword matching first (fast, ~0.1ms).
       Including key name words = instant match.
       Vague goals = semantic fallback (~50ms, less precise).

  KEY NAMING PATTERNS — keys in session state typically follow one of:
    • <agent_name>_output      e.g. "researcher output", "planner output"
    • <data_type>_data         e.g. "user data", "config data"
    • <step>_result            e.g. "validation result", "parse result"
    • <noun>                   e.g. "context", "profile", "summary"

  GOAL TEMPLATES:

    One upstream agent output:
      "<agent_name> output : <what you will do with it>"

    Multiple upstream outputs:
      "<agent_a> output <agent_b> output : <what you need both for>"

    System-injected data (user profile, config, preferences):
      "<data_type> data config profile : retrieve system context for my task"

    Unknown keys (first run, no prior knowledge):
      "<describe the content you expect> : <what you will do with it>"

  EXAMPLES (domain-independent):
    ✅ "researcher output : get research findings to write a structured report"
    ✅ "planner output drafter output : review plan and draft together"
    ✅ "user profile config : personalise my output to user preferences"
    ✅ "validation result : check if upstream validation passed or failed"
    ✅ "parsed data extracted data : use structured data to generate analysis"
    ✅ "summarised findings key points : compose executive brief from summary"

    ❌ "get the latest result"               ← no tokens, slow semantic path
    ❌ "find what the previous agent made"   ← no tokens, slow semantic path

  ───────────────────────────────────────────────────────────────────────

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP 2 — INTERPRET THE RESULT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  The tool returns: found, results[], resolution_method, matched_count.

  ┌─────────────────────┬──────────────────────────────────────────────┐
  │ found = False       │ No prior context. Proceed from user message. │
  │                     │ Complete your task fully — this is normal    │
  │                     │ for the first agent in any pipeline.         │
  ├─────────────────────┼──────────────────────────────────────────────┤
  │ found = True        │ Use ALL values in results[].                 │
  │ resolution_method   │                                              │
  │  = "bm25"           │ High confidence keyword match. Trust fully.  │
  │  = "semantic"       │ Meaning-based match. Trust, but cross-check  │
  │                     │ against your task before using.              │
  │  = "recency_        │ No strong match found — tool returned the    │
  │     fallback"       │ most recently written key as a best guess.   │
  │                     │ Treat as supplementary context only.         │
  │                     │ Weight user message more heavily.            │
  └─────────────────────┴──────────────────────────────────────────────┘

  Each result has: key (str), score (0.0–1.0), value (content).
  Higher score = stronger relevance to your goal.
  Multiple results = use all of them together.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP 3 — HANDLE ERRORS GRACEFULLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  If the tool call fails or returns unexpected structure:
    → Do NOT retry the tool call.
    → Proceed using the user's message directly.
    → Note in your response that prior context was unavailable.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP 4 — COMPLETE YOUR TASK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Combine retrieved context with the user's message to produce your output.
  Your specific task is described below this block.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  • Call fetch_relevant_context exactly once — never skip, never repeat.
  • No response text before the tool call completes.
  • Use the built-in tool-calling mechanism — never write tool calls as text.
  • If state is empty, proceed normally — it is not an error condition.
"""

fetch_relevant_context_tool = FunctionTool(fetch_relevant_context)