# Generated by NeuroStack
# Vendored from platform origin: tool/local_filesystem_tools (upstream_version=platform)

"""Local filesystem tools for Windows-safe direct execution.

These tools avoid MCP stdio subprocess usage and operate inside the repo root only.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List


REPO_ROOT = Path(__file__).resolve().parents[2]


def _resolve_safe_path(relative_path: str) -> Path:
    candidate = (REPO_ROOT / str(relative_path or "")).resolve()
    try:
        candidate.relative_to(REPO_ROOT)
    except Exception:
        raise ValueError("Path escapes repository root")
    return candidate


def list_directory(relative_path: str = ".") -> Dict[str, Any]:
    """List files/folders under a repository-relative directory."""
    try:
        target = _resolve_safe_path(relative_path)
        if not target.exists():
            return {"success": False, "message": f"Path not found: {relative_path}", "data": {}}
        if not target.is_dir():
            return {"success": False, "message": f"Not a directory: {relative_path}", "data": {}}

        children: List[str] = []
        for child in sorted(target.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower())):
            children.append(f"{child.name}/" if child.is_dir() else child.name)

        return {
            "success": True,
            "message": "Directory listed successfully.",
            "data": {
                "path": str(target.relative_to(REPO_ROOT)).replace("\\", "/"),
                "entries": children,
            },
        }
    except Exception as exc:
        return {"success": False, "message": f"List directory failed: {exc}", "data": {}}


def read_text_file(relative_path: str) -> Dict[str, Any]:
    """Read UTF-8 text from a repository-relative file."""
    try:
        target = _resolve_safe_path(relative_path)
        if not target.exists() or not target.is_file():
            return {"success": False, "message": f"File not found: {relative_path}", "data": {}}

        content = target.read_text(encoding="utf-8")
        return {
            "success": True,
            "message": "File read successfully.",
            "data": {
                "path": str(target.relative_to(REPO_ROOT)).replace("\\", "/"),
                "content": content,
            },
        }
    except Exception as exc:
        return {"success": False, "message": f"Read file failed: {exc}", "data": {}}


def write_text_file(relative_path: str, content: str, create_parent_dirs: bool = True) -> Dict[str, Any]:
    """Write UTF-8 text to a repository-relative file."""
    try:
        target = _resolve_safe_path(relative_path)
        if create_parent_dirs:
            target.parent.mkdir(parents=True, exist_ok=True)

        target.write_text(str(content), encoding="utf-8")
        return {
            "success": True,
            "message": "File written successfully.",
            "data": {
                "path": str(target.relative_to(REPO_ROOT)).replace("\\", "/"),
                "bytes": len(str(content).encode("utf-8")),
            },
        }
    except Exception as exc:
        return {"success": False, "message": f"Write file failed: {exc}", "data": {}}


def create_directory(relative_path: str) -> Dict[str, Any]:
    """Create a repository-relative directory recursively."""
    try:
        target = _resolve_safe_path(relative_path)
        target.mkdir(parents=True, exist_ok=True)
        return {
            "success": True,
            "message": "Directory created successfully.",
            "data": {"path": str(target.relative_to(REPO_ROOT)).replace("\\", "/")},
        }
    except Exception as exc:
        return {"success": False, "message": f"Create directory failed: {exc}", "data": {}}
