# Generated by NeuroStack
# Vendored from platform origin: tool/log_normalization_tools (upstream_version=platform)

"""
Log Normalization Tools

Tools for mapping, transforming, and normalizing heterogeneous log events
to a canonical schema. Used by the Normalization Agent.

This module is part of the Security Log Pipeline workflow (demo-only, synthetic data).
"""

import json
import os
import re
import uuid
import ipaddress
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional, Union
from dateutil import parser as dateutil_parser
from dateutil.tz import tzutc



# -----------------------------------------------------------------------------
# Canonical field mappings by profile
# -----------------------------------------------------------------------------

FIELD_MAPPINGS = {
    "network_profile": {
        "source.ip": ["src_ip", "source_ip", "srcip", "ip_src", "sourceIP", "SrcAddr"],
        "source.port": ["src_port", "source_port", "srcport", "sport", "SrcPort"],
        "destination.ip": ["dst_ip", "dest_ip", "dstip", "ip_dst", "destIP", "DstAddr"],
        "destination.port": ["dst_port", "dest_port", "dstport", "dport", "DstPort"],
        "network.transport": ["protocol", "proto", "transport", "Protocol"],
        "network.direction": ["direction", "flow_direction", "dir"],
        "event.action": ["action", "Action", "decision", "verdict"],
        "event.outcome": ["result", "status", "outcome"],
        "observer.name": ["device", "device_name", "firewall", "hostname", "observer"],
        "rule.id": ["rule_id", "ruleId", "rule", "policy_id"],
        "network.bytes": ["bytes", "total_bytes", "byte_count"],
        "source.bytes": ["bytes_in", "in_bytes", "src_bytes"],
        "destination.bytes": ["bytes_out", "out_bytes", "dst_bytes"],
    },
    "endpoint_profile": {
        "event.id": ["EventID", "event_id", "eventId"],
        "process.pid": ["ProcessId", "pid", "process_id"],
        "process.name": ["Image", "process_name", "ProcessName", "exe"],
        "process.command_line": ["CommandLine", "command_line", "cmdline", "cmd"],
        "user.name": ["User", "user", "username", "UserName", "AccountName"],
        "user.domain": ["Domain", "domain", "user_domain"],
        "file.path": ["TargetFilename", "file_path", "FilePath", "path"],
        "host.name": ["Computer", "hostname", "ComputerName", "host"],
        "event.action": ["EventType", "event_type", "action"],
        "registry.path": ["TargetObject", "registry_path", "RegPath"],
        "network.destination.ip": ["DestinationIp", "dest_ip", "remote_ip"],
        "network.destination.port": ["DestinationPort", "dest_port", "remote_port"],
    },
    "identity_profile": {
        "event.type": ["event_type", "EventType", "type", "action_type"],
        "user.name": ["user", "username", "principal", "acct", "account", "UserName"],
        "user.email": ["email", "user_email", "mail", "upn"],
        "user.id": ["user_id", "userId", "uid", "subject_id"],
        "user.domain": ["domain", "tenant", "realm"],
        "event.outcome": ["result", "status", "outcome", "success"],
        "source.ip": ["ip_address", "client_ip", "source_ip", "ipAddress"],
        "source.geo.country": ["country", "geo_country", "location_country"],
        "user_agent.original": ["user_agent", "userAgent", "ua"],
        "authentication.method": ["mfa", "auth_method", "method", "factor"],
        "event.reason": ["failure_reason", "reason", "error", "message"],
    },
    "application_profile": {
        "http.request.id": ["request_id", "requestId", "req_id", "trace_id"],
        "http.request.method": ["method", "http_method", "verb"],
        "url.path": ["path", "url_path", "uri", "endpoint"],
        "http.response.status_code": ["status_code", "statusCode", "status", "response_code"],
        "event.duration": ["latency_ms", "duration_ms", "response_time", "elapsed"],
        "trace.id": ["trace_id", "traceId", "correlation_id", "x_request_id"],
        "span.id": ["span_id", "spanId"],
        "service.name": ["service", "service_name", "app", "application"],
        "user.name": ["user", "username", "user_id"],
        "source.ip": ["client_ip", "remote_ip", "ip"],
        "error.message": ["error", "error_message", "exception"],
    },
    "infrastructure_profile": {
        "log.syslog.facility.code": ["facility", "facility_code"],
        "log.syslog.severity.code": ["severity", "priority", "level"],
        "message": ["message", "msg", "log", "content"],
        "host.name": ["hostname", "host", "server", "machine"],
        "process.name": ["program", "process", "daemon", "service"],
        "process.pid": ["pid", "process_id"],
        "event.action": ["action", "event", "type"],
    },
    "generic_profile": {
        "message": ["message", "msg", "log", "data", "content", "raw"],
        "host.name": ["host", "hostname", "server", "machine", "device"],
        "user.name": ["user", "username", "account"],
        "source.ip": ["ip", "ip_address", "source_ip", "client_ip"],
        "event.action": ["action", "type", "event_type"],
    },
}


def map_to_canonical(event: Dict[str, Any], mapping_profile: str = "generic_profile") -> Dict[str, Any]:
    """
    Map source-specific fields in an event to canonical schema fields.

    Args:
        event (Dict): Source event with original field names.
        mapping_profile (str): Profile name (network_profile, endpoint_profile, etc.)

    Returns:
        Dict with mapped canonical event and transformation details.
    """
    try:
        if not isinstance(event, dict):
            return {
                "success": False,
                "message": "Event must be a dictionary",
                "data": None,
            }

        mappings = FIELD_MAPPINGS.get(mapping_profile, FIELD_MAPPINGS["generic_profile"])
        canonical = {}
        unmapped_fields = {}
        mapping_trace = []

        # Preserve triage metadata if present
        triage_meta = event.pop("_triage", None)

        for canonical_field, source_candidates in mappings.items():
            for candidate in source_candidates:
                # Case-insensitive lookup
                matched_key = next((k for k in event.keys() if k.lower() == candidate.lower()), None)
                if matched_key is not None:
                    value = event[matched_key]
                    _set_nested(canonical, canonical_field, value)
                    mapping_trace.append({
                        "source_field": matched_key,
                        "canonical_field": canonical_field,
                        "value_preview": str(value)[:50] if value is not None else None,
                    })
                    break

        # Collect unmapped fields into custom namespace
        mapped_source_fields = {t["source_field"].lower() for t in mapping_trace}
        for key, value in event.items():
            if key.lower() not in mapped_source_fields and not key.startswith("_"):
                unmapped_fields[key] = value
                _set_nested(canonical, f"custom.{key}", value)

        # Restore triage metadata
        if triage_meta:
            canonical["_triage"] = triage_meta

        return {
            "success": True,
            "message": f"Mapped {len(mapping_trace)} fields using {mapping_profile}",
            "data": {
                "canonical_event": canonical,
                "mapping_profile": mapping_profile,
                "mappings_applied": mapping_trace,
                "unmapped_to_custom": list(unmapped_fields.keys()),
            },
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error mapping to canonical: {str(e)}",
            "data": None,
        }


def _set_nested(d: Dict, key: str, value: Any) -> None:
    """Set a nested key like 'source.ip' in a dict."""
    keys = key.split(".")
    for k in keys[:-1]:
        d = d.setdefault(k, {})
    d[keys[-1]] = value


def _get_nested(d: Dict, key: str, default=None) -> Any:
    """Get a nested key like 'source.ip' from a dict."""
    keys = key.split(".")
    for k in keys:
        if isinstance(d, dict):
            d = d.get(k, default)
        else:
            return default
    return d


def normalize_timestamp(ts_value: Union[str, int, float], default_tz: str = "UTC") -> Dict[str, Any]:
    """
    Normalize a timestamp value to ISO8601 UTC format.

    Args:
        ts_value: Timestamp in various formats (ISO string, epoch seconds/millis, etc.)
        default_tz: Default timezone to assume if none specified.

    Returns:
        Dict with normalized ISO8601 UTC timestamp and parsing details.
    """
    try:
        original_value = ts_value
        parsed_dt = None
        parse_method = None

        if ts_value is None:
            return {
                "success": False,
                "message": "Timestamp value is None",
                "data": None,
            }

        # Handle numeric (epoch)
        if isinstance(ts_value, (int, float)):
            # Detect if seconds or milliseconds
            if ts_value > 1e12:  # Likely milliseconds
                parsed_dt = datetime.fromtimestamp(ts_value / 1000, tz=timezone.utc)
                parse_method = "epoch_milliseconds"
            else:
                parsed_dt = datetime.fromtimestamp(ts_value, tz=timezone.utc)
                parse_method = "epoch_seconds"

        # Handle string
        elif isinstance(ts_value, str):
            ts_value = ts_value.strip()

            # Check for empty/null-ish
            if not ts_value or ts_value.lower() in ["null", "none", "n/a", "-", ""]:
                return {
                    "success": False,
                    "message": f"Empty or null-ish timestamp: {original_value}",
                    "data": None,
                }

            # Try parsing as numeric string first
            try:
                numeric_ts = float(ts_value)
                if numeric_ts > 1e12:
                    parsed_dt = datetime.fromtimestamp(numeric_ts / 1000, tz=timezone.utc)
                    parse_method = "epoch_milliseconds_string"
                else:
                    parsed_dt = datetime.fromtimestamp(numeric_ts, tz=timezone.utc)
                    parse_method = "epoch_seconds_string"
            except ValueError:
                # Try dateutil parser
                try:
                    parsed_dt = dateutil_parser.parse(ts_value)
                    parse_method = "dateutil_parser"

                    # If no timezone, assume default
                    if parsed_dt.tzinfo is None:
                        if default_tz.upper() == "UTC":
                            parsed_dt = parsed_dt.replace(tzinfo=timezone.utc)
                        else:
                            # For demo, just assume UTC
                            parsed_dt = parsed_dt.replace(tzinfo=timezone.utc)
                    else:
                        # Convert to UTC
                        parsed_dt = parsed_dt.astimezone(timezone.utc)

                except Exception as parse_err:
                    return {
                        "success": False,
                        "message": f"Failed to parse timestamp: {str(parse_err)}",
                        "data": {"original_value": str(original_value)[:100]},
                    }
        else:
            return {
                "success": False,
                "message": f"Unsupported timestamp type: {type(ts_value).__name__}",
                "data": None,
            }

        # Format to ISO8601 UTC
        normalized = parsed_dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"

        return {
            "success": True,
            "message": "Timestamp normalized successfully",
            "data": {
                "original": str(original_value),
                "normalized": normalized,
                "parse_method": parse_method,
                "timezone": "UTC",
            },
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error normalizing timestamp: {str(e)}",
            "data": {"original_value": str(ts_value)[:100]},
        }


def normalize_identity(identity_fields: Dict[str, Any]) -> Dict[str, Any]:
    """
    Normalize identity-related fields (user, username, principal, email) to canonical format.

    Args:
        identity_fields (Dict): Dictionary containing identity-related fields.

    Returns:
        Dict with normalized identity structure.
    """
    try:
        normalized = {
            "user": {
                "name": None,
                "email": None,
                "id": None,
                "domain": None,
            }
        }
        transformations = []

        # Extract user name from various fields
        name_candidates = ["user", "username", "principal", "acct", "account", "user_name", "UserName", "AccountName"]
        for candidate in name_candidates:
            if candidate in identity_fields and identity_fields[candidate]:
                raw_name = str(identity_fields[candidate]).strip()
                # Handle domain\user format
                if "\\" in raw_name:
                    parts = raw_name.split("\\", 1)
                    normalized["user"]["domain"] = parts[0]
                    normalized["user"]["name"] = parts[1]
                    transformations.append({"source": candidate, "transform": "split_domain_user"})
                # Handle user@domain format
                elif "@" in raw_name and "." in raw_name.split("@")[-1]:
                    normalized["user"]["email"] = raw_name.lower()
                    normalized["user"]["name"] = raw_name.split("@")[0]
                    normalized["user"]["domain"] = raw_name.split("@")[1]
                    transformations.append({"source": candidate, "transform": "extract_from_email"})
                else:
                    normalized["user"]["name"] = raw_name.lower()
                    transformations.append({"source": candidate, "transform": "lowercase"})
                break

        # Extract email
        email_candidates = ["email", "user_email", "mail", "upn", "userPrincipalName"]
        for candidate in email_candidates:
            if candidate in identity_fields and identity_fields[candidate]:
                email = str(identity_fields[candidate]).strip().lower()
                if "@" in email:
                    normalized["user"]["email"] = email
                    if not normalized["user"]["name"]:
                        normalized["user"]["name"] = email.split("@")[0]
                    if not normalized["user"]["domain"]:
                        normalized["user"]["domain"] = email.split("@")[1]
                    transformations.append({"source": candidate, "transform": "email_normalization"})
                break

        # Extract user ID
        id_candidates = ["user_id", "userId", "uid", "subject_id", "sid"]
        for candidate in id_candidates:
            if candidate in identity_fields and identity_fields[candidate]:
                normalized["user"]["id"] = str(identity_fields[candidate])
                transformations.append({"source": candidate, "transform": "direct_copy"})
                break

        # Extract domain
        domain_candidates = ["domain", "tenant", "realm", "user_domain"]
        for candidate in domain_candidates:
            if candidate in identity_fields and identity_fields[candidate] and not normalized["user"]["domain"]:
                normalized["user"]["domain"] = str(identity_fields[candidate]).lower()
                transformations.append({"source": candidate, "transform": "lowercase"})
                break

        return {
            "success": True,
            "message": f"Normalized identity with {len(transformations)} transformations",
            "data": {
                "normalized_identity": normalized,
                "transformations": transformations,
            },
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error normalizing identity: {str(e)}",
            "data": None,
        }


def normalize_network_fields(net_fields: Dict[str, Any]) -> Dict[str, Any]:
    """
    Normalize network-related fields (IPs, ports, protocols) to canonical format.

    Args:
        net_fields (Dict): Dictionary containing network-related fields.

    Returns:
        Dict with normalized network structure.
    """
    try:
        normalized = {
            "source": {"ip": None, "port": None},
            "destination": {"ip": None, "port": None, "host": None},
            "network": {"transport": None, "direction": None, "bytes": None},
            "classification": {"is_internal_src": None, "is_internal_dst": None},
        }
        transformations = []
        warnings = []

        # Source IP
        src_ip_candidates = ["src_ip", "source_ip", "srcip", "ip_src", "sourceIP", "SrcAddr", "client_ip"]
        for candidate in src_ip_candidates:
            if candidate in net_fields and net_fields[candidate]:
                ip = str(net_fields[candidate]).strip()
                if _is_valid_ip(ip):
                    normalized["source"]["ip"] = ip
                    normalized["classification"]["is_internal_src"] = _is_internal_ip(ip)
                    transformations.append({"field": "source.ip", "source": candidate})
                    break
                warnings.append({
                    "field": candidate,
                    "issue": "invalid_src_ip",
                    "value_preview": ip[:80],
                })

        # Source port
        src_port_candidates = ["src_port", "source_port", "srcport", "sport", "SrcPort"]
        for candidate in src_port_candidates:
            if candidate in net_fields and net_fields[candidate]:
                raw_port = net_fields[candidate]
                port = _parse_port(raw_port)
                if port is not None:
                    normalized["source"]["port"] = port
                    transformations.append({"field": "source.port", "source": candidate})
                    break
                warnings.append({
                    "field": candidate,
                    "issue": "invalid_src_port",
                    "value_preview": str(raw_port)[:40],
                })

        # Destination IP
        dst_ip_candidates = ["dst_ip", "dest_ip", "dstip", "ip_dst", "destIP", "DstAddr", "destination_ip"]
        for candidate in dst_ip_candidates:
            if candidate in net_fields and net_fields[candidate]:
                dst_value = str(net_fields[candidate]).strip()
                if _is_valid_ip(dst_value):
                    normalized["destination"]["ip"] = dst_value
                    normalized["classification"]["is_internal_dst"] = _is_internal_ip(dst_value)
                    transformations.append({"field": "destination.ip", "source": candidate})
                    break
                # For firewall logs, destination can be a hostname/domain.
                normalized["destination"]["host"] = dst_value
                normalized["classification"]["is_internal_dst"] = None
                transformations.append({"field": "destination.host", "source": candidate, "reason": "non_ip_destination"})
                warnings.append({
                    "field": candidate,
                    "issue": "dst_ip_not_ip_promoted_to_destination_host",
                    "value_preview": dst_value[:100],
                })
                break

        # Destination port
        dst_port_candidates = ["dst_port", "dest_port", "dstport", "dport", "DstPort"]
        for candidate in dst_port_candidates:
            if candidate in net_fields and net_fields[candidate]:
                raw_port = net_fields[candidate]
                port = _parse_port(raw_port)
                if port is not None:
                    normalized["destination"]["port"] = port
                    transformations.append({"field": "destination.port", "source": candidate})
                    break
                warnings.append({
                    "field": candidate,
                    "issue": "invalid_dst_port",
                    "value_preview": str(raw_port)[:40],
                })

        # Protocol/Transport
        proto_candidates = ["protocol", "proto", "transport", "Protocol"]
        for candidate in proto_candidates:
            if candidate in net_fields and net_fields[candidate]:
                proto = str(net_fields[candidate]).lower()
                # Normalize common values
                proto_map = {"6": "tcp", "17": "udp", "1": "icmp", "tcp": "tcp", "udp": "udp", "icmp": "icmp"}
                normalized["network"]["transport"] = proto_map.get(proto, proto)
                transformations.append({"field": "network.transport", "source": candidate})
                break

        # Direction
        dir_candidates = ["direction", "flow_direction", "dir"]
        for candidate in dir_candidates:
            if candidate in net_fields and net_fields[candidate]:
                direction = str(net_fields[candidate]).lower()
                dir_map = {"in": "inbound", "out": "outbound", "inbound": "inbound", "outbound": "outbound",
                           "ingress": "inbound", "egress": "outbound"}
                normalized["network"]["direction"] = dir_map.get(direction, direction)
                transformations.append({"field": "network.direction", "source": candidate})
                break

        return {
            "success": True,
            "message": f"Normalized {len(transformations)} network fields",
            "data": {
                "normalized_network": normalized,
                "transformations": transformations,
                "warnings": warnings,
            },
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error normalizing network fields: {str(e)}",
            "data": None,
        }


def _is_valid_ip(ip: str) -> bool:
    """IP address validation using stdlib parser."""
    try:
        ipaddress.ip_address(str(ip).strip())
        return True
    except ValueError:
        return False


def _is_internal_ip(ip: str) -> bool:
    """Classify private/internal addresses."""
    try:
        parsed = ipaddress.ip_address(str(ip).strip())
        return bool(parsed.is_private or parsed.is_loopback or parsed.is_link_local)
    except ValueError:
        return False


def _parse_port(value: Any) -> Optional[int]:
    """Parse port number from various formats."""
    try:
        raw = str(value).strip().strip('"').strip("'")
        port = int(float(raw))
        if 0 <= port <= 65535:
            return port
    except (ValueError, TypeError):
        pass
    return None


def handle_schema_drift(event: Dict[str, Any], drift_policy: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Handle schema drift by applying a policy for unknown/new fields.

    Args:
        event (Dict): Event that may contain unexpected fields.
        drift_policy (Dict, optional): Policy for handling drift. Keys:
            - unknown_fields: "drop" | "park_under_custom" | "preserve"
            - type_coercion: True/False
            - null_handling: "drop" | "preserve" | "empty_string"

    Returns:
        Dict with processed event and drift handling details.
    """
    try:
        # Default policy
        policy = {
            "unknown_fields": "park_under_custom",
            "type_coercion": True,
            "null_handling": "preserve",
        }
        if drift_policy:
            policy.update(drift_policy)

        processed = {}
        drift_actions = []
        known_canonical_prefixes = ["event", "source", "destination", "user", "host", "network",
                                     "process", "file", "http", "url", "log", "@timestamp", "pipeline", "_triage"]

        for key, value in event.items():
            # Check if this is a known canonical field
            is_known = any(key.startswith(prefix) or key == prefix for prefix in known_canonical_prefixes)

            # Handle null values
            if value is None:
                if policy["null_handling"] == "drop":
                    drift_actions.append({"field": key, "action": "dropped_null"})
                    continue
                elif policy["null_handling"] == "empty_string":
                    value = ""
                    drift_actions.append({"field": key, "action": "null_to_empty"})

            # Type coercion
            if policy["type_coercion"] and isinstance(value, str):
                # Try to coerce to appropriate type
                coerced, coercion_type = _try_type_coercion(value)
                if coercion_type:
                    value = coerced
                    drift_actions.append({"field": key, "action": f"coerced_to_{coercion_type}"})

            # Handle unknown fields
            if not is_known and not key.startswith("custom.") and not key.startswith("_"):
                if policy["unknown_fields"] == "drop":
                    drift_actions.append({"field": key, "action": "dropped_unknown"})
                    continue
                elif policy["unknown_fields"] == "park_under_custom":
                    new_key = f"custom.{key}"
                    processed[new_key] = value
                    drift_actions.append({"field": key, "action": "parked_under_custom", "new_key": new_key})
                    continue

            processed[key] = value

        return {
            "success": True,
            "message": f"Handled schema drift with {len(drift_actions)} actions",
            "data": {
                "processed_event": processed,
                "drift_actions": drift_actions,
                "policy_applied": policy,
            },
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error handling schema drift: {str(e)}",
            "data": None,
        }


def _try_type_coercion(value: str) -> tuple:
    """Try to coerce a string to a more appropriate type."""
    v = value.strip()

    # Boolean
    if v.lower() in ["true", "false"]:
        return v.lower() == "true", "boolean"

    # Integer
    if v.isdigit() or (v.startswith("-") and v[1:].isdigit()):
        return int(v), "integer"

    # Float
    try:
        if "." in v:
            return float(v), "float"
    except ValueError:
        pass

    # Keep as string
    return value, None


def write_normalized_events(events: List[Dict[str, Any]], out_path: str, run_id: Optional[str] = None) -> Dict[str, Any]:
    """
    Write normalized events to a JSONL file with pipeline metadata.

    Args:
        events (List[Dict]): List of normalized events to write.
        out_path (str): Output file path (will create parent dirs if needed).
        run_id (str, optional): Pipeline run ID to attach to events.

    Returns:
        Dict with write status, counts, and output path.
    """
    try:
        if not events:
            return {
                "success": False,
                "message": "No events to write",
                "data": None,
            }
            
        # DEMO MODE: Limit to exactly 5 events to prevent context overflow for smaller LLMs
        events = events[:5]

        out_file = Path(out_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)

        run_id = run_id or str(uuid.uuid4())
        written_count = 0
        errors = []

        with open(out_file, "w", encoding="utf-8") as f:
            for i, event in enumerate(events):
                try:
                    # Add normalization pipeline metadata
                    if "pipeline" not in event:
                        event["pipeline"] = {}
                    event["pipeline"]["run_id"] = run_id
                    event["pipeline"]["stage"] = "normalized"
                    event["pipeline"]["normalized_at"] = datetime.utcnow().isoformat() + "Z"

                    if "lineage" not in event["pipeline"]:
                        event["pipeline"]["lineage"] = []
                    event["pipeline"]["lineage"].append({
                        "stage": "normalization",
                        "timestamp": datetime.utcnow().isoformat() + "Z",
                        "tool": "write_normalized_events",
                    })

                    f.write(json.dumps(event, default=str) + "\n")
                    written_count += 1
                except Exception as write_err:
                    errors.append({"index": i, "error": str(write_err)})

        return {
            "success": True,
            "message": f"Wrote {written_count} normalized events to {out_path}",
            "data": {
                "output_path": str(out_file.absolute()),
                "run_id": run_id,
                "events_written": written_count,
                "errors": errors[:10],
            },
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error writing normalized events: {str(e)}",
            "data": None,
        }

def process_normalization_batch(input_path: str, mapping_profile: str, out_path: str) -> Dict[str, Any]:
    """
    Reads a triaged JSONL file, normalizes all events using the mapping profile,
    and writes them to an output JSONL file in one batch.
    """
    try:
        in_file = Path(input_path)
        if not in_file.exists():
            return {"success": False, "message": f"Input file not found: {input_path}", "data": None}
            
        out_file = Path(out_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)
        
        events = []
        with open(in_file, "r", encoding="utf-8") as f:
            for i, line in enumerate(f):
                if line.strip():
                    events.append(json.loads(line))
                # DEMO MODE: Limit to exactly 5 events
                if i >= 4:
                    break
                    
        normalized_events = []
        for event in events:
            # Basic map
            res = map_to_canonical(event, mapping_profile)
            if res.get("success"):
                norm_ev = res["data"]["canonical_event"]
                # Quick timestamp normalize
                if "@timestamp" in norm_ev:
                    ts_res = normalize_timestamp(norm_ev["@timestamp"])
                    if ts_res.get("success"):
                        norm_ev["@timestamp"] = ts_res["data"]["normalized"]
                normalized_events.append(norm_ev)
                
        # Write
        return write_normalized_events(normalized_events, out_path)
    except Exception as e:
        return {"success": False, "message": str(e), "data": None}
