# Generated by NeuroStack
# Vendored from platform origin: tool/threat_hunting_baseline_tools (upstream_version=platform)

"""
Threat Hunting Baseline Tools (Demo-only, local-only).

Compute simple baseline features for a seed entity and detect deviations in a hunt window.
Designed for clarity and explainability (2–4 flags max).
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .threat_hunting_data_tools import _get_nested, _parse_ts, read_events, load_threat_hunting_dataset


def _hour_bucket(ts: str) -> str:
    dt = _parse_ts(ts)
    return f"{dt.hour:02d}"


def _top_n(counter: Counter, n: int) -> List[Dict[str, Any]]:
    return [{"key": k, "count": v} for k, v in counter.most_common(n)]


def _safe_mean(values: List[int]) -> float:
    return sum(values) / len(values) if values else 0.0


def _safe_std(values: List[int]) -> float:
    if len(values) < 2:
        return 0.0
    mu = _safe_mean(values)
    var = sum((x - mu) ** 2 for x in values) / (len(values) - 1)
    return var ** 0.5


def compute_baseline_features(
    entity_username: str,
    history_start_ts: str,
    history_end_ts: str,
    dataset_root: str = "data/threat_hunting_demo",
) -> Dict[str, Any]:
    """
    Compute baseline features for an entity from auth and cloud audit events.
    """
    try:
        ds = load_threat_hunting_dataset(dataset_root)
        if not ds["success"]:
            return ds
        tables = ds["data"]["tables"]
        auth_path = tables.get("auth_events") or str(Path(dataset_root) / "canonical" / "auth_events.jsonl")
        cloud_path = tables.get("cloud_audit_events") or str(Path(dataset_root) / "canonical" / "cloud_audit_events.jsonl")

        auth = read_events(auth_path, history_start_ts, history_end_ts, {"user.name": entity_username}, limit=100000)
        cloud = read_events(cloud_path, history_start_ts, history_end_ts, {"user.name": entity_username}, limit=100000)

        auth_events = auth.get("data", {}).get("events", []) if auth.get("success") else []
        cloud_events = cloud.get("data", {}).get("events", []) if cloud.get("success") else []

        hours = Counter()
        hosts = Counter()
        methods = Counter()
        regions = Counter()

        for e in auth_events:
            ts = e.get("@timestamp")
            if ts:
                hours[_hour_bucket(ts)] += 1
            h = _get_nested(e, "host.name")
            if h:
                hosts[str(h).lower()] += 1
            m = _get_nested(e, "authentication.method")
            if m:
                methods[str(m).lower()] += 1

        for e in cloud_events:
            r = _get_nested(e, "cloud.region")
            if r:
                regions[str(r).lower()] += 1

        # Daily auth counts (for spike detection)
        per_day = Counter()
        for e in auth_events:
            ts = e.get("@timestamp")
            if not ts:
                continue
            dt = _parse_ts(ts)
            per_day[dt.date().isoformat()] += 1
        daily_counts = [per_day[d] for d in sorted(per_day.keys())]

        return {
            "success": True,
            "message": "Computed baseline features",
            "data": {
                "entity": entity_username,
                "window": {"start_ts": history_start_ts, "end_ts": history_end_ts},
                "features": {
                    "login_hours_top": _top_n(hours, 3),
                    "hosts_top": _top_n(hosts, 5),
                    "auth_methods_top": _top_n(methods, 3),
                    "cloud_regions_top": _top_n(regions, 3),
                    "daily_auth_counts": daily_counts,
                    "daily_auth_mean": round(_safe_mean(daily_counts), 2),
                    "daily_auth_std": round(_safe_std(daily_counts), 2),
                    "unique_hosts": len(hosts),
                },
                "evidence": {
                    "auth": auth.get("data", {}).get("evidence", []),
                    "cloud": cloud.get("data", {}).get("evidence", []),
                },
            },
        }
    except Exception as e:
        return {"success": False, "message": f"Error computing baseline features: {e}", "data": None}


def compute_recent_features(
    entity_username: str,
    start_ts: str,
    end_ts: str,
    dataset_root: str = "data/threat_hunting_demo",
) -> Dict[str, Any]:
    """
    Compute recent-window features (last 24h by default in the workflow request).
    """
    try:
        ds = load_threat_hunting_dataset(dataset_root)
        if not ds["success"]:
            return ds
        tables = ds["data"]["tables"]
        auth_path = tables.get("auth_events") or str(Path(dataset_root) / "canonical" / "auth_events.jsonl")
        cloud_path = tables.get("cloud_audit_events") or str(Path(dataset_root) / "canonical" / "cloud_audit_events.jsonl")

        auth = read_events(auth_path, start_ts, end_ts, {"user.name": entity_username}, limit=100000)
        cloud = read_events(cloud_path, start_ts, end_ts, {"user.name": entity_username}, limit=100000)

        auth_events = auth.get("data", {}).get("events", []) if auth.get("success") else []
        cloud_events = cloud.get("data", {}).get("events", []) if cloud.get("success") else []

        hours = Counter()
        hosts = Counter()
        methods = Counter()
        regions = Counter()

        for e in auth_events:
            ts = e.get("@timestamp")
            if ts:
                hours[_hour_bucket(ts)] += 1
            h = _get_nested(e, "host.name")
            if h:
                hosts[str(h).lower()] += 1
            m = _get_nested(e, "authentication.method")
            if m:
                methods[str(m).lower()] += 1

        for e in cloud_events:
            r = _get_nested(e, "cloud.region")
            if r:
                regions[str(r).lower()] += 1

        return {
            "success": True,
            "message": "Computed recent features",
            "data": {
                "entity": entity_username,
                "window": {"start_ts": start_ts, "end_ts": end_ts},
                "features": {
                    "login_hours_top": _top_n(hours, 6),
                    "hosts_top": _top_n(hosts, 10),
                    "auth_methods_top": _top_n(methods, 5),
                    "cloud_regions_top": _top_n(regions, 5),
                    "auth_event_count": len(auth_events),
                    "unique_hosts": len(hosts),
                },
                "evidence": {
                    "auth": auth.get("data", {}).get("evidence", []),
                    "cloud": cloud.get("data", {}).get("evidence", []),
                },
            },
        }
    except Exception as e:
        return {"success": False, "message": f"Error computing recent features: {e}", "data": None}


def _flag(flag_type: str, why: str, evidence: List[Dict[str, Any]], confidence: str) -> Dict[str, Any]:
    return {
        "flag_type": flag_type,
        "why": why,
        "confidence": confidence,
        "evidence": evidence[:5],  # keep tight for demo
    }


def detect_deviations(
    baseline: Dict[str, Any],
    recent: Dict[str, Any],
    policy: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Compare recent activity against baseline and output 2–4 deviations max.
    """
    try:
        policy = policy or {}
        max_flags = int(policy.get("max_flags", 4))
        min_flags = int(policy.get("min_flags", 2))

        base_f = baseline.get("data", {}).get("features", {})
        recent_f = recent.get("data", {}).get("features", {})

        base_hosts = {x["key"] for x in base_f.get("hosts_top", [])}
        recent_hosts = {x["key"] for x in recent_f.get("hosts_top", [])}
        new_hosts = sorted(list(recent_hosts - base_hosts))

        base_hours = {x["key"] for x in base_f.get("login_hours_top", [])}
        recent_hours = {x["key"] for x in recent_f.get("login_hours_top", [])}
        abnormal_hours = sorted(list(recent_hours - base_hours))

        base_methods = {x["key"] for x in base_f.get("auth_methods_top", [])}
        recent_methods = {x["key"] for x in recent_f.get("auth_methods_top", [])}
        new_methods = sorted(list(recent_methods - base_methods))

        flags: List[Dict[str, Any]] = []

        # Evidence (use the recent auth evidence pointers primarily)
        recent_auth_evidence = recent.get("data", {}).get("evidence", {}).get("auth", [])

        if new_hosts:
            flags.append(
                _flag(
                    "NEW_HOST",
                    f"Observed login activity from host(s) not present in baseline top hosts: {', '.join(new_hosts[:3])}.",
                    recent_auth_evidence,
                    "high",
                )
            )

        if abnormal_hours:
            flags.append(
                _flag(
                    "ABNORMAL_TIME",
                    f"Observed login hour bucket(s) outside baseline norms: {', '.join(abnormal_hours[:4])} UTC.",
                    recent_auth_evidence,
                    "medium",
                )
            )

        if new_methods:
            flags.append(
                _flag(
                    "NEW_AUTH_METHOD",
                    f"Observed authentication method(s) not seen in baseline: {', '.join(new_methods[:3])}.",
                    recent_auth_evidence,
                    "medium",
                )
            )

        # Spike (simple): recent auth count > baseline mean + 2*std * (window_days factor)
        mean = float(base_f.get("daily_auth_mean", 0))
        std = float(base_f.get("daily_auth_std", 0))
        recent_count = int(recent_f.get("auth_event_count", 0))
        threshold = mean + 2 * std
        if std == 0 and mean > 0:
            threshold = mean * 2.5
        if recent_count > max(3, int(threshold)):
            flags.append(
                _flag(
                    "AUTH_SPIKE",
                    f"Authentication volume in the window ({recent_count}) exceeds baseline expectation (≈{mean}+2σ).",
                    recent_auth_evidence,
                    "low",
                )
            )

        # Enforce demo constraints: 2–4 flags max, stable ordering
        preferred_order = ["NEW_HOST", "ABNORMAL_TIME", "NEW_AUTH_METHOD", "AUTH_SPIKE"]
        flags.sort(key=lambda f: preferred_order.index(f["flag_type"]) if f["flag_type"] in preferred_order else 999)

        if len(flags) > max_flags:
            flags = flags[:max_flags]

        # If we have too few flags, that's ok for real life, but demo requires 2.
        # Pad with an analyst-style "no further deviation detected" is not helpful; instead allow <2.
        if len(flags) < min_flags:
            # Keep behavior honest: do NOT fabricate flags.
            pass

        return {
            "success": True,
            "message": f"Detected {len(flags)} deviation flag(s)",
            "data": {"flags": flags, "constraints": {"max_flags": max_flags, "min_flags": min_flags}},
        }
    except Exception as e:
        return {"success": False, "message": f"Error detecting deviations: {e}", "data": None}

