# Generated by NeuroStack
# Vendored from platform origin: tool/threat_hunting_data_tools (upstream_version=platform)

"""
Threat Hunting Data Tools (Demo-only, local-only, synthetic-only).

These tools provide:
- dataset loading/validation (manifest + canonical tables + reference data)
- entity resolution for a seed entity (e.g., service account)
- local JSONL table scans with simple filters and time-window constraints
- deterministic synthetic dataset generation (for demos)

No external network calls. All reads/writes are under the local repository dataset directory.
"""

from __future__ import annotations

import json
import random
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple



DEFAULT_DATASET_ROOT = "data/threat_hunting_demo"
SCHEMA_VERSION = "1.0"


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _isoformat_z(dt: datetime) -> str:
    dt = dt.astimezone(timezone.utc)
    return dt.isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _parse_ts(ts: str) -> datetime:
    """
    Parse a timestamp that may be ISO-8601 ("...Z"/"+00:00"), Unix epoch seconds
    (as seen in the hc_security_demo enriched dataset), or "MM/DD/YYYY hh:mm:ss AM/PM".
    """
    s = str(ts).strip()
    if s.isdigit():
        return datetime.fromtimestamp(int(s), tz=timezone.utc)
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        return datetime.fromisoformat(s).astimezone(timezone.utc)
    except ValueError:
        return datetime.strptime(s, "%m/%d/%Y %I:%M:%S %p").replace(tzinfo=timezone.utc)


def _get_nested(d: Dict[str, Any], path: str, default: Any = None) -> Any:
    cur: Any = d
    for part in path.split("."):
        if not isinstance(cur, dict):
            return default
        cur = cur.get(part, default)
    return cur


def _set_nested(d: Dict[str, Any], path: str, value: Any) -> None:
    cur: Dict[str, Any] = d
    parts = path.split(".")
    for part in parts[:-1]:
        nxt = cur.get(part)
        if not isinstance(nxt, dict):
            nxt = {}
            cur[part] = nxt
        cur = nxt
    cur[parts[-1]] = value


def _is_within_window(event_ts: str, start_ts: str, end_ts: str) -> bool:
    try:
        dt = _parse_ts(event_ts)
    except Exception:
        return False
    return _parse_ts(start_ts) <= dt <= _parse_ts(end_ts)


def _match_filters(event: Dict[str, Any], filters: Optional[Dict[str, Any]]) -> bool:
    if not filters:
        return True
    for key, expected in filters.items():
        actual = _get_nested(event, key, None)
        if isinstance(expected, dict):
            # Minimal operators for demo:
            # {"in": [...]}, {"neq": value}, {"contains": "substr"}
            if "in" in expected:
                if actual not in expected["in"]:
                    return False
            elif "neq" in expected:
                if actual == expected["neq"]:
                    return False
            elif "contains" in expected:
                if actual is None:
                    return False
                if str(expected["contains"]) not in str(actual):
                    return False
            else:
                return False
        else:
            if actual != expected:
                return False
    return True


def _read_json(path: Path) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, sort_keys=False)


def _write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, default=str) + "\n")
            n += 1
    return n


def _stable_event_id(namespace: uuid.UUID, *parts: str) -> str:
    joined = "|".join(parts)
    return f"evt-{uuid.uuid5(namespace, joined)}"


_ENRICHED_NS = uuid.UUID("6f2c9b0a-1d3e-4a5b-9c6d-7e8f9a0b1c2d")


def _normalize_enriched_event(evt: Dict[str, Any], line_no: int, table_path: str) -> Dict[str, Any]:
    """
    Adapt an hc_security_demo enriched-pipeline event (source/event/custom/_triage/pipeline/threat)
    onto the ECS-style fields the rest of the threat-hunting tools key off of
    (@timestamp, event.id/category/action, user.name, host.name, source.ip).

    Only triggered when the raw event lacks the ECS fields already (see read_events),
    so canonical threat_hunting_demo events pass through unchanged.
    """
    normalized = dict(evt)
    event_time = _get_nested(evt, "custom.event_time")
    if event_time and not evt.get("@timestamp"):
        try:
            normalized["@timestamp"] = _isoformat_z(_parse_ts(event_time))
        except Exception:
            pass

    action = _get_nested(evt, "event.action")
    if action:
        _set_nested(normalized, "event.category", _get_nested(evt, "event.category") or "enriched")
        _set_nested(normalized, "event.outcome", _get_nested(evt, "event.outcome") or "unknown")

    if not _get_nested(evt, "event.id"):
        eid = _get_nested(evt, "_triage.record_id") or _stable_event_id(
            _ENRICHED_NS, table_path, str(line_no)
        )
        _set_nested(normalized, "event.id", eid)

    dest_host = _get_nested(evt, "custom.dest_host")
    if dest_host and not _get_nested(evt, "host.name"):
        _set_nested(normalized, "host.name", dest_host)

    # This dataset has no user.name field — the natural entity key is source.ip.
    # Mirror it onto user.name so existing {"user.name": entity} filters keep working
    # when the seed entity (from resolve_entity) is an IP.
    src_ip = _get_nested(evt, "source.ip")
    if src_ip and not _get_nested(evt, "user.name"):
        _set_nested(normalized, "user.name", src_ip)

    return normalized


_ENRICHED_TABLE_NAMES = (
    "auth_events",
    "process_events",
    "network_events",
    "dns_events",
    "cloud_audit_events",
)


def _load_enriched_dataset_without_manifest(dataset_root: str) -> Optional[Dict[str, Any]]:
    """
    Fallback for datasets that don't ship a manifest.json (e.g. data/hc_security_demo/enriched):
    - If dataset_root points directly at a .jsonl file, use that single file as every event table.
    - If dataset_root is a directory, use the first .jsonl file found (or a caller-specified one
      via the ".jsonl"-suffixed dataset_root) as every event table.

    All events live in one flat file in this dataset, so every canonical table name is pointed
    at the same file; read_events/filters narrow down what's actually relevant per query.
    """
    root = Path(dataset_root)

    if root.is_file() and root.suffix == ".jsonl":
        jsonl_path = root
    elif root.is_dir():
        candidates = sorted(root.glob("*.jsonl"))
        if not candidates:
            return None
        jsonl_path = candidates[0]
    else:
        return None

    resolved_tables = {name: str(jsonl_path) for name in _ENRICHED_TABLE_NAMES}
    return {
        "success": True,
        "message": f"Dataset loaded (no manifest.json; using {jsonl_path.name} as the event source)",
        "data": {
            "dataset_root": str(jsonl_path.parent),
            "manifest": {"dataset_name": jsonl_path.parent.name, "source_file": str(jsonl_path)},
            "tables": resolved_tables,
            "references": {},
            "missing": [],
        },
    }


def load_threat_hunting_dataset(dataset_root: str = DEFAULT_DATASET_ROOT) -> Dict[str, Any]:
    """
    Load and validate the threat hunting demo dataset manifest and expected file layout.

    Also supports manifest-less datasets (e.g. data/hc_security_demo/enriched) by pointing
    `dataset_root` at either the folder or a specific .jsonl file inside it.
    """
    try:
        root = Path(dataset_root)
        manifest_path = root / "manifest.json" if root.is_dir() else None
        if not manifest_path or not manifest_path.exists():
            fallback = _load_enriched_dataset_without_manifest(dataset_root)
            if fallback is not None:
                return fallback
            return {
                "success": False,
                "message": f"Dataset manifest not found: {manifest_path or root}",
                "data": {"dataset_root": str(root)},
            }

        manifest = _read_json(manifest_path)

        # Resolve table paths from manifest (preferred) but also validate defaults.
        tables = manifest.get("tables", {})
        missing: List[str] = []
        resolved_tables: Dict[str, str] = {}
        for name, rel_path in tables.items():
            p = root / rel_path
            resolved_tables[name] = str(p)
            if not p.exists():
                missing.append(rel_path)

        references = manifest.get("references", {})
        resolved_refs: Dict[str, str] = {}
        for name, rel_path in references.items():
            p = root / rel_path
            resolved_refs[name] = str(p)
            if not p.exists():
                missing.append(rel_path)

        return {
            "success": len(missing) == 0,
            "message": "Dataset loaded" if not missing else f"Dataset loaded with missing files: {missing}",
            "data": {
                "dataset_root": str(root),
                "manifest": manifest,
                "tables": resolved_tables,
                "references": resolved_refs,
                "missing": missing,
            },
        }
    except Exception as e:
        return {"success": False, "message": f"Error loading dataset: {e}", "data": None}


def resolve_entity(seed: str, dataset_root: str = DEFAULT_DATASET_ROOT) -> Dict[str, Any]:
    """
    Resolve a seed entity (e.g., svc_backup1) to a canonical entity_id and profile.
    """
    try:
        root = Path(dataset_root)
        ref_dir = root / "reference"
        er_path = ref_dir / "entity_resolution.json"
        identities_path = ref_dir / "identities.json"
        allowlists_path = ref_dir / "allowlists.json"

        if not er_path.exists():
            # Datasets without reference data (e.g. data/hc_security_demo/enriched) have no
            # entity_resolution.json — treat the seed itself (typically an IP: source.ip) as
            # the entity_id since that dataset has no user.name field to resolve against.
            return {
                "success": True,
                "message": f"No entity_resolution.json found under {ref_dir}; using seed '{seed}' as entity_id directly.",
                "data": {
                    "seed": seed,
                    "entity_id": seed.strip(),
                    "entity_type": "unknown",
                    "profile": {},
                },
            }

        entity_resolution = _read_json(er_path)
        identities = _read_json(identities_path) if identities_path.exists() else {}
        allowlists = _read_json(allowlists_path) if allowlists_path.exists() else {}

        seed_norm = seed.strip().lower()
        entry = entity_resolution.get(seed_norm) or entity_resolution.get(seed)  # allow exact key too
        if not entry:
            return {
                "success": False,
                "message": f"Seed entity not found in entity_resolution: {seed}",
                "data": {"seed": seed, "known_seeds": sorted(list(entity_resolution.keys()))[:50]},
            }

        entity_id = entry.get("entity_id") or seed_norm
        entity_type = entry.get("entity_type", "unknown")
        identity_profile = identities.get(seed_norm) or identities.get(entity_id) or {}
        allow = allowlists.get(seed_norm) or allowlists.get(entity_id) or {}

        return {
            "success": True,
            "message": f"Resolved seed '{seed}' to entity_id '{entity_id}'",
            "data": {
                "seed": seed,
                "entity_id": entity_id,
                "entity_type": entity_type,
                "profile": {
                    **identity_profile,
                    "allowlists": allow,
                },
            },
        }
    except Exception as e:
        return {"success": False, "message": f"Error resolving entity: {e}", "data": None}


def read_events(
    table_path: str,
    start_ts: str,
    end_ts: str,
    filters: Optional[Dict[str, Any]] = None,
    limit: int = 5000,
) -> Dict[str, Any]:
    """
    Scan a local JSONL canonical table and return events in the time window that match filters.

    Filters are dot-paths into the JSON event (e.g., {"user.name": "svc_backup1"}).

    The default limit is 5000 — high enough that an omitted `limit` does not
    silently truncate an investigation window. Callers that want a small sample
    must pass `limit` explicitly.
    """
    try:
        path = Path(table_path)
        if not path.exists():
            return {"success": False, "message": f"Table not found: {table_path}", "data": None}

        results: List[Dict[str, Any]] = []
        evidence: List[Dict[str, Any]] = []
        line_no = 0

        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line_no += 1
                if not line.strip():
                    continue
                try:
                    evt = json.loads(line)
                except Exception:
                    continue

                if not evt.get("@timestamp") and not _get_nested(evt, "event.id"):
                    evt = _normalize_enriched_event(evt, line_no, str(path))

                ts = evt.get("@timestamp") or _get_nested(evt, "event.created")
                if not ts or not _is_within_window(ts, start_ts, end_ts):
                    continue
                if not _match_filters(evt, filters):
                    continue

                results.append(evt)
                evidence.append(
                    {
                        "event_id": _get_nested(evt, "event.id") or evt.get("event_id") or evt.get("id"),
                        "table": str(path),
                        "line_number": line_no,
                        "timestamp": ts,
                    }
                )
                if len(results) >= limit or len(results) >= 5: # DEMO MODE: Force cap at 5
                    break

        return {
            "success": True,
            "message": f"Read {len(results)} events from {path.name}",
            "data": {"events": results, "evidence": evidence, "count": len(results)},
        }
    except Exception as e:
        return {"success": False, "message": f"Error reading events: {e}", "data": None}


def collect_related_entities(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Extract related entities touched by a set of events (users, hosts, IPs, resources).
    """
    try:
        users = set()
        hosts = set()
        src_ips = set()
        dst_ips = set()
        resources = set()

        for evt in events or []:
            u = _get_nested(evt, "user.name")
            if u:
                users.add(str(u).lower())
            h = _get_nested(evt, "host.name")
            if h:
                hosts.add(str(h).lower())
            sip = _get_nested(evt, "source.ip")
            if sip:
                src_ips.add(str(sip))
            dip = _get_nested(evt, "destination.ip")
            if dip:
                dst_ips.add(str(dip))
            res = _get_nested(evt, "resource.id") or _get_nested(evt, "resource.name")
            if res:
                resources.add(str(res))

        return {
            "success": True,
            "message": "Collected related entities",
            "data": {
                "users": sorted(users),
                "hosts": sorted(hosts),
                "source_ips": sorted(src_ips),
                "destination_ips": sorted(dst_ips),
                "resources": sorted(resources),
            },
        }
    except Exception as e:
        return {"success": False, "message": f"Error collecting related entities: {e}", "data": None}


def generate_threat_hunting_demo_dataset(
    dataset_root: str = DEFAULT_DATASET_ROOT,
    seed: int = 1337,
    end_ts: Optional[str] = None,
    days_history: int = 13,
) -> Dict[str, Any]:
    """
    Generate a deterministic synthetic threat hunting dataset locally.

    - History window: `days_history` days prior to the 24h hunt window
    - Hunt window: last 24 hours ending at end_ts (default: now UTC)
    """
    try:
        rng = random.Random(seed)
        root = Path(dataset_root)
        ref_dir = root / "reference"
        canonical_dir = root / "canonical"
        outputs_dir = root / "outputs"

        end_dt = _parse_ts(end_ts) if end_ts else _utcnow()
        start_dt = end_dt - timedelta(hours=24)
        history_start_dt = start_dt - timedelta(days=days_history)
        history_end_dt = start_dt

        # ---------------------------------------------------------------------
        # Reference data (small but sufficient)
        # ---------------------------------------------------------------------
        identities = {
            "svc_backup1": {
                "full_name": "Service Account: Backup Automation",
                "department": "IT Operations",
                "title": "Service Account",
                "manager": "mwilson",
                "location": "HQ",
                "employee_type": "service",
                "risk_score": 35,
                "groups": ["svc", "backup", "privileged"],
                "user_type": "service",
                "owner_team": "IT Ops",
                "privilege_level": "high",
            },
            "svc_etl2": {
                "full_name": "Service Account: ETL",
                "department": "Data Engineering",
                "title": "Service Account",
                "manager": "agarcia",
                "location": "HQ",
                "employee_type": "service",
                "risk_score": 20,
                "groups": ["svc", "etl"],
                "user_type": "service",
                "owner_team": "Data Eng",
                "privilege_level": "medium",
            },
            "jsmith": {
                "full_name": "John Smith",
                "department": "Engineering",
                "title": "Senior Developer",
                "manager": "bchen",
                "location": "Remote-US",
                "employee_type": "employee",
                "risk_score": 25,
                "groups": ["engineering"],
                "user_type": "human",
            },
            "contractor01": {
                "full_name": "External Contractor",
                "department": "Contractor",
                "title": "Contractor",
                "manager": "mwilson",
                "location": "Remote-EU",
                "employee_type": "contractor",
                "risk_score": 75,
                "groups": ["contractors"],
                "user_type": "human",
            },
            "mwilson": {
                "full_name": "Maria Wilson",
                "department": "IT Operations",
                "title": "IT Operations Manager",
                "manager": "dlee",
                "location": "HQ",
                "employee_type": "employee",
                "risk_score": 15,
                "groups": ["itops", "managers"],
                "user_type": "human",
            },
            "dlee": {
                "full_name": "David Lee",
                "department": "Security",
                "title": "Security Lead",
                "manager": None,
                "location": "HQ",
                "employee_type": "employee",
                "risk_score": 10,
                "groups": ["security", "admins"],
                "user_type": "human",
            },
        }

        assets = {
            "srv-backup-01": {
                "asset_id": "asset-srv-backup-01",
                "asset_type": "server",
                "criticality": "high",
                "owner": "IT Ops",
                "business_unit": "Operations",
                "environment": "production",
                "operating_system": "Windows Server 2022",
                "tags": ["backup", "scheduled"],
            },
            "jumpbox-01": {
                "asset_id": "asset-jumpbox-01",
                "asset_type": "server",
                "criticality": "high",
                "owner": "Security",
                "business_unit": "Security",
                "environment": "production",
                "operating_system": "Windows Server 2022",
                "tags": ["admin", "jumpbox"],
            },
            "srv-db-01": {
                "asset_id": "asset-srv-db-01",
                "asset_type": "server",
                "criticality": "critical",
                "owner": "Data Platform",
                "business_unit": "Finance",
                "environment": "production",
                "operating_system": "Linux",
                "tags": ["database", "pii"],
            },
            "ws-contractor-07": {
                "asset_id": "asset-ws-contractor-07",
                "asset_type": "workstation",
                "criticality": "medium",
                "owner": "Contractor",
                "business_unit": "External",
                "environment": "corp",
                "operating_system": "Windows 11",
                "tags": ["contractor"],
            },
        }

        geoip = {
            "10.0.0": {"country": "Internal", "city": "Private Network", "is_internal": True},
            "203.0.113": {"country": "US", "city": "New York", "is_internal": False},
            "198.51.100": {"country": "DE", "city": "Frankfurt", "is_internal": False},
        }

        threat_intel = {
            "198.51.100.25": {"category": "c2", "severity": 8, "label": "Synthetic C2"},
            "exfil-demo.example": {"category": "exfil", "severity": 6, "label": "Synthetic Exfil Domain"},
        }

        business_context = {
            "cloud_resources": {
                "s3://finance-exports": {"owner": "Finance", "sensitivity": "high"},
            },
            "applications": {
                "backup_service": {"owner": "IT Ops", "tier": "prod"},
            },
        }

        entity_resolution = {
            "svc_backup1": {"entity_id": "ent-svc-backup1", "entity_type": "service_account"},
            "svc_etl2": {"entity_id": "ent-svc-etl2", "entity_type": "service_account"},
            "jsmith": {"entity_id": "ent-user-jsmith", "entity_type": "user"},
            "contractor01": {"entity_id": "ent-user-contractor01", "entity_type": "user"},
        }

        allowlists = {
            "ent-svc-backup1": {
                "approved_hosts": ["srv-backup-01"],
                "approved_hours_utc": ["01", "02", "03"],
                "approved_cloud_resources": ["s3://finance-exports"],
                "approved_auth_methods": ["token"],
            }
        }

        _write_json(ref_dir / "identities.json", identities)
        _write_json(ref_dir / "assets.json", assets)
        _write_json(ref_dir / "geoip_synth.json", geoip)
        _write_json(ref_dir / "threat_intel_synth.json", threat_intel)
        _write_json(ref_dir / "business_context.json", business_context)
        _write_json(ref_dir / "entity_resolution.json", entity_resolution)
        _write_json(ref_dir / "allowlists.json", allowlists)

        # ---------------------------------------------------------------------
        # Canonical events generation
        # ---------------------------------------------------------------------
        ns = uuid.UUID("11111111-2222-3333-4444-555555555555")

        def mk_base(ts: datetime, category: str, action: str, outcome: str = "success") -> Dict[str, Any]:
            return {
                "event": {
                    "id": "",
                    "category": category,
                    "type": "info",
                    "action": action,
                    "outcome": outcome,
                },
                "@timestamp": _isoformat_z(ts),
                "pipeline": {"stage": "canonical", "schema_version": SCHEMA_VERSION},
            }

        # History: svc_backup1 does routine logins from srv-backup-01 at 02:xx UTC
        auth_events: List[Dict[str, Any]] = []
        cloud_events: List[Dict[str, Any]] = []
        process_events: List[Dict[str, Any]] = []
        dns_events: List[Dict[str, Any]] = []
        network_events: List[Dict[str, Any]] = []

        def add_evt(evt: Dict[str, Any], eid_parts: Tuple[str, ...]) -> Dict[str, Any]:
            evt_id = _stable_event_id(ns, *eid_parts)
            _set_nested(evt, "event.id", evt_id)
            return evt

        # Build daily baseline
        day = history_start_dt
        while day < history_end_dt:
            # One successful token auth
            ts = day.replace(hour=2, minute=rng.randint(0, 50), second=rng.randint(0, 59), microsecond=0)
            evt = mk_base(ts, "authentication", "login", "success")
            evt["user"] = {"name": "svc_backup1", "type": "service"}
            evt["host"] = {"name": "srv-backup-01"}
            evt["source"] = {"ip": f"10.0.0.{rng.randint(10, 60)}"}
            evt["authentication"] = {"method": "token"}
            auth_events.append(add_evt(evt, ("auth", "svc_backup1", evt["@timestamp"], "srv-backup-01")))

            # Optional: one cloud list/read (small)
            ts2 = day.replace(hour=2, minute=55, second=rng.randint(0, 59), microsecond=0)
            ce = mk_base(ts2, "cloud", "object_list", "success")
            ce["user"] = {"name": "svc_backup1", "type": "service"}
            ce["cloud"] = {"provider": "aws", "service": {"name": "s3"}, "region": "us-east-1"}
            ce["resource"] = {"type": "bucket", "id": "s3://finance-exports", "name": "finance-exports"}
            ce["source"] = {"ip": f"10.0.0.{rng.randint(10, 60)}"}
            cloud_events.append(add_evt(ce, ("cloud", "svc_backup1", ce["@timestamp"], "list")))

            day += timedelta(days=1)

        # Hunt window (last 24h): create 3 episodes
        # Episode 1: anomalous login from new host + abnormal time
        ep1_ts = start_dt + timedelta(hours=4, minutes=12, seconds=33)
        evt1 = mk_base(ep1_ts, "authentication", "login", "success")
        evt1["user"] = {"name": "svc_backup1", "type": "service"}
        evt1["host"] = {"name": "ws-contractor-07"}
        evt1["source"] = {"ip": "198.51.100.23"}
        evt1["authentication"] = {"method": "password"}
        evt1["correlation"] = {"id": "corr-episode-1"}
        auth_events.append(add_evt(evt1, ("auth", "svc_backup1", evt1["@timestamp"], "ws-contractor-07")))

        # Small failure before success (adds realism)
        ep1_fail_ts = start_dt + timedelta(hours=4, minutes=8, seconds=10)
        evt1f = mk_base(ep1_fail_ts, "authentication", "login", "failure")
        evt1f["user"] = {"name": "svc_backup1", "type": "service"}
        evt1f["host"] = {"name": "ws-contractor-07"}
        evt1f["source"] = {"ip": "198.51.100.23"}
        evt1f["authentication"] = {"method": "password"}
        evt1f["event"]["reason"] = "Invalid credentials"
        evt1f["correlation"] = {"id": "corr-episode-1"}
        auth_events.append(add_evt(evt1f, ("auth", "svc_backup1", evt1f["@timestamp"], "failure")))

        # Episode 2: remote execution on jumpbox then access to srv-db-01
        ep2_ts = start_dt + timedelta(hours=4, minutes=26, seconds=5)
        pe = mk_base(ep2_ts, "process", "process_start", "success")
        pe["user"] = {"name": "svc_backup1", "type": "service"}
        pe["host"] = {"name": "jumpbox-01"}
        pe["process"] = {
            "name": "powershell.exe",
            "command_line": "powershell.exe -NoP -NonI -W Hidden -EncodedCommand SQBFAFgA...",
            "pid": 4321,
            "parent": {"name": "wsmprovhost.exe"},
        }
        pe["correlation"] = {"id": "corr-episode-2"}
        process_events.append(add_evt(pe, ("proc", "jumpbox-01", pe["@timestamp"], "powershell")))

        ne = mk_base(ep2_ts + timedelta(minutes=2), "network", "connection", "success")
        ne["user"] = {"name": "svc_backup1", "type": "service"}
        ne["host"] = {"name": "jumpbox-01"}
        ne["source"] = {"ip": "10.0.0.50"}
        ne["destination"] = {"ip": "10.0.0.80", "port": 445}
        ne["network"] = {"transport": "tcp", "direction": "outbound", "bytes": 12000}
        ne["correlation"] = {"id": "corr-episode-2"}
        network_events.append(add_evt(ne, ("net", "jumpbox-01", ne["@timestamp"], "srv-db-01", "445")))

        pe2 = mk_base(ep2_ts + timedelta(minutes=6), "process", "process_start", "success")
        pe2["user"] = {"name": "svc_backup1", "type": "service"}
        pe2["host"] = {"name": "srv-db-01"}
        pe2["process"] = {"name": "ssh", "command_line": "ssh -i /tmp/key svc_backup1@10.0.0.80", "pid": 2201}
        pe2["correlation"] = {"id": "corr-episode-2"}
        process_events.append(add_evt(pe2, ("proc", "srv-db-01", pe2["@timestamp"], "ssh")))

        # Episode 3: cloud access burst
        ep3_ts = start_dt + timedelta(hours=5, minutes=5, seconds=0)
        for i in range(8):
            ce = mk_base(ep3_ts + timedelta(minutes=i * 2), "cloud", "object_get", "success")
            ce["user"] = {"name": "svc_backup1", "type": "service"}
            ce["cloud"] = {"provider": "aws", "service": {"name": "s3"}, "region": "eu-central-1"}
            ce["resource"] = {
                "type": "object",
                "id": "s3://finance-exports/exports/finance_dump.csv",
                "name": "finance_dump.csv",
            }
            ce["source"] = {"ip": "198.51.100.23"}
            ce["user_agent"] = {"original": "aws-cli/2.15.0"}
            ce["correlation"] = {"id": "corr-episode-3"}
            cloud_events.append(add_evt(ce, ("cloud", "svc_backup1", ce["@timestamp"], f"get-{i}")))

        # DNS event that ties to exfil-demo.example
        de = mk_base(ep3_ts - timedelta(minutes=3), "dns", "query", "success")
        de["user"] = {"name": "svc_backup1", "type": "service"}
        de["host"] = {"name": "ws-contractor-07"}
        de["source"] = {"ip": "198.51.100.23"}
        de["dns"] = {"question": {"name": "exfil-demo.example"}, "answers": [{"data": "198.51.100.25"}]}
        de["correlation"] = {"id": "corr-episode-3"}
        dns_events.append(add_evt(de, ("dns", "ws-contractor-07", de["@timestamp"], "exfil-demo.example")))

        # Write canonical tables
        counts: Dict[str, int] = {}
        counts["auth_events"] = _write_jsonl(canonical_dir / "auth_events.jsonl", auth_events)
        counts["process_events"] = _write_jsonl(canonical_dir / "process_events.jsonl", process_events)
        counts["network_events"] = _write_jsonl(canonical_dir / "network_events.jsonl", network_events)
        counts["dns_events"] = _write_jsonl(canonical_dir / "dns_events.jsonl", dns_events)
        counts["cloud_audit_events"] = _write_jsonl(canonical_dir / "cloud_audit_events.jsonl", cloud_events)

        # Manifest
        manifest = {
            "dataset_name": "threat_hunting_demo",
            "schema_version": SCHEMA_VERSION,
            "generated_at": _isoformat_z(_utcnow()),
            "generator_seed": seed,
            "history_window": {"start_ts": _isoformat_z(history_start_dt), "end_ts": _isoformat_z(history_end_dt)},
            "hunt_window": {"start_ts": _isoformat_z(start_dt), "end_ts": _isoformat_z(end_dt)},
            "tables": {
                "auth_events": "canonical/auth_events.jsonl",
                "process_events": "canonical/process_events.jsonl",
                "network_events": "canonical/network_events.jsonl",
                "dns_events": "canonical/dns_events.jsonl",
                "cloud_audit_events": "canonical/cloud_audit_events.jsonl",
            },
            "references": {
                "identities": "reference/identities.json",
                "assets": "reference/assets.json",
                "geoip": "reference/geoip_synth.json",
                "threat_intel": "reference/threat_intel_synth.json",
                "business_context": "reference/business_context.json",
                "entity_resolution": "reference/entity_resolution.json",
                "allowlists": "reference/allowlists.json",
            },
            "row_counts": counts,
        }
        _write_json(root / "manifest.json", manifest)

        # Small README
        (root / "README.md").write_text(
            "\n".join(
                [
                    "# Threat Hunting Demo Dataset (Synthetic, Local-Only)",
                    "",
                    "This dataset is generated locally for demonstrating an agentic threat hunting workflow.",
                    "",
                    "Key files:",
                    "- `manifest.json`: dataset metadata and file pointers",
                    "- `canonical/*.jsonl`: canonical event tables",
                    "- `reference/*.json`: enrichment and resolution reference data",
                    "",
                    "Regenerate with the Threat Hunting Data tools (`generate_threat_hunting_demo_dataset`).",
                    "",
                ]
            ),
            encoding="utf-8",
        )

        outputs_dir.mkdir(parents=True, exist_ok=True)

        return {
            "success": True,
            "message": f"Generated dataset at {root}",
            "data": {
                "dataset_root": str(root),
                "manifest_path": str((root / "manifest.json").resolve()),
                "row_counts": counts,
                "hunt_window": manifest["hunt_window"],
                "history_window": manifest["history_window"],
            },
        }
    except Exception as e:
        return {"success": False, "message": f"Error generating dataset: {e}", "data": None}
