# Generated by NeuroStack
# Artifact: tool/weather_fetcher.py

"""Weather fetcher tool using OpenWeatherMap API.

Retrieves current weather information for a given city. Use this tool when you need
to get real-time weather data including temperature, conditions, humidity, and wind speed.
"""

import os
from typing import Optional
import requests
from dotenv import load_dotenv

# Load environment variables before any access
load_dotenv(override=True)


async def get_weather(city: str, api_key: Optional[str] = None) -> dict:
    """Get current weather information for a city.
    
    Fetches current weather data from the OpenWeatherMap API, including temperature,
    weather description, humidity, and wind speed.
    
    Args:
        city: Name of the city to get weather for (e.g., "London", "New York", "Tokyo").
        api_key: OpenWeatherMap API key. If not provided, reads from OPENWEATHERMAP_API_KEY
                 environment variable.
    
    Returns:
        Success: {"status": "success", "result": {"city": str, "temperature": float,
                  "description": str, "humidity": int, "wind_speed": float, "units": str}}
        Error: {"status": "error", "error_message": str}
    """
    # Validate city input
    if not city or not isinstance(city, str):
        return {
            "status": "error",
            "error_message": "City name must be a non-empty string"
        }
    
    city = city.strip()
    if not city:
        return {
            "status": "error",
            "error_message": "City name cannot be empty"
        }
    
    # Get API key
    key = api_key or os.getenv("OPENWEATHERMAP_API_KEY")
    if not key:
        return {
            "status": "error",
            "error_message": "OpenWeatherMap API key is required. Set OPENWEATHERMAP_API_KEY environment variable or pass api_key parameter"
        }
    
    # Build API request
    base_url = "https://api.openweathermap.org/data/2.5/weather"
    params = {
        "q": city,
        "appid": key,
        "units": "metric"  # Use Celsius
    }
    
    try:
        # Make API request
        response = requests.get(base_url, params=params, timeout=10)
        
        # Handle different HTTP status codes
        if response.status_code == 404:
            return {
                "status": "error",
                "error_message": f"City '{city}' not found. Please check the spelling and try again"
            }
        elif response.status_code == 401:
            return {
                "status": "error",
                "error_message": "Invalid API key. Please check your OpenWeatherMap API key"
            }
        elif response.status_code == 429:
            return {
                "status": "error",
                "error_message": "API rate limit exceeded. Please try again later"
            }
        elif response.status_code != 200:
            return {
                "status": "error",
                "error_message": f"API request failed with status code {response.status_code}"
            }
        
        # Parse response
        data = response.json()
        
        # Extract weather information
        result = {
            "city": data.get("name", city),
            "temperature": data["main"]["temp"],
            "description": data["weather"][0]["description"],
            "humidity": data["main"]["humidity"],
            "wind_speed": data["wind"]["speed"],
            "units": "metric (°C, m/s)"
        }
        
        return {
            "status": "success",
            "result": result
        }
        
    except requests.exceptions.ConnectionError:
        return {
            "status": "error",
            "error_message": "Network connection error. Please check your internet connection"
        }
    except requests.exceptions.Timeout:
        return {
            "status": "error",
            "error_message": "Request timed out. Please try again"
        }
    except requests.exceptions.RequestException as e:
        return {
            "status": "error",
            "error_message": f"Request failed: {str(e)}"
        }
    except (KeyError, IndexError) as e:
        return {
            "status": "error",
            "error_message": f"Failed to parse API response: {str(e)}"
        }
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Unexpected error: {str(e)}"
        }
