# Generated by NeuroStack
# Vendored from platform origin: agent/documentation_agent (upstream_version=platform)

"""
Documentation Agent module for automated documentation generation and maintenance.
"""

from .agent import root_agent, runner

__all__ = ["root_agent", "runner"]
