# Generated by NeuroStack
# Vendored from platform origin: agent/documentation_agent (upstream_version=platform)

from __future__ import annotations

from google.adk import Agent
from google.genai import types
from google.adk.tools import load_memory

import importlib.util as _ilu
import pathlib as _pl
_spec_mcp_internal_documentation = _ilu.spec_from_file_location(
    'documentation',
    _pl.Path(__file__).parent.parent.parent / 'mcp_servers' / 'internal' / 'documentation.py',
)
_mod_mcp_internal_documentation = _ilu.module_from_spec(_spec_mcp_internal_documentation)
_spec_mcp_internal_documentation.loader.exec_module(_mod_mcp_internal_documentation)
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)

SYSTEM_PROMPT = _mod_rel_prompt.SYSTEM_PROMPT

documentation = _mod_mcp_internal_documentation.create_mcp_server
documentation_agent = Agent(
    name="documentation_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description="Specialized agent for automated documentation generation and maintenance using MCP toolsets.",
    instruction=SYSTEM_PROMPT,
    tools=[
        documentation(),
        load_memory,
    ],
    generate_content_config=types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = documentation_agent
