# Generated by NeuroStack
# Artifact: agent/sample_tenant_agent_2


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

# No MCP servers configured





# ============================================================================
# AGENT DEFINITION
# ============================================================================

sample_tenant_agent_2 = Agent(
    name="sample_tenant_agent_2",
    model='gemini/gemini-2.5-flash',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[


    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = sample_tenant_agent_2
