# Generated by NeuroStack
# Vendored from platform origin: agent/containment_agent (upstream_version=platform)

"""containment_agent using Google ADK."""
from __future__ import annotations
from google.adk import Agent
from google.adk.tools import load_memory
from google.genai import types
import importlib.util as _ilu
import pathlib as _pl
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)
_spec_tools_containment_tools = _ilu.spec_from_file_location(
    'containment_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'containment_tools.py',
)
_mod_tools_containment_tools = _ilu.module_from_spec(_spec_tools_containment_tools)
_spec_tools_containment_tools.loader.exec_module(_mod_tools_containment_tools)

SYSTEM_PROMPT = _mod_rel_prompt.SYSTEM_PROMPT
isolate_host = _mod_tools_containment_tools.isolate_host
disable_account = _mod_tools_containment_tools.disable_account
block_ip = _mod_tools_containment_tools.block_ip
revoke_tokens = _mod_tools_containment_tools.revoke_tokens

def create_containment_agent() -> Agent:
    return Agent(
        name="containment_agent",
        model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
        description="Executes approved containment actions against a compromised asset.",
        instruction=SYSTEM_PROMPT,
        tools=[
            isolate_host,
            disable_account,
            block_ip,
            revoke_tokens,
            load_memory
        ],
        generate_content_config=types.GenerateContentConfig(
            safety_settings=[types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            )]
        ),
    )

containment_agent = create_containment_agent()
root_agent = containment_agent
